### ISSUE TITLE
Global setting for the cover image location preference

### ISSUE THREAD

**Issue by MageJohn** [geigi/cozy#104]
It would be good to support covers that are separate from the audio files - e.g a file named folder.jpg, cover.jpg, or similar. It's easier to set a custom cover by changing this file than editing the metadata of a book. Ideally it should be possible to set the choice of where to find the cover, whether in a file or in the tags, on a per book basis.

This would tie in to issue #102 as well, allowing books with no tags to have covers.

**Comment by geigi** [comment]
This feature was already implemented by someone but I didn't test it a lot. Did it not work for you? How are your image files named?

**Comment by MageJohn** [comment]
The image is called `folder.jpg`. However I just tested it with `cover.jpg`, `[book name].jpg`, and converting all three to png. After adding each different version I restarted the app and re-scanned the directory. 
For now I've only tested it with the one audiobook, but I have more I could download if you think it would help.

**Comment by MageJohn** [comment]
I just had a look at the PR that added cover from file support, #72. It seems to only load the cover from the file if there wasn't a picture in the tags. That means this isn't a bug, as my book has a cover in the tags. Personally, I'd prefer to have the image loaded instead of the tags, but I'm sure other people would prefer it the other way. I think it might need to be a setting, possibly on a per book basis. I would say the default should be to load the image instead of the tags, because the image is the easiest to change, but it's up to you. I know python, so I'd do the PR myself, but I'm unbelievably busy at the moment. :sweat_smile:

**Comment by geigi** [comment]
Hey thanks for looking into it ;) I think I prefer to implement this as an global setting first. Sometime in the future  I'll add more advanced tagging features. Then it would be nice to have this setting for each book :)

**Comment by geigi** [comment]
The feature is implemented and will be shipping with the next version ;)
