### ISSUE TITLE
Cozy crashes on F27 at Gst.Bin init

### ISSUE THREAD

**Issue by Warmuser** [geigi/cozy#106]
After the installation cozy doesn't start on Fedora 27 with latest updates.

**Comment by geigi** [comment]
Hey,
can you post the cozy log file (`~/.local/share/cozy/cozy.log`) here?

**Comment by Warmuser** [comment]
Ok, I opened it, but the only thing written into the .log file is the directory "~/.local/share/cozy/cozy.log" that you specified.

**Comment by geigi** [comment]
Ok seems like the log file is empty then... Can you try start cozy from the commandline and post the output here? 
`com.github.geigi.cozy`
or if you're running the flatpak
`flatpak run com.github.geigi.cozy`

**Comment by Warmuser** [comment]
I didn't know there was a flatpak version, anyway its work perfectly the flatpak one. These are the commands that I write yesterday to install manually Cozy (before to install te flatpak version): 

sudo dnf config-manager --add-repo https://download.opensuse.org/repositories/home:geigi/Fedora_27/home:geigi.repo

sudo dnf install com.github.geigi.cozy

**Comment by Warmuser** [comment]
This is what I get If I run the first command you suggested me:

[newuser@localhost ~]$ com.github.geigi.cozy
Traceback (most recent call last):
  File "/usr/bin/com.github.geigi.cozy", line 35, in <module>
    from cozy.ui import CozyUI
  File "/usr/lib/python3.6/site-packages/cozy/ui.py", line 10, in <module>
    from cozy.book_element import BookElement
  File "/usr/lib/python3.6/site-packages/cozy/book_element.py", line 4, in <module>
    from cozy.player import *
  File "/usr/lib/python3.6/site-packages/cozy/player.py", line 78, in <module>
    init()
  File "/usr/lib/python3.6/site-packages/cozy/player.py", line 61, in init
    __audiobin = Gst.Bin("audioline")
TypeError: GObject.__init__() takes exactly 0 arguments (1 given)
[newuser@localhost ~]$ 

If I run the second command, the app starts without problems.

**Comment by Warmuser** [comment]
Ok, thanks anyway for the help! :)

**Comment by geigi** [comment]
Sure :) I'm glad the flatpak version is working fine for you :)

**Comment by Warmuser** [comment]
Many Thanks! :)
