### ISSUE TITLE
Can't run cozy on Ubuntu 16.04

### ISSUE THREAD

**Issue by peledzius** [geigi/cozy#107]
So I'm trying to install Cozy on Ubuntu 16.04 with ```dpkg -i com.github.geigi.cozy_0.5.5_amd64.deb```, but I'm receiving this error: 
```
dpkg: dependency problems prevent configuration of com.github.geigi.cozy:
 com.github.geigi.cozy depends on python3-peewee; however:
  Package python3-peewee is not installed.

dpkg: error processing package com.github.geigi.cozy (--install):
 dependency problems - leaving unconfigure
```
There is no ```python3-peewee``` package in Ubuntu repository and I coudn't find it anywhere else.
I installed it with ```pip3 install peewee``` and Cozy works, but dependency error still showing up:
```
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 com.github.geigi.cozy : Depends: python3-peewee but it is not installable
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).
```
Command ```apt-get -f install``` just removes ```com.github.geigi.cozy``` package.

**Comment by geigi** [comment]
You can find the missing dependency in the repository which also provides cozy. It's a bit messy because of other dependency issues I'm not able to provide cozy for 16.04 in this repository. You can find the instructions on how to add the repo here:
https://software.opensuse.org//download.html?project=home%3Ageigi&package=python3-peewee

**Comment by peledzius** [comment]
Thanks, it's working now without dependency issues. But there is other problem in Cozy: it only plays one chapter of my book and stops. Cozy not showing all chapters list in my audiobook. Cozy theme is not changing to dark. Buttons ```Playback speed```, ```Sleep timer``` and ```Search your library``` not giving me any menu when pressed. But ```Options``` button works fine.

**Comment by peledzius** [comment]
I installed flatpak and Cozy with it. Now it works perfectly, thanks.

**Comment by geigi** [comment]
Awesome :)
