### ISSUE TITLE
Cozy interprets "Artist" metadata field as "Author" for mp3's and "Reader" for m4a/mp4's.

### ISSUE THREAD

**Issue by Wowfunhappy** [geigi/cozy#110]
I have a collection of DRM-free audiobooks from a variety of different sources. I save some books as mp3's and some as m4a's—m4a, with the aac codec, is a superior format, but some stores don't offer it, and I don't want to re-encode a lossy source.

To keep the metadata consistent regardless of source, I've been tagging these files myself. Regardless of format, I always use the "Artist" tag to designate author, and I leave out the reader.

For whatever reason, Cozy sees the author of MP3 audiobooks correctly. However, m4a audiobooks are listed under "Unknown author", and lists the correct author as the "Reader".

I'm not entirely sure whether this is a bug in Cozy or an error in how I've been tagging. It seems odd to me that the same field would be interpreted differently for mp3's vs m4a's, but maybe there's a standard spec which Cozy is adhering too, and which differs between the two formats? Anecdotally, I have not found any consistency between the various places I purchase audiobooks (Audiobooksnow.com, downpour.com, audiobookstore.com, MP3 CD's, among others), which is why I started tagging everything myself in the first place.

**Comment by geigi** [comment]
Hey, thanks for reporting, this might be a bug, I'll have a look. 
Currently the correct behaviour would be that the artist tag contains the reader and the composer tag the author, because this is how most of my audiobooks had been tagged. But it's a bit of a mess, everybody does it differently.
I'll add a switch to the settings which allows you to swap the reader/author assignment globally in the next version ;)

**Comment by Wowfunhappy** [comment]
Thanks!

I do wonder if there could be a more intelligent rule, instead of a simple setting. For instance, maybe if the composer tag is unset, Cozy could default to artist = author? My logic is that very few books are going to list a reader but not an author, and artist is the more prominent tag.

**Comment by geigi** [comment]
Very nice idea!

**Comment by geigi** [comment]
I've implemented this and it'll be shipping in the next version ;) I'll add a force refresh database option in the settings which you'll need to do to get your tags correctly imported.
