### ISSUE TITLE
Can't finish second Importing Audiobooks after editing the TAGs in EasyTAG in Cozy 0.5.4

### ISSUE THREAD

**Issue by f3spirit** [geigi/cozy#111]
Have Linux Solus Budgie on SSD and private Files (Audiobooks) on a HDD. (But not my Linux User Folder up to now, also have to hang the HDD Drive in with Disks at startup).

Problem:
When I chose a Folder on my HDD to Import around 25 Audiobooks in mp3 format.
The Import starts till the progress bar is around 90% finished, then the "ball" is still turning but for hours nothing happens any more.
Also this Problem starts after I edit the Audiobook TAGS with EasyTAG. So under Author for example are things shown that came from the Import before the EasyTAG edits.

In Rhythmbox the Import from the HDD works fine.
In Lollypop I also have Problems, only one Book gets imported.
EasyTAG can read the Files normally and edit them.

My Setup:
Solus 3.9996 Budgie
Gnome 3.28.1
Intel® Xeon(R) CPU E3-1230 v3 @ 3.30GHz × 8
31.4 GiB ECC
EVGA Nvidia 780
Samsung 850 SSD (Solus + Linux User Folder)
1 TB HDD (my stuff)

_I would like to help. So if you have questions, or I should test something you are welcome. :)_

**Comment by geigi** [comment]
Hey, thanks for offering your help :) could you post the cozy log files from 
```
~/.local/share/cozy/cozy.log
```
here?

**Comment by f3spirit** [comment]
I get back:
/home/free/.local/share/cozy/cozy.log: No such file or directory


Hartmut Döring

info@hartmutdoering.de

**Comment by geigi** [comment]
Which version of cozy are you using?

**Comment by f3spirit** [comment]
I use
Cozy 0.5.4

######## This gives Disks about my HDD ########
The Hard Drive the Audio books are stored is:

Model:
ST1000DM003-1CH162 (CC49)

Size:
1.0 TB (1,000,204,886,016 bytes)
1.0 TB — 310 GB free (69.0% full)

Partitioning:
GUID Partition Table

Serial Number:
Z1D8YEX5

Assesment:
Disk is OK (33° C / 91° F)

Device
/dev/sdb2

UUID:
3E9C56DF9C5690EF

Partition Type:
Basic Data

Contents:
NTFS — Mounted at /mnt/3E9C56DF9C5690EF

At the start of the HDD is a small NTFS Partition (Microsoft Reserved) /dev/sdb1
And at the end is a 1.8 MB Free Space.
This stuff is left over from my Dualboot set up i had before I used Solus only now. I will change this to ext4 when my new hard drive arives in 2 days.

**Comment by geigi** [comment]
Could you try importing your files again with cozy 0.5.5? The importer is a lot more robust in this version, it sounds like it crashed for you with 0.5.4.

**Comment by geigi** [comment]
I found a how-to report outdated software for Solus: https://www.reddit.com/r/SolusProject/comments/55w3j9/flagging_out_of_date_software/

**Comment by f3spirit** [comment]
Oki, I read the post but have difficulty to understand everything correctly. I think I need a bit more time to figure this all out to really be of use. But thank you for pointing me in the right direction.

Have a great day

**Comment by geigi** [comment]
Awesome :) let me know if you have any problems with 0.5.5
