### ISSUE TITLE
Barely visible descriptions for actions

### ISSUE THREAD

**Issue by natanielcz** [geigi/cozy#112]
### Bug/Feature description
After installing cozy we can see welcome screen with some default action to perform but descrtiptions are barely visible if we have light theme enabled
![screenshot from 2018-05-27 10-57-03](https://user-images.githubusercontent.com/1231703/40584266-3a74c8bc-619e-11e8-8c8b-7e216c1ba73b.png)
If we change theme to dark it looks much better
![screenshot from 2018-05-27 10-57-22](https://user-images.githubusercontent.com/1231703/40584269-44528658-619e-11e8-87fe-2bcb4bb53930.png)

but even in dark theme this text could be a little bit lighter.

### Steps to reproduce
1. Install cozy
2. Run cozy (the issue is on the welcome screen)

### System Information
- Operating System: Ubuntu 18.04
- Installation source: Flathub
- Version of cozy: 0.5.5

**Comment by geigi** [comment]
It looks like you're not using the default gtk theme. The default Ubuntu gtk theme does not have this issue. I'm pretty sure this is a bug in the theme you're using.
