### ISSUE TITLE
Cannot find my book collection directory

### ISSUE THREAD

**Issue by bhmevik** [geigi/cozy#115]
### Bug/Feature description
I cannot get cozy to find the directory where I keep my audio books, which is /data/bok/lyd.
### Steps to reproduce
On initial startup:
- Choose "Other..." in the pulldown menue under "Change Audiobooks Folder"
- Click on "Other Locations"
- Click on the "Computer" line in the "On This Computer"
That lists some of the directories in / on the computer (in addition to "app"): bin, dev, etc, home, lib, lib64, proc, run, sbin, sys, tmp, usr, var, but a few are missing, namely boot, data, media, mnt, opt, root, srv

I also tried clicking on Home, because I have a symlink to /data/bok there, but the symlink is simply listed as a 9 byte long file, so I guess cozy is not supporting symlinks.

I've also tried dragging folders from /data/bok/lyd with the default Gnome file handler (nautilus) into cozy, but that had no apparent effect.

### System Information
- Operating System: Debian Stretch (9.4)
- Installation source: Flatpak:
flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install --user flathub com.github.geigi.cozy
- Version of cozy: 0.5.5

**Comment by geigi** [comment]
Hey :) this is a restriction from the flatpak release currently. You can change this yourself, have a look at the readme FAQ section: file:///android_asset/md/#i-have-my-audiobooks-in-a-location-that-is-not-accessible-in-the-flatpak-sandbox
I'll also make this the default setting with the next flatpak release ;)

**Comment by bhmevik** [comment]
Duh! How could I miss that one?! Sorry for not reading the docs (properly)! :)

**Comment by geigi** [comment]
No worries ✌️
