### ISSUE TITLE
Unable to import mp3's but able to import some. 

### ISSUE THREAD

**Issue by wanderwitch** [geigi/cozy#117]
I have been attempting to migrate from linux mint to elementary os and everything is going fine except for cozy. It has chosen some of the mp3's to import but refuses to import others.

This occurs whenever i attempt to import the audio books into cozy, despite having worked perfectly on my previous build.

Current operating system: Elementary Os Loki 0.4.1
Installed cozy through the appcenter
cozy version is 0.6.0

Log dump:
17:16:09[MainThread  ] [main      ] [INFO ]  ('"elementary"', '0.4.1', 'loki')
17:16:09 [MainThread  ] [main      ] [INFO ]  Starting up cozy 0.6.0
17:16:09 [MainThread  ] [db        ] [ERROR]  Could not connect to database. 
17:16:09 [MainThread  ] [db        ] [ERROR]  Connection already opened.
17:16:10 [MainThread  ] [ui        ] [INFO ]  Initialize main window
17:16:10 [Thread-2    ] [offline_ca] [INFO ]  Startet processing queue
17:16:10 [MainThread  ] [titlebar  ] [INFO ]  Replaying the previous 30 seconds.
17:20:21 [UpdateDataba] [importer  ] [WARNI]  Skipping file /home/hali/Audiobooks/Balance/Ep. 55. The Suffering Game - Chapter Five.mp3 because of mime type application/octet-stream.
17:20:22 [UpdateDataba] [importer  ] [WARNI]  Skipping file /home/hali/Audiobooks/Balance/Ep. 68. Story and Song - Finale, Part Two.mp3 because of mime type application/octet-stream.
17:20:23 [UpdateDataba] [importer  ] [WARNI]  Skipping file /home/hali/Audiobooks/Balance/Ep. 69. Story and Song - Finale, Part Three.mp3 because of mime type application/octet-stream.
17:20:24 [UpdateDataba] [importer  ] [WARNI]  Skipping file /home/hali/Audiobooks/Balance/Ep. 37. The Crystal Kingdom - Chapter Nine.mp3 because of mime type application/octet-stream.
17:20:25 [UpdateDataba] [importer  ] [WARNI]  Skipping file /home/hali/Audiobooks/Balance/Ep. 63. The Stolen Century - Chapter Four.mp3 because of mime type application/octet-stream.
17:20:26 [UpdateDataba] [importer  ] [WARNI]  Skipping file /home/hali/Audiobooks/Amnesty/The Adventure Zone - Episode - 03.mp3 because of mime type application/octet-stream.
17:20:26 [UpdateDataba] [importer  ] [WARNI]  Skipping file /home/hali/Audiobooks/Amnesty/The Adventure Zone - Episode - 09.mp3 because of mime type application/octet-stream.
17:20:26 [UpdateDataba] [importer  ] [WARNI]  Skipping file /home/hali/Audiobooks/Amnesty/The Adventure Zone - Episode - 05.mp3 because of mime type application/octet-stream.
17:20:26 [UpdateDataba] [importer  ] [WARNI]  Skipping file /home/hali/Audiobooks/Amnesty/The Adventure Zone - Episode - 06.mp3 because of mime type application/octet-stream.
17:20:26 [UpdateDataba] [importer  ] [WARNI]  Skipping file /home/hali/Audiobooks/Amnesty/The Adventure Zone - Episode - 01.mp3 because of mime type application/octet-stream.
17:20:26 [UpdateDataba] [importer  ] [WARNI]  Skipping file /home/hali/Audiobooks/Amnesty/The Adventure Zone - Episode - 02.mp3 because of mime type application/octet-stream.
17:20:26 [UpdateDataba] [importer  ] [WARNI]  Skipping file /home/hali/Audiobooks/Amnesty/The Adventure Zone - Episode - 04.mp3 because of mime type application/octet-stream.
17:20:26 [UpdateDataba] [importer  ] [WARNI]  Skipping file /home/hali/Audiobooks/Amnesty/The Adventure Zone - Episode - 07.mp3 because of mime type application/octet-stream.
17:20:26 [UpdateDataba] [importer  ] [WARNI]  Skipping file /home/hali/Audiobooks/Amnesty/The Adventure Zone - Episode - 08.mp3 because of mime type application/octet-stream.
17:20:26 [UpdateDataba] [importer  ] [WARNI]  Skipping file /home/hali/Audiobooks/Amnesty/The Adventure Zone - Episode - 00.mp3 because of mime type application/octet-stream.
17:20:26 [UpdateDataba] [importer  ] [INFO ]  Total import time: 6.576308727264404
17:20:26 [UpdateDataba] [offline_ca] [INFO ]  Startet processing queue
17:20:29 [MainThread  ] [ui        ] [INFO ]  Closing.
17:20:29 [MainThread  ] [titlebar  ] [INFO ]  Closing.
17:20:29 [MainThread  ] [player    ] [INFO ]  Closing.
17:20:29 [MainThread  ] [db        ] [INFO ]  Closing.
17:20:29 [MainThread  ] [ui        ] [INFO ]  Closing app.
17:20:29 [MainThread  ] [ui        ] [INFO ]  App closed.

**Comment by wanderwitch** [comment]
Update. It seems that easytag and others mess with the MIME tag as well as the id3 tags. Use of puddletag is able to restore proper MIME tag.

**Comment by wanderwitch** [comment]
Update. Update. Was only a fluke It seems that nearly all mp3's are being seen as mime type application/octet-stream

**Comment by wanderwitch** [comment]
Update. Update. Update. (yes it's a bit)

The mime type application/octet-stream seems to be triggered by album art being included in the mp3. removal of the album art and resetting the id3 tags seems to fix the issue

**Comment by geigi** [comment]
Hey thanks for digging into this! I've also quite some mp3 files with embedded album art (mostly tagged with easytag) but didn't experience this issue. Did you re-add the id3 tags after resetting them? Or are you only able to import the files without tags?

**Comment by wanderwitch** [comment]
I used puddletag to remove all the id3 tags and then stripped the album art out. I added some of the tags back. I currently have the files imported but as soon as embedded art is put into the mp3 it triggers the error. It is repeatable. Even with verified mp3's. Some mp3's can have album art but most can't.

Also the system I am using is a fresh install of Elementary OS. Out of the box fresh.

Also a little quirk i have found is that flac files always import. But that can fill a drive quickly due to the uncompressed nature of the standard.

I have yet to successfully i port aac, m4a files as well. They return the same octet stream error.

**Comment by wanderwitch** [comment]
Just had a thought as i was grabbin the PPA for Kodi. Making so the importer uses the file name as the primary information grabber, similar to how the Kodi scrappers work. Make sure it is in a prescribed format and then cozy can sort it out from there. then it can use the id3 tags to fill in blanks.

Example:
File name: [audiobook title] - [Author] - [Chapter name+number]

maybe something along those lines. Just a shower thought

**Comment by geigi** [comment]
I researched a bit and this could be a bug in the package `file`. Could you try weather this suggestion works for you:
https://superuser.com/a/445418

Maybe it's also a missing gstreamer dependency. Do you have `gstreamer1.0-plugins-good`, `
gstreamer1.0-libav` and `gstreamer1.0-plugins-ugly` installed on your system?

About your showerthought:
I prefer using ID3 tags as primary source as everybody names their files differently. Some have folders for each audiobook, some don't, etc... When I implement something like this it would be a random naming scheme of many possibilities. Currently when no tags are available the book name is taken from the folder name and the title is taken from the file name.

**Comment by wanderwitch** [comment]
Good news. Editing the magic file and the magic.mime file in /etc/ root did fix the mp3 issue. i have been able to import all mp3's now. i will be doing aac and other file format testing later as i need to grab all the gstreamer stuff. Perhaps a fix could be introduced to append the magic and magic.mime files upon install?

**Comment by geigi** [comment]
Hey thanks a lot for testing this! What did you exactly add to the `magic.mime` file?

**Comment by wanderwitch** [comment]
howdy I added this block of 6 lines of code into the `magic.mime` file it doesn't want to copy paste properly here most likely it's due to user ineptitude but
https://superuser.com/a/445418
here is what i edited

[magic.mime.txt](https://github.com/geigi/cozy/files/2152167/magic.mime.txt)
a txt copy of my magic.mime file too

**Comment by netlexer** [comment]
I believe this problem is caused by incorrectly rendered id3tag frames within the mp3 file. 
I solved this by running each mp3 file through id3convert (on Arch linux this is contained within the id3lib package.)   Cozy was then able to correctly identify the mp3's. There is no need to alter any magic files.

**Comment by geigi** [comment]
@netlexer sorry for the late answer ... Do you expect to handle cozy those files anyway even though they don't contain proper id3 tags?

**Comment by StoneyFish** [comment]
(Great App) Import was working fine , upgraded to 0.6.1b (Flatpak)
"Some files could not be imported"
This is happening to all my new "Big Finish"  audio mp3 books. The mp3s play fine from the file manager.  Some do get imported but are missing the artwork. I played around with EasyTag, PuddleTag and even id3convert. None of them helped resolve the import errors. It seems older "Big Finish" titles are importing ok.

**Comment by lxqueen** [comment]
I think this may depend on the file size of the embedded art? Which would fit with the Big Finish problem, I've had this too.

I'm guessing it could be this because in the case of their older releases they used to embed smaller art files and just ship the larger covers as an extra JPG, whereas for their more recent releases they ship both in the same size and quality (usually a 1417x1417 image roughly 2 MB in size).

**Comment by pokemontotalwar** [comment]
I'm currently running into this issue. Converted a couple m4b and m4a files to mp3 using m4b-tools, which uses ffmpeg to convert, so cozy could handle them, and it refuses to import the converted files. I've tried id3convert, and my system doesn't have any magic mime files.

I'm running Manjaro KDE at the moment, everything up to date.

**Comment by JohannPopper** [comment]
Yeah, same on Solus 4 here, most recent updates using Cozy v0.6.7. Absolutely won't import any of my mp3 drm-free audiobooks. ID3 tags have been purged, edited, etc, as suggested above. Changed file name conventions, confirmed files are perfect as they play as normal with every player except Cozy. Nothin doin. Sadly, something weird is happening. I miss my Cozy.

**Comment by pokemontotalwar** [comment]
Will do as soon as I'm at my computer. I generally use the AUR version, but tested the Flatpak before reporting so I could be more accurate -- neither version works for me.

**Comment by JohannPopper** [comment]
Hi. Sorry it took me so long to get back to you here -- I left the country for a while with no net. The audiobook in question for me was a purchase from audible that i had burned to cd with iTuneslong ago, then forgot about, then ripped as mp3s. I thought "what if the cd rip was bad somehow?", so I reconverted the mp3s to ogg and mp3 again via audacity and both new formats were instantly and perfectly recognizable by Cozi. So, in my case at least, I think the issue was my own fault due to old copy protection weirdness from iTunes. I would suggest other users with this problem reconvert problematic mp3s from any legit source, though. I can still post the log from the old files import if you wish (which I had no need to look at yet), but I don't think it was a Cozy problem after all.

**Comment by geigi** [comment]
Alright! Thanks for letting me know! I’m glad your files are working now 😊

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by geigi** [comment]
I just pushed an update (0.6.11) which should fix this issue. Thanks everyone for reporting :)

**Comment by geigi** [comment]
Cozy 0.7 is out with a completely new importer! This should work with every mp3 file you can play back with any other media player on your system.
