### ISSUE TITLE
How can I reset cozy?

### ISSUE THREAD

**Issue by ersanchez** [geigi/cozy#119]
### Bug/Feature description

Unwanted files (music) are inadvertently imported upon first launch of cozy.

### Steps to reproduce

Launch cozy for the first time and pick your music folder (doh!) instead of your audiobook folder.  :)

How can I 'reset' cozy so that it forgets all of the music? I can't find the config file.

### System Information
- Operating System: Ubuntu 18.04
- Installation source: flatpak
- Version of cozy: 0.60

**Comment by geigi** [comment]
Hey :) all config is stored in 
```
~/.local/share/cozy
```
Alternatively you can add your audiobook folder in settings, set it as default and remove your music folder ;)

**Comment by ersanchez** [comment]
Thanks a ton!   :)
I am really enjoying cozy.  :+1:

**Comment by rpgdev** [comment]
> Hey :) all config is stored in
> 
> ```
> ~/.local/share/cozy
> ```
> 
> Alternatively you can add your audiobook folder in settings, set it as default and remove your music folder ;)

Where is this file? I can't find it on Fedora KDE even though I have used Cozy daily for a while with several preferences set.

**Comment by geigi** [comment]
Thanks, I’ll add this info to the faq :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
