### ISSUE TITLE
"Chapter" is misspelled in Preferences window

### ISSUE THREAD

**Issue by lxqueen** [geigi/cozy#121]
### Bug/Feature description
Pretty self-explanatory, see below.

![Highlighted image](https://i.imgur.com/OleIUuX.png)

### Steps to reproduce
Go to **Preferences > Appearance**, and read the second option from the top.

### System Information
- **Operating System:** Solus 3.9999, kernel 4.9.119-104.lts
- **Installation source:** Flatpak (via Flathub)
- **Version of cozy:** 0.6.0

**Comment by geigi** [comment]
Thanks for reporting :) I'm currently quite busy but it'll get fixed at some point ;)

**Comment by lxqueen** [comment]
No problem :) one day I'll get around to looking at and building the code myself, I'm probably spending too much time actually listening to audio haha
