### ISSUE TITLE
Support for multiple discs?

### ISSUE THREAD

**Issue by lxqueen** [geigi/cozy#122]
### Bug/Feature description
Having audiobooks with multiple discs is currently a little messy - the track numbering works fine but there's no easy visual hint as to where a disc starts or stops (see below).

![Current state of multi-disc support](https://i.imgur.com/dEeWae4.png)

### Proposal
A simple heading with some extra padding above should suffice, I've done a quick mockup below of what it could look like in theory (using the Adapta-Eta theme, for reference). Maybe mess around with the disc label positioning though, I couldn't find one I liked so left it there. Also, the icon used is `media-optical-cd-audio-symbolic`, looking through Adwaita's icon files. Also it might look fine dropping the *Disc* part of the label and just leaving the number there, as the icon should give enough context.

Ideally, disc headings should only be shown on multi-disc audiobooks, and ignored completely where there's either no disc number or the disc number only equals 1. _(I mention both as prerequisites because it'd be nice to see a "disc 2" heading even if disc 1 is missing, it's a nice hint to tell you either tagging or importing screwed up somewhere, or for larger works where you only own part of it maybe?)_

![Proposed mockup of multi-disc support](https://i.imgur.com/3qO1wIA.png)

### Steps to reproduce
Import an audiobook tagged with multiple discs.

### System Information
- **Operating System:** Solus 3.9999, kernel 4.9.119-104.lts
- **Installation source:** Flatpak (via Flathub)
- **Version of cozy:** 0.6.0

**Comment by lxqueen** [comment]
Quick addition to this just because:

According to [this part of the GNOME HIG](https://developer.gnome.org/hig/stable/visual-layout.html.en) the space between each disc should ideally be 18 pixels. Do as you wish with that information.

**Comment by geigi** [comment]
@lxqueen I like the idea a lot! Looks very nice and I like how you thought about when displaying the disc labels and when not. I'm currently quite busy and don't have a lot of time, but I'll try to release a small update soon and I'll include this :)

**Comment by geigi** [comment]
I've implemented this and it'll ship with the next update :)
