### ISSUE TITLE
How to remove entries or clear database? 

### ISSUE THREAD

**Issue by wavecycle** [geigi/cozy#124]
### Bug/Feature description
I've accidentally added music from my "Music" folder and I can't remove that folder's files

### Steps to reproduce
* I added my first audiobook folder "/Documents/Audio Books Fiction" successfully and listened to one

* I then wanted to add another folder (non fiction)... 

* in preferences, storage tab I clicked "+" to add another storage location

* I clicked on "File System" thinking it would drill down to select folder

* system started adding from entire system including music from /Music

* I halted the process after sometime. Did a hard shut down of app and restarted

* I removed the "File System" storage location and rescanned the directory from the main menu "Scan Directory" 

* after long scan and even restart I can still see music in the directory and don't know how to remove it. I don't want music in here

Thank you! 

### System Information
- Operating System: Ubuntu 18.04 
- Installation source: flatpak instructions on github
- Version of cozy: 0.60

**Comment by geigi** [comment]
Hey,
best is to delete the cozy database and start fresh (this will delete all saved progress). Remove those folders:
```
~/.local/share/cozy
~/.cache/cozy
```

**Comment by wavecycle** [comment]
thanks for the quick answer.

> best is to delete the cozy database and start fresh (this will delete all saved progress). Remove those folders: ~/.local/share/cozy

I deleted this folder

> ~/.cache/cozy

This folder does not exist. I checked twice, both nautilus and console. I then restarted cozy and the music is still visible. I rescanned but it makes no difference.

**Comment by geigi** [comment]
The important folder is .local/share/cozy (the folder is hidden). The cache 
folder is not as important.

**Comment by wavecycle** [comment]
Sorry, I was ambiguous:

I deleted: /.local/share/cozy
I could not find: ~/.cache/cozy

After deleting only the hidden /.local/share/cozy folder, I restarted cozy and there was no difference to the imported content; the music was still present.

**Comment by geigi** [comment]
Ok that's weird, could you search your home folder for a file named 
"cozy.db" (including hidden folders)?

**Comment by wavecycle** [comment]
Note: I initially tried to install through software centre unsuccessfully first, then tried off git and finally got it working with flatpak.
![cozy_db](https://user-images.githubusercontent.com/19392059/45235207-72975300-b2d8-11e8-97dc-6572da81e66d.png)

**Comment by geigi** [comment]
Ahh sorry, I ignored that you're using flatpak. The folder in .var/app 
should be the right one!

**Comment by wavecycle** [comment]
That worked, thank you :)
