### ISSUE TITLE
ImportError when starting cozy (flatpak installation)

### ISSUE THREAD

**Issue by elya5** [geigi/cozy#128]
### Bug/Feature description
When I try to start cozy, I get the following error:
```
Traceback (most recent call last):
  File "/app/bin/com.github.geigi.cozy", line 35, in <module>
    from cozy.ui import CozyUI
  File "/app/lib/python3.5/site-packages/cozy/ui.py", line 8, in <module>
    from cozy.book_element import BookElement
  File "/app/lib/python3.5/site-packages/cozy/book_element.py", line 4, in <module>
    import cozy.db as db
  File "/app/lib/python3.5/site-packages/cozy/db.py", line 16, in <module>
    from playhouse.sqliteq import SqliteQueueDatabase
ImportError: No module named 'playhouse.sqliteq'
```

### Steps to reproduce
- Install cozy from flathub
- Try to run it

### System Information
- Operating System: Fedora 28
- Installation source: Flathub
- Version of cozy: 0.6.1

**Comment by Meresmata** [comment]
Hi, 

 I currently also have one problem importing the audiobooks. I used **drag and drop from  /home/username/  subfolders.**
The audiobooks are **mp3s, vorbis (.ogg) and opus (.ogg, .opus).** format.

I am using the **0.6.1** version on **Xubuntu 18.04** and retrieved cozy from **flathub**.

**Comment by geigi** [comment]
@Meresmata Could you please create a separate issue and post the file `.var/app/com.github.geigi.cozy/data/cozy/cozy.log` after trying to import those files?

**Comment by elya5** [comment]
I installed it from flathub. I tried both g-s-m and the terminal and the same issue appears.
I'm running the 64bit version. The `playhouse` module seems to exists and the folder contains a `sqliteq` file.

**Comment by geigi** [comment]
Can you confirm that cozy is running with python3 and that the `PYTHONPATH` is correct?

**Comment by elya5** [comment]
I added 
```
print(sys.version)
print(sys.path)
```
and it shows
```
3.5.2 (default, Sep 21 2018, 14:56:44) 
[GCC 6.4.0]
['/app/bin', '/usr/lib/python35.zip', '/usr/lib/python3.5', '/usr/lib/python3.5/plat-linux', '/usr/lib/python3.5/lib-dynload', '/home/user/.local/lib/python3.5/site-packages', '/usr/lib/python3.5/site-packages', '/usr/lib/python3.5/site-packages/setuptools-22.0.5-py3.5.egg', '/app/lib/python3.5/site-packages']
```

**Comment by elya5** [comment]
The flatpak is working now

**Comment by geigi** [comment]
Nice, thanks for testing!
