### ISSUE TITLE
Not reading ogg/opus metadata

### ISSUE THREAD

**Issue by chron-isch** [geigi/cozy#132]
### Bug/Feature description
I just noticed that Cozy is not reading ogg metadata. When you import anything in ogg it always shows as 'Unknown Author'.

### Steps to reproduce
Import an OGG-file.

### System Information
- Operating System: ArchLinux 
- Installation source: Arch AUR
- Version of cozy: 0.6.1b

**Comment by monreal** [comment]
I can still reproduce this in the latest version. As I use the flatpak ogg opus seems to be the filetype of choice (mp3 does not work).

**Comment by geigi** [comment]
Mp3 should work in the flatpak version. But this is a different issue. Could you create a new issue for this with some information about your mp3s?

**Comment by naraesk** [comment]
Using the AUR package on ArchLinux as well and I don't have any problems with ogg, They are imported as expected

**Comment by geigi** [comment]
The current version has improved ogg and opus support. Feel free to reopen if the issue still exists :)
