### ISSUE TITLE
Cannot start Cozy on Juno

### ISSUE THREAD

**Issue by DanyGee** [geigi/cozy#133]
### Bug/Feature description
Cannot start Cozy
### Steps to reproduce
1. Install from Appcenter
2. Launch from the menu
3. Launch from terminal to see what is wrong
### System Information
- Operating System: 
elementary OS Juno
- Installation source: 
Appcenter
- Version of cozy: 
0.6.3
 ### Error message
```
com.github.geigi.cozy
Traceback (most recent call last):
  File "/usr/bin/com.github.geigi.cozy", line 35, in <module>
    from cozy.ui import CozyUI
  File "/usr/lib/python3/dist-packages/cozy/ui.py", line 8, in <module>
    from cozy.book_element import BookElement
  File "/usr/lib/python3/dist-packages/cozy/book_element.py", line 4, in <module>
    import cozy.db as db
  File "/usr/lib/python3/dist-packages/cozy/db.py", line 7, in <module>
    from peewee import __version__ as PeeweeVersion
ModuleNotFoundError: No module named 'peewee'
```

**Comment by geigi** [comment]
Thanks for reporting :) this is a bug in elementarys app center: https://github.com/elementary/houston/issues/656
But maybe I can find a solution to push a working release

**Comment by geigi** [comment]
There is a workaround, but it's still broken at elementary's side.
Here is the workaround: https://github.com/geigi/cozy/issues/141#issuecomment-444012040
You have to install the package `python3-peewee` manually.

**Comment by geigi** [comment]
Finally this issue is fixed :)
