### ISSUE TITLE
A setting for inverting author and reader tag assignment

### ISSUE THREAD

**Issue by leighss** [geigi/cozy#139]
Great work!
I have searched but cant find out which Tag fields are used for Author and Reader (& any others?) by Cozy

Edit: Found [this ](https://github.com/geigi/cozy/issues/110)closed issue 

So is the below current behaviour?

artist tag contains the reader and the composer tag the author
 if the composer tag is unset, Cozy defaults to artist = author

This (or correct if above wrong) info might be useful in FAQ?

**Comment by geigi** [comment]
Thanks! :) This is correct. 
I think it would be useful to also have a setting for this so the user can also invert this behaviour (artist = author, composer = reader by default).
I'm leaving this issue open as reference for the setting and as a reminder for FAQ ;)

**Comment by leighss** [comment]
Thanks
My tags were all over the place so it was just a case of knowing what was used by cozy so that I could then tidy things up with Puddletag
BTW Puddletag couldn't load some of my files - any sugestions for alternative tag management app (linux or I can grudgingly also boot into Win10)?
Thanks again

**Comment by geigi** [comment]
I’ve used easytag which worked quite well: https://wiki.gnome.org/Apps/EasyTAG <https://wiki.gnome.org/Apps/EasyTAG>

**Comment by leighss** [comment]
Thanks, works well :)

**Comment by geigi** [comment]
This is possible since a while now! :)
