### ISSUE TITLE
Missing Library: Elementary os

### ISSUE THREAD

**Issue by JohnJohnstone** [geigi/cozy#147]
### Bug/Feature description

Application does not launch. I ran the application from the cli and notived it was looking for a python library peewee. After installing `python3-peewee` the application runs without issue.

### Steps to reproduce

Install from elementary appstore
Run application

### System Information
- Operating System: elementary OS 5.0 Juno 
- Installation source: elementary appstore
- Version of cozy:

**Comment by geigi** [comment]
Duplicate #141
