### ISSUE TITLE
Audio books are displayed as one audio book

### ISSUE THREAD

**Issue by elya5** [geigi/cozy#152]
### Bug/Feature description
I have several audio books which consist of one, big mp3 file. They are all stored in the same directory. Cozy seems to think they are all part of the same audio book although they have different authors and titles. 

Is there any explanation how audio book should be organized so that cozy understands it?

### System Information
- Operating System: Fedora 29
- Installation source: Flathub
- Version of cozy: 0.6.7

**Comment by geigi** [comment]
Hey,

Sorry for the late answer... If the audio files contain tags cozy will detect the books correctly. You can do this e.g. with a program named **easytag**. Here is a short tutorial: https://fedoramagazine.org/easytag-organize-your-music-on-fedora/

**Comment by geigi** [comment]
Closing because there wasn’t any answer... feel free to reopen the issue if you still experience problems
