### ISSUE TITLE
Picture not Displaying 

### ISSUE THREAD

**Issue by Sweetstud** [geigi/cozy#154]
### System Information
- Operating System:  Ubuntu 18.04
- Installation source:  flatak
- Version of cozy: 0.6.7

**Comment by geigi** [comment]
Can you specify more on what’s your issue is? Which picture do you want to display? Where is it saved? (Embedded tag or as separate file?)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by geigi** [comment]
Closing because no additional info was posted
