### ISSUE TITLE
Chapter Time Format Only Displays minutes/seconds (not Hours:Min:Sec)

### ISSUE THREAD

**Issue by JHDeerin** [geigi/cozy#156]
### Bug/Feature description
When listening to audiobook chapters that are over 1 hour long, the time format never updates to the hours/minutes/seconds left in the chapter, but only the total number of minutes/seconds remaining:
![cozy_chapterTime](https://user-images.githubusercontent.com/22411098/61759094-49b76980-ad95-11e9-9619-e2a4a03d7404.png)

However, when viewing the time remaining in the whole book, the correct hour/minutes/seconds format is used:
![cozy_wholeBookTime](https://user-images.githubusercontent.com/22411098/61759185-ae72c400-ad95-11e9-9599-33a49d02ed9c.png)

This could be intentional, but feels more like a small oversight to me; I would've expected it to use the Hour:Min:Sec format for both settings.

If it's helpful, the relevant code seems to be at [lines 208-220 of titlebar.py](https://github.com/geigi/cozy/blob/e4cc1cee10d4c3decf267f4eb968511fa27c4ce2/cozy/titlebar.py#L208).

*Note that in this particular example, I'm listening to a `.mp3` file that hasn't been properly formatted with chapters*
### Steps to reproduce
1. Play an audiobook that has a chapter longer than 1 hour.
2. Go to Preferences>Appearance>Titlebar and make sure `Display the whole book instead of the current chapter` is disabled
### System Information
- Operating System: Ubuntu 18.04 Bionic Beaver
- Installation source: Flatpak (via Flathub)
- Version of cozy: 0.6.7

**Comment by geigi** [comment]
Thanks for reporting!
