### ISSUE TITLE
Doesn't work with audiobooks on NAS

### ISSUE THREAD

**Issue by abssorb** [geigi/cozy#157]
Flatpak is too limited. Can't use NAS or any kind of file sharing.

Hoping this will make it into official repos.

**Comment by geigi** [comment]
I'll look into this. Maybe flatpak can be made to work with network drives.

**Comment by abssorb** [comment]
Thanks - I've discovered it can work with network drives, though I can't say how.
See GIMP for an example.  Just installed this via flatpak and it can access the NAS no problem.

One gotcha I had to workaround is although flatpak is in the 18.04 repos, it's way behind the maintained version at: https://flatpak.org/setup/Ubuntu/

**Comment by geigi** [comment]
The latest flatpak release can now access network drives 😊
