### ISSUE TITLE
Does not recognize mp4-files

### ISSUE THREAD

**Issue by rakor** [geigi/cozy#159]
### Bug/Feature description
Cozy does not recognize mp4-files. 

### Steps to reproduce
Try to import a mp4-file

### System Information
- Operating System: 
Debian Buster
- Installation source:
Flathub 
- Version of cozy:
0.6.7

**Comment by geigi** [comment]
Only m4a files are supported as most mp4 files do contain a video stream. If your files only contain audio you can simply rename them to m4a :)
