### ISSUE TITLE
Windows does not fit small screens

### ISSUE THREAD

**Issue by rakor** [geigi/cozy#160]
### Bug/Feature description
I have an GPD Pocket 2 wit an 7" Display (1920*1200 - scaled). The window does not fit on the screen properly.

### Steps to reproduce
Open cozy on a small screen.

### System Information
- Operating System: 
Debian Buster
- Installation source: 
Flathub
- Version of cozy: 
0.6.7

**Comment by rakor** [comment]
As a audiobook-player is a very nice application on the go, it would be nice to have the gui be optimised for the upcoming Librem 5 too. :)

**Comment by Poopooracoocoo** [comment]
https://gitlab.gnome.org/GNOME/libhandy/

**Comment by geigi** [comment]
Libhandy is awesome :) currently I'm focusing on a new and improved importer and later on m4b support. After that I will have a look at the UI and libhandy again :)

**Comment by geigi** [comment]
The next version of Cozy will feature a responsive design for the main window :)
