### ISSUE TITLE
No metadata analyzed in m4a-Files

### ISSUE THREAD

**Issue by rakor** [geigi/cozy#162]
### Bug/Feature description
when importing m4a-files the metadata is not analyzed nor displayed. So the audiobook is named after the Folder it is in. Author and other data is not used.

### Steps to reproduce
import m4a-file with metadata

### System Information
- Operating System: 
Debian Buster
- Installation source:
Flatpak 
- Version of cozy: 
0.6.7

**Comment by geigi** [comment]
This issue should be resolved with the latest version of Cozy, it features a completely new importer. Feel free to reopen when the issue still exists :)
