### ISSUE TITLE
Errors with python 3.8

### ISSUE THREAD

**Issue by shastry** [geigi/cozy#182]
Running cozy on python 3.8 fails with:
```
AttributeError: module 'platform' has no attribute 'dist'
```
I believe `platform.dist()` is removed in python3.8 and it's recommended to use distro from https://pypi.org/project/distro/ .

Relevant files:
`main.py`
`cozy/tools.py`

**Comment by emmaliddell** [comment]
I created a PR for this. #183

**Comment by geigi** [comment]
Pull request is merged, I need to verify the elementaryOS specific code (which I may simply remove at this point) is still working before creating a new release.
