### ISSUE TITLE
Question: Page0

### ISSUE THREAD

**Issue by libreajans** [geigi/cozy#186]
There is a "Page0" string which was marked as translatable in that file (https://github.com/geigi/cozy/blob/master/data/ui/main_window.ui)

Would you confirm for me that is is a translatable string?

```
              <packing>
                <property name="name">book_overview</property>
                <property name="title" translatable="yes">page0</property>
                <property name="position">3</property>
              </packing>
```

**Comment by geigi** [comment]
This is not a translatable string, but a placeholder which I forgot to remove. Thanks for reporting :)
