### ISSUE TITLE
Split sentence in book_progress_element.ui

### ISSUE THREAD

**Issue by libreajans** [geigi/cozy#187]
There are two strings in the PO files from book_progress_element.ui (https://github.com/geigi/cozy/blob/master/data/ui/book_progress_element.ui)

There are "of" and "remaining". It is really hard to translate this kind of split sentences.

Gnome always advice never split sentences (https://wiki.gnome.org/TranslationProject/DevGuidelines/Never%20split%20sentences)

Would it possible to make these strings a sentence? 

Plus: Thanks for everyone, I have finished translating it to Turkish just now.

**Comment by geigi** [comment]
Thanks for reporting :) I'll have to think of a solution for this one.
