### ISSUE TITLE
Use open-menu-symbolic for preferences button

### ISSUE THREAD

**Issue by donadigo** [geigi/cozy#19]
The button in the HeaderBar for opening the popover with additional options could use the `open-menu-symbolic` icon for a better fit. Additionaly you could change it so that it uses an icon size of 24. (https://lazka.github.io/pgi-docs/Gtk-3.0/enums.html#Gtk.IconSize, `LARGE_TOOLBAR`)

**Comment by geigi** [comment]
Hey, this button appears automatically (I didn't create the button or the popover) and contains the app actions that I've added. Is it still possible to change the icon somehow?

**Comment by donadigo** [comment]
You currently call `set_app_menu` here: https://github.com/geigi/cozy/blob/master/cozy/ui.py#L212, instead, create a `Gtk.MenuButton` with the open-menu-symbolic icon: https://lazka.github.io/pgi-docs/Gtk-3.0/classes/MenuButton.html, add it to the headerbar at the end using `pack_end` or in your UI file. Then set it to not use the popover and set a menu model for it.

**Comment by geigi** [comment]
Ah thank you! I will add it manually then :)
