### ISSUE TITLE
On Arch, pip itself seems to be required to run Cozy

### ISSUE THREAD

**Issue by Krutonium** [geigi/cozy#227]
### Bug/Feature description
Unable to start Cozy after installing it from the AUR. It installs, but does not run, producing the below error.
### Steps to reproduce
```
com.github.geigi.cozy (<= Command to run it)
Traceback (most recent call last):
  File "/usr/bin/com.github.geigi.cozy", line 28, in <module>
    import distro
ModuleNotFoundError: No module named 'distro'
```

Installing python-pip fixes this.

### System Information
- Operating System: Arch Linux
- Installation source: AUR
- Version of cozy: 0.6.10

**Comment by geigi** [comment]
It’s not pip that is required but python-distro. Seems like this is missing in the arch packaging info.

**Comment by geigi** [comment]
Fixed :)
