### ISSUE TITLE
Missing cover in GNOME Shell notifications

### ISSUE THREAD

**Issue by k-kirill** [geigi/cozy#240]
### Bug description
Book cover is missing in GNOME Shell notifications
![missing_cover_in_gnome_shell_notifications](https://user-images.githubusercontent.com/8539168/75166360-cd26a800-5734-11ea-9eaf-e51e19902dce.png)

### Steps to reproduce
Open GNOME Shell notifications while some book is played in Cozy

### System Information
- Operating System: openSUSE Tumbleweed
- Installation source: an official RPM, cozy-0.6.12-1.1.noarch
- Version of cozy: 0.6.12

**Comment by geigi** [comment]
Thanks for reporting!
