### ISSUE TITLE
Position slider jumps on dragging

### ISSUE THREAD

**Issue by k-kirill** [geigi/cozy#248]
### Bug description
Position slider in the app header jumps on dragging
![unfriendly_slider](https://user-images.githubusercontent.com/8539168/75494493-6e2f9000-59cd-11ea-8426-d8bcb038f817.gif)

### Steps to reproduce
Drag the position slider for an audio file longer than an hour

### System Information
- Operating System: openSUSE Tumbleweed
- Installation source: an official RPM, cozy-0.6.12-1.1.noarch
- Version of cozy: 0.6.12

**Comment by geigi** [comment]
Thanks for reporting :) Will be fixed in the next release.
