### ISSUE TITLE
Flatpak support

### ISSUE THREAD

**Issue by fbruetting** [geigi/cozy#25]
Would you please provide Flatpak support?

**Comment by nedrichards** [comment]
Hey there, I made a flatpak manifest for cozy, [available in this gist](https://gist.github.com/nedrichards/bfa0369e5cfe35ffdfa5e8bda844bf55). Feel free to take it! This probably needs a bit more GStreamer tweaking (I suspect you'd want to ensure you were bundling AAC playback but I just followed the build instructions).

My recommendation would be adding this to [flathub](https://flathub.org/), where you can control everything - but it builds for x86 and ARM, and makes it a bit easier for users to discover the app and get updates. I'd be very happy to help you get it on there if you wish.

**Comment by geigi** [comment]
Hey that's awesome! Thanks a lot! I'll test this with all the file formats that should be supported and publish it on flathub ;)

**Comment by nedrichards** [comment]
Sweet! Thanks

**Comment by nedrichards** [comment]
Cozy is now [available on flathub](https://github.com/flathub/com.github.geigi.cozy)!

**Comment by fbruetting** [comment]
Many thanks!
