### ISSUE TITLE
Add AppImage releases

### ISSUE THREAD

**Issue by codesnippy** [geigi/cozy#258]
Would it be possible to also release the application in a AppImage format.

**Comment by geigi** [comment]
I tried to release an AppImage about 2 years ago but didn't succeed. 

For now there are no plans for providing an AppImage. If somebody that knows how to package this format is willing to build an GitHub Actions integration for it I'm happy to to include this :) Although I would focus on supporting the flatpak/flathub release as the majority of people use this and

**Comment by geigi** [comment]
@ anybody: If you want to contribute the AppImage packaging, feel free to reopen :)
