### ISSUE TITLE
MP3 Files not played

### ISSUE THREAD

**Issue by B-codes** [geigi/cozy#267]
### Bug/Feature description
I've exported m4b files using FFMPEG to get something supported by Cozy. Unfortunately, it just gives an error when I add the files. These files play fine on any other music/video player. 

### Steps to reproduce
Import an MP3 exported from M4b with FFMPEG 

Command used:
`ffmpeg -i book.m4b -ss 0.000000 -to 103.096599 chapter1.mp3`

### System Information
- Operating System: Ubuntu 20.04
- Installation source: Flatpack
- Version of cozy: 0.6.16

**Comment by geigi** [comment]
Hey,

thanks for reporting :) This is a known issue. Sadly detecting mp3's is a difficult task which cozy doesn't support very well yet. A lot of mp3's do get detected but some still don't work. I've some solutions in mind but there isn't a quick fix...

Until this is properly fixed I recommend converting to m4a, ogg/opus or flac. Those should import fine.

**Comment by geigi** [comment]
I've found a quick fix for an mp3 file created with ffmpeg like you did. After testing I'll release a new version later this week.

**Comment by geigi** [comment]
The fix will be included in the next version I'm releasing now. Feel free to reopen if it doesn't work as expected :)
