### ISSUE TITLE
How to set metadata for a book?

### ISSUE THREAD

**Issue by windyweather** [geigi/cozy#270]
### Bug/Feature description
Can't find documentation for how to set meta data for a book. Title seems to come from directory name. I'd like to set whatever else that Cozy will see. At least Author maybe short description.
### Steps to reproduce
For example, I have audio book directory named "R A Salvatore" containing all audio books for "Legend of Drizzt" book series. Each book as a file. I can see how to set "book title" by naming directory. But Cozy reports "Author Unknown" I have searched and cannot find documentation for how Cozy finds this. Can you point to doc of where meta data is found? I'd like to supply all that I can manually.

A pointer to documentation is fine. I could not find another way to send a message to developers to ask this question.
Thanks much. Cozy is very nice.

### System Information
- Operating System: Linux Mint 18, 19
- Installation source: flathub
- Version of cozy: 0.6.16
![Screenshot from 2020-05-15 08-41-12](https://user-images.githubusercontent.com/4505159/82070698-f860c980-9689-11ea-8d4e-58472d2dbdc5.png)
![Screenshot from 2020-05-15 08-40-34](https://user-images.githubusercontent.com/4505159/82070707-fd257d80-9689-11ea-873b-0dad394a4f6c.png)
![Screenshot from 2020-05-15 08-43-05](https://user-images.githubusercontent.com/4505159/82070713-ff87d780-9689-11ea-8efe-746b8b4cb42e.png)

**Comment by geigi** [comment]
Hey :) I‘ve done the metadata tagging for my audiobooks with a program named **easytag**. Here is a guide on how to use it: https://www.tecmint.com/easytag-edit-mp3-track-info-linux/

Using the directory names for the book name is only a fallback when no tags within the audio files are present. Setting the author/reader without metadata is currently not possible, they will always be „unknown author“. Therefore I suggest using easytag to prepare your files :) Does this help you?

**Comment by geigi** [comment]
You can skip the installation part of the guide. Easytag is available from the regular Linux mint repositories :)

**Comment by windyweather** [comment]
ok, Sure I've used those programs. Just need to figure out what the tags are I've used an MP3Tag program on windows too. Thanks that answers my question.

**Comment by windyweather** [comment]
Woops. That failed. Worked fine with AudioBooks on Windows. Plays in VLC and native player on Linux Mint, but Cozy rejects my audio books after adding tags. What's the problem please. Is there some log to check for more info?

![Screenshot from 2020-05-16 10-41-02](https://user-images.githubusercontent.com/4505159/82126742-7ba21e00-9763-11ea-85ba-6e113d3995bd.png)
![MP3TagProgram](https://user-images.githubusercontent.com/4505159/82126751-85c41c80-9763-11ea-8147-89f373c33369.png)
![WitcherWorksFineOnCozy](https://user-images.githubusercontent.com/4505159/82126752-85c41c80-9763-11ea-9e89-01cd61559ea5.png)
![LegendOfDrizztFailsWithCozy](https://user-images.githubusercontent.com/4505159/82126753-865cb300-9763-11ea-8ed3-18f466124d6e.png)
![LegendOfDrizztMoreTags](https://user-images.githubusercontent.com/4505159/82126754-865cb300-9763-11ea-983e-d1c54f948fbd.png)

**Comment by geigi** [comment]
This issue is sadly quite common. I've found a possible quick fix for this which I will release this week. I'm not sure whether it works for all mp3 files but it should be able to detect quite a lot more files.

**Comment by geigi** [comment]
The fix will be included in the next version. I'm closing this issue now but feel free to reopen if the issue still persists :)
