### ISSUE TITLE
Cannot open a regular mp3 file

### ISSUE THREAD

**Issue by OnkelTem** [geigi/cozy#284]
### Bug/Feature description

I have a book in a set of mp3 files. I specified that directory as my audiobooks directory. Then Cozy showed me a screen with the list of my files and error message saying: **Some files could not me imported.** 

MP3 file mediainfo:

```
General
Format                                   : MPEG Audio
File size                                : 20.0 MiB
Duration                                 : 21 min 51 s
Overall bit rate mode                    : Constant
Overall bit rate                         : 128 kb/s

Audio
Format                                   : MPEG Audio
Format version                           : Version 1
Format profile                           : Layer 3
Format settings                          : Joint stereo / MS Stereo
Duration                                 : 21 min 51 s
Bit rate mode                            : Constant
Bit rate                                 : 128 kb/s
Channel(s)                               : 2 channels
Sampling rate                            : 32.0 kHz
Frame rate                               : 27.778 FPS (1152 SPF)
Compression mode                         : Lossy
Stream size                              : 20.0 MiB (100%)
```

### System Information
- Operating System: Linux Kubuntu 18.04
- Installation source: flatpak
- Version of cozy: 0.6.17

**Comment by astize** [comment]
Hi OnkelTem,

Have you installed the gstreamer-libav plugin? This is required for MP3/4 support but may not necessarily be automatically installed (it wasn't for me on Arch)

**Comment by geigi** [comment]
Hey,
thanks for reporting :) This is most likely an issue with the tag importer. MP3s are quite difficult to detect (sadly). Could you provide the file you tried to import or does it contain copyrighted material? You can also have a look at the other issues regarding this topic:
https://github.com/geigi/cozy/issues/267
https://github.com/geigi/cozy/issues/260
https://github.com/geigi/cozy/issues/226
https://github.com/geigi/cozy/issues/117

**Comment by OnkelTem** [comment]
Hi, folks!

Thanks for referencing those issues - mine seems to have the same cause.

Here is a screenshot:
![image](https://user-images.githubusercontent.com/114060/85692028-b6da2a00-b6dd-11ea-81c5-f594a8e1d307.png)

There are 4 files listed out from 6. Why the other two were not mentioned — IDK.

So let me upload one of the erroneous and one that was "ok".

https://yadi.sk/d/vPcAn6O6JlM32Q - this is one of the bad ones;
https://yadi.sk/d/u4KqSMknm-9Pag - this one was not reported in the message.

**Comment by OnkelTem** [comment]
Meanwhile I converted the files to OGG and they have been imported well finally. Thanks to https://github.com/geigi/cozy/issues/260#issuecomment-626866221

**Comment by geigi** [comment]
Thanks! I'll have a look at the files. But I'm glad you've found a solution for now. I'll leave this issue open until I investigated your files.

**Comment by geigi** [comment]
I've fixed the issue in this commit: https://github.com/geigi/cozy/commit/bad0034f41ad67f12df27667761ae4eed7468a52
Thanks again for reporting! :)
