### ISSUE TITLE
Parse multiple authors and list each one separately

### ISSUE THREAD

**Issue by bhokarala** [geigi/cozy#288]
Currently, authors are just listed by whatever is in the tag data. Multiple authors should be parsed and each author should be listed separately. The parser should be able to handle different author separators (e.g., / ; , and &).

In the following example, there should just be four individual authors listed--Amy Chua, Jed Rubenfeld, John Tierney, and Roy F. Baumeister:

![20200615 1554 cozy](https://user-images.githubusercontent.com/39920389/84700047-8c8bae00-af20-11ea-8961-a786681fd97a.png)

### System Information
- Operating System: Linux Mint 19.3 (Ubuntu 18.04)
- Installation source: flatpak
- Version of cozy: 0.6.18

**Comment by geigi** [comment]
Hey,
thanks for your suggestion! This would be indeed a nice feature.

**Comment by geigi** [comment]
**Progress tracking**
Branch: split-author-reader

- [x] Implement and test splitting of strings in python maps
- [x] Use the new splitting function in the library filters
- [ ] Reimplement Search to use the `Library` class

**Comment by geigi** [comment]
This feature is now implemented and will ship with the next version :)
