### ISSUE TITLE
Universal Format Package for Cozy? (Snap, AppImage, Flatpak)

### ISSUE THREAD

**Issue by MichaelTunnell** [geigi/cozy#29]
I know there is already an issue for Flatpak but I dont think you should limit your decision to just Flatpak and instead should also try out Snaps or AppImages.

Why Snaps? - https://insights.ubuntu.com/2017/10/11/elementary-on-why-snaps-are-right-for-their-linux-distro/

Why AppImages? - https://appimage.org/

Why Flatpaks? - http://flatpak.org/#features

Quick Note: I'd prefer a Snap or an AppImage if looking for opinions. :)

**Comment by geigi** [comment]
Thanks for already providing information! I'll have a look at those options ;)

**Comment by probonopd** [comment]
Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/) central directory of available AppImages

[Here is an overview](https://github.com/probonopd/AppImageKit/wiki/AppImages) of projects that are already distributing upstream-provided, official AppImages.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

**Comment by geigi** [comment]
@probonopd Hey, I'm currently trying to create an AppImage for Cozy using the OpenSuse build service, but I'm running into some issues I couldn't resolve and couldn't find anything about. I also didn't get any help on the IRC, maybe you can help me here? This is my appimage.yml: https://build.opensuse.org/package/view_file/home:geigi:branches:OBS:AppImage:Templates/Cozy/appimage.yml?expand=1
The build works until I add the dependencies as ingredients - then it fails:
```
[   46s] -----------------------------------------------------------------
[   46s] ----- building appimage.yml (user abuild)
[   46s] -----------------------------------------------------------------
[   46s] -----------------------------------------------------------------
[   46s] creating repository metadata...
[   49s] Spawning worker 0 with 51 pkgs
[   49s] Spawning worker 1 with 51 pkgs
[   49s] Spawning worker 2 with 51 pkgs
[   49s] Spawning worker 3 with 51 pkgs
[   49s] Spawning worker 4 with 51 pkgs
[   49s] Spawning worker 5 with 51 pkgs
[   49s] Spawning worker 6 with 51 pkgs
[   49s] Spawning worker 7 with 51 pkgs
[   49s] Workers Finished
[   49s] Saving Primary metadata
[   49s] Saving file lists metadata
[   49s] Saving other metadata
[   49s] rpm: no arguments given for query
[   49s] ERROR: Can not find a unique desktop file for  defined in App: tag
[   49s] 
[   49s] lamb09 failed "build appimage.yml" at Wed Nov  8 13:42:43 UTC 2017.
```
It seems like that the ingredients are not downloaded and extracted? When I remove the ingredients the build works - it also finds the right desktop file.
Here is the complete log file: https://build.opensuse.org/package/live_build_log/home:geigi:branches:OBS:AppImage:Templates/Cozy/AppImage/x86_64

Cheers! :)

**Comment by probonopd** [comment]
ping @adrianschroeter

**Comment by nedrichards** [comment]
I shared a sample flatpak manifest in #25
