### ISSUE TITLE
Playback speed for a book not saved

### ISSUE THREAD

**Issue by alexminder** [geigi/cozy#291]
### Bug/Feature description
Playback speed can not be saved when close the app or move to another file in audiobook or change from/to another audiobook. Playback speed alwas drops to 1.0

### Steps to reproduce
- Play any audio book
- change playback speed to other from 1.0 (1.5 in my case)
- close the app
- run the app again
- resume listen the audio book
- Playback speed is 1.0

### System Information
- Operating System: Gentoo
- Installation source: release (ebuild)
- Version of cozy: 0.6.16

**Comment by geigi** [comment]
Thanks for reporting. Could you verify that this issue exists on version 0.6.18? I just tried to reproduce your issue and the playback speed is stored and loaded correctly.

**Comment by alexminder** [comment]
I had update the app to version 0.6.18 and the issue still exists.

**Comment by alexminder** [comment]
I had found that book playback speed saves only when I use mouse left key for speed select. If I use mouse scroll wheel or keyboard left/right keys playback speed changes only runtime and resets after track change or restart the app.

**Comment by geigi** [comment]
Thanks for testing! I see, I didn’t try using the scroll wheel. This is definitely a bug then. :)
