### ISSUE TITLE
Can't import a pseudo-"m4a" that's actually an mp4

### ISSUE THREAD

**Issue by mbkv** [geigi/cozy#293]
### Bug/Feature description
I got an audiobook with the extension m4a that gave the error "Some files could not be imported." Upon further inspection, cozy seems to skip the files entirely with the warning

```
22:41:20 [UpdateDataba] [importer  ] [WARNI]  Skipping file $HOME/Audiobooks/Atlas Shrugged, Part 4.m4a because of mime type video/mp4\012- application/octet-stream.
22:41:20 [UpdateDataba] [importer  ] [WARNI]  Skipping file $HOME/Audiobooks/Atlas Shrugged, Part 3.m4a because of mime type video/mp4\012- application/octet-stream.
22:41:20 [UpdateDataba] [importer  ] [WARNI]  Skipping file $HOME/Audiobooks/Atlas Shrugged, Part 5.m4a because of mime type video/mp4\012- application/octet-stream.
22:41:20 [UpdateDataba] [importer  ] [WARNI]  Skipping file $HOME/Audiobooks/Atlas Shrugged, Part 1.m4a because of mime type video/mp4\012- application/octet-stream.
22:41:20 [UpdateDataba] [importer  ] [WARNI]  Skipping file $HOME/Audiobooks/Atlas Shrugged, Part 2.m4a because of mime type video/mp4\012- application/octet-stream.
```

It seems like on my system, cozy associates this particular m4a file as a `video/mp4`. and there's even conflicting information my system provides

```sh
$ file -i Atlas\ Shrugged,\ Part\ 1.m4a
Atlas Shrugged, Part 1.m4a: video/mp4; charset=binary
$ mimetype -M Atlas\ Shrugged,\ Part\ 1.m4a
Atlas Shrugged, Part 1.m4a: video/mp4
$ mimetype Atlas\ Shrugged,\ Part\ 1.m4a
Atlas Shrugged, Part 1.m4a: audio/mp4
```

It seems like this file is technically just an mp4 with the book cover being a static image as the video. Would it be possible to support video/mp4 in this case? m4a is just the audio type of mp4, so I don't think it should be a big ask. I don't really know if it is

Assuming I'm not the only person to find this. A workaround would be renaming the file as mp4, then running

```sh
$ ffmpeg -i book.mp4 -vn -acodec copy book.m4a
```

### Steps to reproduce

As above,

1. import a "m4a" file that's actually a "mp4" file
2. cozy tells you it can't import it

### System Information
- Operating System: Kubuntu 20.04
- Installation source: flatpak
- Version of cozy: 0.6.18/stable branch

**Comment by geigi** [comment]
Thanks for reporting! :) I’m currently working on rewriting the import process completely. There will also be a new mechanic which decides which files are being imported. I’ll keep this in mind and have a look how to handle this. There is probably a solution for this, but I want to avoid that actual video files are being imported by cozy :)

**Comment by geigi** [comment]
It will take some time until this is finished so I suggest using the workaround you provided in the meantime for everyone else that finds this

**Comment by gambhiro** [comment]
The above trick was helpful. At first Cozy didn't recognize the files saved by youtube-dl in m4a format, but it works after converting them with ffmpeg, and fortunately it doesn't have to re-encode them.

**Comment by geigi** [comment]
This problem is now fixed in the latest version of cozy :)
