### ISSUE TITLE
Refactor seconds_to_human_readable to use ngettext plurals and string format

### ISSUE THREAD

**Issue by Carmina16** [geigi/cozy#297]
Please use `ngettext` instead of explicit logic to select between singular and plural string. Also, please avoid concatenating a number with the string, and use `.format` instead.

https://github.com/geigi/cozy/blob/9611cf8414688100fd18c009a29a319b017411c6/cozy/tools.py#L116

**Comment by geigi** [comment]
Thanks for reporting :) this is very old code which I didn't refactor yet. Most of the code already uses .format and correct gettext plurals. But this function definitely needs refactoring.
