### ISSUE TITLE
Missing mutagen from runtime deps

### ISSUE THREAD

**Issue by danrabbit** [geigi/cozy#30]
Looks like there's a missing runtime dependency:

```
com.github.geigi.cozy 
Traceback (most recent call last):
  File "/usr/bin/com.github.geigi.cozy", line 28, in <module>
    from cozy.ui import CozyUI
  File "/usr/lib/python3/dist-packages/cozy/ui.py", line 4, in <module>
    from cozy.importer import *
  File "/usr/lib/python3/dist-packages/cozy/importer.py", line 2, in <module>
    import mutagen
ModuleNotFoundError: No module named 'mutagen'
```

**Comment by geigi** [comment]
This is weird, it's included in the `debian/control` file: `python3-mutagen`. The last build in review found this library. Any idea what could be wrong? I didn't change any dependencies since the last build.

**Comment by danrabbit** [comment]
Hey @geigi it looks like you added those dependencies to your `build-depends` instead of `depends` (which is for runtime dependencies) :)

**Comment by geigi** [comment]
Ahh I see, thanks a lot! :)
