### ISSUE TITLE
does the import function copy files?

### ISSUE THREAD

**Issue by icf20** [geigi/cozy#309]
the UI dont make it clear if the import option is actually coping files or not

**Comment by geigi** [comment]
Files are only copied when you import them by drag&drop. Otherwise only the directory is scanned.

I'll have a look at the UI text :)

**Comment by jubalh** [comment]
Clicking on `Scan Library` will then show `Importing Audiobooks`
When drag&dropping an audiobook into cozy `Copying new files` is shown followed by `Importing Audiobooks`.

I would suggest to rename `Importing Audiobooks` to `Refreshing Audiobooks` or something.

Once you settled on a naming convention could you ping me? Maybe this would be a nice first issue for me to get started with Cozy.
