### ISSUE TITLE
Dark mode not working

### ISSUE THREAD

**Issue by dspacejs** [geigi/cozy#338]
### Bug/Feature description

Dark mode is no longer working after a recent update. It's turned on in the settings. I tried turning it off/on again, but it did nothing.

It may also be because I recently switched to Regolith Linux, which is using i3 (instead of GNOME). But it still uses the GNOME GUI for apps, so I expect it to be the same.

I've heard this can sometimes cause issues with flatpak dark mode. That might be it (but if it is, I don't know how to fix it, I already tried for a different app a while ago with no luck). 

### Steps to reproduce

1. Replicate my environment
2. Install the app
3. Turn on dark mode. It shouldn't work

### System Information
- Operating System: Ubuntu 20.04.1 LTS, with Regolith installed as the WM
- Installation source: flatpak
- Version of cozy: 0.7.2

**Comment by geigi** [comment]
This is almost always an issue of the GTK theme used. Some GTK themes don't feature a real dark mode but a separate Theme which is dark. In this case Cozy is not able to detect this and switch to a dark mode. Which GTK theme are you using?

**Comment by dspacejs** [comment]
@geigi I'm not using any custom theme that I'm aware of, unless Regolith uses one (but I'm not sure how to check). I'll ask in their support forum and see

**Comment by geigi** [comment]
I'll close this issue as this is a problem I can't resolve with Cozy, this is most likely an issue with the default theme from Regolith.
