### ISSUE TITLE
[Feature Request] Map "back" in media controls to 30 seconds rewind

### ISSUE THREAD

**Issue by dspacejs** [geigi/cozy#346]
This is something all audiobook apps I've used do, and is expected. Whenever I go back I rarely ever want to go to the start of the chapter. Instead, I want to go rewind 30 seconds to rehear something I missed. If I want to go back to a different chapter, I'll open my device and manually switch chapters, instead.

**Comment by geigi** [comment]
Note to myself: This feature first requires refactoring of the player and MPRIS library

**Comment by geigi** [comment]
This feature will ship in the next release :)
