### ISSUE TITLE
MPRIS: swap author/reader setting is not respected

### ISSUE THREAD

**Issue by dspacejs** [geigi/cozy#347]
### Bug description

The media player in i3 isn't able to pick up the author name:

![Screenshot from 2020-10-04 10-05-19](https://user-images.githubusercontent.com/9282837/95003698-1f17a080-0629-11eb-802b-7e1012e406ae.png)

But I've checked the list of authors under the "Reader" view, and the metadata for this author does exist.

### Steps to reproduce

1. Run an audiobok
2. Check the media player
3. The author name should be "Unknown" 

### System Information
- Operating System: Ubuntu 20.04.1 LTS with Regolith and i3xrocks
- Installation source: flatpak
- Version of cozy: 0.7.2

**Comment by dspacejs** [comment]
Looks like this problem is in the app itself, too: 

![Screenshot from 2020-10-04 10-35-53](https://user-images.githubusercontent.com/9282837/95004030-92bbac80-062d-11eb-9eb6-104c54531b18.png)

![Screenshot from 2020-10-04 10-36-51](https://user-images.githubusercontent.com/9282837/95004032-95b69d00-062d-11eb-856e-5ff6823d931a.png)

Yet authors still show in the left sidebar in the "Reader" view:

![Screenshot from 2020-10-04 10-37-04](https://user-images.githubusercontent.com/9282837/95004038-a109c880-062d-11eb-9dc0-daf4c01680da.png)

**Comment by geigi** [comment]
It looks like your audiobooks have tagged the author in the artist field. Most audiobooks are tagged like this:

Artist: Reader
Composer: Author

You can switch this mapping in the settings :)

**Comment by dspacejs** [comment]
@geigi now this isn't a problem in the app itself. But the media player still says "Unknown" instead of the author.

**Comment by geigi** [comment]
So your library and the titlebar shows the correct author but the desktop integration does not?

**Comment by geigi** [comment]
Maybe the desktop integration does not respect the setting to swap author and reader properly

**Comment by dspacejs** [comment]
@geigi 

> So your library and the titlebar show the correct author but the desktop integration does not?

Yep. I don't know how the media player thing works on Linux, but I guess you have to set the "Artist" field as the "Author" then it should work.

**Comment by geigi** [comment]
This is definitely a bug in Cozy then. Cozy provides all the information that will be displayed in the desktop media player integration (MPRIS).

**Comment by geigi** [comment]
The code for MPRIS and the media player is very old. To properly fix this issue I'll first need to refactor the MPRIS and player component. I'm in the progress of refactoring the player but it'll take some time.

**Comment by thomascrisan** [comment]
Artist is usually the performing artist while composer is the person who wrote the music.  My confusion today was that I was using Kid3 (a KDE tag editor) and it has a field for "Author".  I started adding the authors' names to my files using an Author tag, re-scanned my books in Cozy and was surprised when the Author tag was not recognized.

I see that "Author" is not a native frame in the [ID3 specifications](https://id3.org/id3v2.4.0-frames).

Adding the authors' names to the Composer tag has fixed the issue in Cozy for me.
