### ISSUE TITLE
Import of m4b hangs

### ISSUE THREAD

**Issue by beattie** [geigi/cozy#354]
### Bug/Feature description
Import of m4b converted from aax files hangs on some (2 files out of 3 tried) hang.

### Steps to reproduce
Start Cozy from clean install, Import audiobook either by scan or drag&drop.

### System Information
- Operating System: Ubuntu 20.04.1
- Installation source: flatpak app/com.github.geigi.cozy/x86_64/stable
- Version of cozy: 0.7.2

**Comment by geigi** [comment]
Hey, thanks for reporting!

Could you try the import again and post Cozy's log here? You can find the log at:
```
~/.var/app/com.github.geigi.cozy/data/cozy/cozy.log
```
This would help a lot in identifying the issue :)

**Comment by beattie** [comment]
Log after close:

10:34:18 [MainThread  ] [applicatio] [INFO ]  ('org.gnome.platform', 'master', 'Flatpak runtime')
10:34:18 [MainThread  ] [applicatio] [INFO ]  Starting up cozy 0.7.2
10:34:18 [MainThread  ] [db        ] [INFO ]  SQLite version: 3.33.0, APSW version: 3.33.0-r1
10:34:18 [MainThread  ] [ui        ] [INFO ]  Initialize main window
10:34:19 [Thread-9    ] [offline_ca] [INFO ]  Startet processing queue
10:34:20 [MainThread  ] [player    ] [ERROR]  Argument 0 does not allow None as a value
10:34:33 [DragDropImpo] [files     ] [INFO ]  Start of copying files
10:34:33 [DragDropImpo] [files     ] [INFO ]  Copy file /home/beattie/Audible/GodsofRiskAnExpanseNovella_ep6.m4b to /home/beattie/Audiobooks/GodsofRiskAnExpanseNovella_ep6.m4b
10:34:34 [DragDropImpo] [files     ] [INFO ]  Copying of files finished
10:34:34 [DragDropImpo] [root      ] [INFO ]  Starting import
10:48:28 [MainThread  ] [ui        ] [INFO ]  Closing.
10:48:28 [MainThread  ] [titlebar  ] [INFO ]  Closing.
10:48:28 [MainThread  ] [player    ] [INFO ]  Closing.
10:48:28 [MainThread  ] [db        ] [INFO ]  Closing.
10:48:28 [MainThread  ] [ui        ] [INFO ]  Closing app.
10:48:28 [MainThread  ] [ui        ] [INFO ]  App closed.

**Comment by beattie** [comment]
Just to seem if Audible aax was part of the problem I downloaded parts 1 and 2 of Origin of Species from LibreVox, Part1 imported but part2 hung.

https://archive.org/download/origin_species_librivox/OriginOfSpeciesPart1-64kb_librivox.m4b
https://archive.org/download/origin_species_librivox/OriginOfSpeciesPart2-64kb_librivox.m4b

**Comment by geigi** [comment]
Thanks for the log and providing an example :) I'll try to reproduce the issue probably on the weekend.

**Comment by geigi** [comment]
I just released Cozy 0.7.5 with a couple of bug fixes that could have something to do with your issue. 
I'm not sure whether your issue is fixed because I couldn't reproduce it. Could you give it a try?

**Comment by beattie** [comment]
0.7.5 import of several books works, now I just need to figure out how to port to mobian on my pinephone/pinetab, Thanks

**Comment by geigi** [comment]
Nice to hear :) sadly Cozy doesn't work on the pinephone yet, because the UI is not capable to run on a small screen. This is something I'll address sometime in the future. It should work on the Pinetab though :)
