### ISSUE TITLE
Chapter support question/request

### ISSUE THREAD

**Issue by beattie** [geigi/cozy#362]
### Bug/Feature description
Not sure is this is the right place, but I'm wondering what chapter support is present or planned. If this is inappropriate I apologize, if there is a better forum I'd appreciate a pointer.

Features I'd like to see:

- list chapters
- skip to next chapter
- select chapter to play
- port to ARM Debian
(I've tried to build cozy on my Ubuntu 20.04.1 and If I could get that to work I could give porting a shot, but I don't expect handholding)

**Comment by geigi** [comment]
Chapters are currently only supported when they are separate files. M4b chapter support has not landed yet but is in progress :)

Arm is fully supported and you should be able to install Cozy from Flathub on an arm device :) If this is not the case let me know!

Closing due to being a duplicate 

#62

**Comment by geigi** [comment]
Btw there is currently no forum or anything other than GitHub where I'm active so this was the right place for your questions :)

**Comment by geigi** [comment]
If you want chapter support now, you can use a tool like this to split your m4b files into multiple audio files by chapter. All of the features you mentioned will then work :)

Here is the tool: https://github.com/sandreas/m4b-tool

**Comment by apandada1** [comment]
> port to ARM Debian

Does the .deb package work for you?
arm64: https://launchpad.net/~cozy-team/+archive/ubuntu/cozy/+files/cozy_1.1.0-2~ubuntu21.04.1_arm64.deb
armhf: https://launchpad.net/~cozy-team/+archive/ubuntu/cozy/+files/cozy_1.1.0-2~ubuntu21.04.1_armhf.deb
