### ISSUE TITLE
[Feature Request] Build Library Without Copying Files

### ISSUE THREAD

**Issue by rockhazard** [geigi/cozy#366]
I have a very large library. I can't afford to move many gigs of audio files to one location, and it's a waste to have duplicate files to begin with. I'd like Cozy to be capable of building its library without copying my books. Many programs can do this sort of thing (by building playlists, for instance). I don't know if this was a design decision or some kind of techincal/practical limitation, but it means I can't really use Cozy. This one feature would make all the difference.

**Comment by geigi** [comment]
Hey, this is already possible! Have a look at the settings, you can add multiple storage locations. All these locations will be scanned. You can also mark them as external which enables a feature that allows you to download the files to your machine (if you're using a laptop for on the go).
If you add files using drag and drop they will be copied to the location which is marked as default.
But you can still add files manually to your locations and issue a scan from the menu manually.

**Comment by geigi** [comment]
Did this solve your issue? I'm closing it for now but feel free to reopen if it didn't :)

**Comment by rockhazard** [comment]
Yes it did thanks!
