### ISSUE TITLE
[Bug] Art for podcast is trimmed incorrectly

### ISSUE THREAD

**Issue by dspacejs** [geigi/cozy#372]
### Bug/Feature description

The complete art for a podcast isn't showing. It's cropped most of it:

![Screenshot from 2020-11-30 12-04-45](https://user-images.githubusercontent.com/9282837/100560070-8ccc0a00-3304-11eb-9f5b-dcde80ee1b80.png)

### Steps to reproduce

1. Download one or more of the podcast episodes from https://www.whatonearthishappening.com/podcast
2. Move them into a folder with the structure: `Podcasts/WOEIH/`
3. Import the `Podcasts` folder into Cozy
4. View the podcast in the app, the album art should be cropped

### System Information
- Operating System: Ubuntu 20.04.1 LTS
- Installation source: flatpak
- Version of cozy: 0.7.6

**Comment by geigi** [comment]
Hey, I just downloaded an episode and tried to reproduce your issue but it did work perfectly fine for me. This does look like the image that was read by Cozy is somehow corrupted as it just stops in the middle from being rendered. 
Is the image only broken in the library view or also in the book detail view?

**Comment by dspacejs** [comment]
@geigi it's everywhere. I can open the same files in another player like VLC and it will render the image correctly, so the image must not be corrupted. Not sure what's going on

**Comment by geigi** [comment]
Have you experienced this issue again?

**Comment by dspacejs** [comment]
> Have you experienced this issue again?

Not that I remember, feel free to close. It can be reopened later if necessary.
