### ISSUE TITLE
[Bug] Sleep Timer not working

### ISSUE THREAD

**Issue by phpwutz** [geigi/cozy#375]
### Bug/Feature description

Timer is not working and UI makes the slider jump back.

### Steps to reproduce
Start Cozy
Play something
Try to configure a Sleep timer
Result:
Slider jumps back to 0 and it shows "min" (missing number)

When starting from the Command Line, I get this error when dragging the timer slider:
```
handle exception
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/cozy/control/sleep_timer.py", line 135, in __on_timer_changed
    if not self.sleep_timer or not self.sleep_timer.isAlive():
AttributeError: 'IntervalTimer' object has no attribute 'isAlive'
```
interestingly, when i stop the playback, the slider starts behaving normal again until i resume playback

### System Information
- Operating System: Arch Linux
- Installation source: AUR
- Version of cozy: 0.7.7

Love the App, thanks and keep safe!

**Comment by phpwutz** [comment]
did some research, the threading library decided to do a  BC breaking change...

isAlive() is now named is_alive(). Because sure, why not...

https://bugzilla.redhat.com/show_bug.cgi?id=1787746

i'll prep a PR if you would be so kind to merge it :)

**Comment by geigi** [comment]
Good catch and thanks for the PR! There will be a new release probably this weekend which will include the fix :)
