### ISSUE TITLE
Design a GNOME HIG-compliant app icon

### ISSUE THREAD

**Issue by jimmac** [geigi/cozy#379]
Let's kick the effort off with some preliminary sketches of how the current metaphor could live in the constraints of the HIG.

![Cozy](https://user-images.githubusercontent.com/14821/101484344-c41c6580-3959-11eb-9776-1dfa5588e5d9.png)

**Comment by geigi** [comment]
This looks awesome! I quite like the idea of the headphones plugged into the book :)

**Comment by jimmac** [comment]
For clarity at 1:1 I've chosen to use a speaker for the symbolic. Alternatively we could just go with a book or headphones. It's pretty much impossible to cram the two together and keep them legible.

![image](https://user-images.githubusercontent.com/14821/101506841-24210500-3976-11eb-98f0-12282bf538a4.png)

**Comment by geigi** [comment]
I'm digging the style of the icon :)

**Comment by jimmac** [comment]
Perhaps a bit of that original orange could be preserved not to be so grey:

![image](https://user-images.githubusercontent.com/14821/101512553-6b5dc480-397b-11eb-9569-43123d542d85.png)

**Comment by geigi** [comment]
The orange fits nicely!
