### ISSUE TITLE
Empty state: weird layout and visuals

### ISSUE THREAD

**Issue by bertob** [geigi/cozy#381]
### Bug/Feature description

On first run, there's an empty state that uses some pretty weird-looking font styles, and has a listbox-style layout without a listbox background. The whole empty state also grows very wide, and the descirptions include line breaks:

![image](https://user-images.githubusercontent.com/1908896/101530969-e7173b80-3992-11eb-8a56-c38e708f14e0.png)

I'd recommend
- Making this a real listbox with a white background
- Putting the view in an HdyClamp
- Using standard listbox text styles
- Using symbolics rather than hicolor icons on the left
- No line breaks in descriptions

### Steps to reproduce

1. Install app
2. launch the app

### System Information
- Operating System: Fedora 33 
- Installation source: Flathub
- Version of cozy: 0.7.8

**Comment by geigi** [comment]
Thanks, this feedback helps a lot :) The empty state is already a few years old (infact most of the UI is) and definitely could use an overhaul. Two small questions:
- Are the standard listbox text styles you mentioned css classes I can use?
- Do the actions in the empty state make sense to you or is there something else you would change or an information you're missing?

**Comment by bertob** [comment]
I think there are some style classes for listboxes in libhandy (e.g. `.content` for the rows). It's probably easier to just use libhandy's list row widgets though: https://gnome.pages.gitlab.gnome.org/libhandy/doc/1.0/HdyActionRow.html

As for the overall flow and layout, I haven't properly the app since I don't have any audiobooks, but just looking at that first screen I wonder if it makes sense to expose those three options so prominently. Perhaps it'd be better to just pick sane defaults and have them live in the preferences dialog for people to change if their setup requires it.

**Comment by geigi** [comment]
I'm now working on a redesign of Cozy's UI :) Here is my first try with your suggestions (HdyClamp, ListBox and HdyActionBar). What do you think?
![Screenshot from 2021-05-30 22-57-38](https://user-images.githubusercontent.com/9107883/120119899-795a0880-c19a-11eb-8d70-3fd3938c4473.png)

(Please ignore the headerbar and bottom bar for now, they are still wip)

**Comment by geigi** [comment]
Maybe with a frame and a separator:
![Screenshot from 2021-05-30 23-03-28](https://user-images.githubusercontent.com/9107883/120120053-511ed980-c19b-11eb-895c-5e58aaa8e12d.png)
