### ISSUE TITLE
Sleep timer runs with double speed

### ISSUE THREAD

**Issue by phpwutz** [geigi/cozy#382]
### Bug/Feature description

Sleep timer goes down with about 2x the expected speed.

### Steps to reproduce
set a timer to 10min
wait 5min

expected behavior: timer should be at 5min
actual behavior: timer triggers the sleep action / fade out

### System Information
- Operating System: arch linux
- Installation source: AUR
- Version of cozy: 0.7.8

**Comment by geigi** [comment]
Thanks for reporting :) I just noticed this myself a few days ago.

**Comment by phpwutz** [comment]
After taking a look at the code I will make an educated guess:
You also have Fadeout enabled and at 60sec? If so, I have an idea for a fix :)

**Comment by geigi** [comment]
I'm not sure if I had fadeout enabled... but might be :)

**Comment by rdbende** [comment]
Was fixed probably in cfa1c9e
