### ISSUE TITLE
Support .mp4 files

### ISSUE THREAD

**Issue by madfin** [geigi/cozy#387]
### Bug/Feature description
If i try to add MP4/AAC audiobook, nothing happens. File plays fine with mplayer and VLC.

**Media info:**
Format                                   : MPEG-4
Format profile                           : Base Media / Version 2
Codec ID                                 : mp42 (isom/mp42)
File size                                : 55.4 MiB
Duration                                 : 2 h 44 min
Overall bit rate mode                    : Variable
Overall bit rate                         : 47.0 kb/s
Encoded date                             : UTC 2016-06-27 12:04:01
Tagged date                              : UTC 2016-06-27 12:04:01

Audio
ID                                       : 1
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format profile                           : LC
Codec ID                                 : mp4a-40-2
Duration                                 : 2 h 44 min
Source duration                          : 2 h 44 min
Bit rate mode                            : Variable
Bit rate                                 : 45.7 kb/s
Maximum bit rate                         : 142 kb/s
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 44.1 kHz
Frame rate                               : 43.066 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 53.8 MiB (97%)
Source stream size                       : 53.8 MiB (97%)
Language                                 : English
Encoded date                             : UTC 2016-06-27 12:04:01
Tagged date                              : UTC 2016-06-27 12:04:01

### System Information
- Operating System: Linux Mint 19.3
- Installation source: Ubuntu software center 
- Version of cozy: 0.7.8

These libs are installed:
gstreamer1.0-plugins-good
gstreamer1.0-plugins-bad
gstreamer1.0-plugins-ugly
gstreamer1.0-libav for mp4 support

**Comment by geigi** [comment]
Sorry for the late answer... Could you try to import the file again and post the log file here? You can find the log file in one of those two paths:
```
~/.var/app/cozy/cozy.log
~/.local/share/cozy/cozy.log
```
Thanks :)

**Comment by madfin** [comment]
Here is a log from drag and drop. Copy passes, but nothing can be played or is listed.

[cozy.log](https://github.com/geigi/cozy/files/5897788/cozy.log)

**Comment by geigi** [comment]
Thanks for the log! Looks like Cozy isn't logging enough in the case you're experiencing... 

I'm a bit clueless at the moment. I'll try to add more logging in the next version of Cozy. But I'll have to ask you for a log file again once I've improved logging.

**Comment by madfin** [comment]
I used mkvmerge to split small portion from the book. Here is a link if you wish to try it yourself. 

https://drive.google.com/file/d/1jdra_kOIqjBR_kdEE2ydaycVT3Pfr8Pk/view?usp=sharing

**Comment by geigi** [comment]
Thanks for the upload! I just realized what the issue is, try renaming the file to **.m4a**. **.mp4** is currently ignored because a lot of times this is a video file. I'll try to add a other detection for video files in the next release.

**Comment by madfin** [comment]
Ok. I tried that, but didn't work for me. If it worked for you with that file, then there is something wrong with my installation.

**Comment by geigi** [comment]
Just tried it and it worked fine with the file you provided (also renamed to **m4a**) . Do you have the "hide unavailable books" option enabled in the menu?
