### ISSUE TITLE
Can't jump to the start of a chapter?

### ISSUE THREAD

**Issue by jianpan** [geigi/cozy#397]
I'm using Cozy 0.7.8 from flathub. I have an audio book with each chapter in a mp3 file. Sometimes I want to go back to a previous chapter to relisten from the beginning. But Cozy seems to always resume from previous position? It's great to continue when I open an audiobook. But if I select a chapter, it seems more useful to play from the beginning?

**Comment by geigi** [comment]
Hey thanks for reporting! I noticed this too, this is a bug.

**Comment by geigi** [comment]
This issue will be fixed with the next release of Cozy. Selecting a new chapter will always play from the beginning :)
