### ISSUE TITLE
The App Crashes when Removing Item from Library : Bug

### ISSUE THREAD

**Issue by buffythepig** [geigi/cozy#401]
Bug Description

When I right click to remove an item from the library, the entire app freezes forcing me to kill the application from terminal.

**Steps to reproduce**

open cozy library ... right click for drop down menu .... choose **'remove from library'** ...instantly crashes and freezes and can't use the GUI for any purpose even to close windows (also leaves a small rectangular patch on the screen where removal was attempted ..... see attached screenshot)

**System Information**

Mx Linux and Pop!_Os
Flatpak and MX package installer : same behavior in both
Version : 0.7.8
DE ... Same behavior on Gnome and KDE Plasma and XFCE

![Screenshot from 2021-01-15 15-00-23](https://user-images.githubusercontent.com/77426841/104697803-e10b3c00-5742-11eb-8bd1-8367d81629bb.png)

**Comment by geigi** [comment]
Thanks for reporting, I'll have a look!
