### ISSUE TITLE
Include MX Linux Packaging to Install section of README

### ISSUE THREAD

**Issue by SwampRabbit** [geigi/cozy#402]
### Bug/Feature description
Include MX Linux Packaging to Install section of README

### Steps to reproduce
N/A

### System Information
- Operating System:  MX Linux 19
- Installation source:  MX Package Installer - MX Test Repo tab
- Version of cozy: 0.7.8

Hello, I'm a package maintainer for MX Linux, we had your application requested by one of our users.
Cozy is in our repos now and I'd like to kindly request for MX Linux to be added to the Install section of README.

We like our users to use MX Package Installer rather than direct link to the .deb.  This is important in relation to Cozy as some of the dependencies are also in the MX Test Repo, so when users use our MX Package Installer - MX Test Repo tab, Cozy installs with everything it needs.

Thank you in advance

**Comment by geigi** [comment]
Hey, is there a page I can link to where users can find Cozy on MX Linux? Also, is the package simply called cozy on MX Linux?

**Comment by SwampRabbit** [comment]
@geigi very good questions, it was packaged as "Cozy" but shows up on Repology under cozy-audiobooks.

I have just created a Announcement and Status Tracking thread on our Forum 
https://forum.mxlinux.org/viewtopic.php?p=621071#p621071

I see you just released another version, I'll package it first chance I get.

**Comment by geigi** [comment]
Thanks for the additional information :) 
'll added MY Linux to the Readme!
