### ISSUE TITLE
The empty state page is a bit far from GNOME's HIG

### ISSUE THREAD

**Issue by Kekun** [geigi/cozy#403]
![Capture d’écran de 2021-01-27 19-01-20](https://user-images.githubusercontent.com/2536339/106034265-ff721f80-60d2-11eb-8d18-79ff545bc26c.png)

The empty state page currently looks like this, it's serviceable but it's huge and quite busy, making it hard to read and fairly different from the HIg. It also is very far from usable on small devices like phones as this is the scallest reachable size.

![Capture d’écran de 2021-01-27 19-02-29](https://user-images.githubusercontent.com/2536339/106034618-6a235b00-60d3-11eb-9839-14b57b3e23d1.png)

I would suggest to use `HdyStatusPage` and a `GtkListBox` with the `.content` style class and some `HdyActionRow` to give it this standardized and adaptive look very easily:

![Capture d’écran de 2021-01-27 19-17-45](https://user-images.githubusercontent.com/2536339/106035380-59bfb000-60d4-11eb-8646-f3cf7c612ae2.png)

### System Information
- Operating System: Fedora Silverblue
- Installation source: Flathub
- Version of cozy: 0.7.8

**Comment by Kekun** [comment]
Ah my bad, this is a duplicate of https://github.com/geigi/cozy/issues/381.

**Comment by geigi** [comment]
Thanks for reporting and the examples! I'll close this one as a duplicate.
