### ISSUE TITLE
Use the latest preferences window HIG patterns

### ISSUE THREAD

**Issue by Kekun** [geigi/cozy#404]
I'd suggest using `HdyPreferencesWindow`: it's adaptive, it looks a bit better, it implements the latest HIG patterns, and you get preferences search for free.

### System Information
- Operating System: Fedora Silverblue
- Installation source: Flathub
- Version of cozy: 0.7.8

**Comment by geigi** [comment]
Thanks for reporting! This is something I'll change in the future. A bigger UI overhaul is something I have in mind but there are still some features I want to implement or fix first.

**Comment by geigi** [comment]
Todo:

- [ ] Adopt HdyPreferencesWindow
- [ ] Rearrange and remove unneccesary settings
- [ ] Refactor code
