### ISSUE TITLE
Make the windows transient

### ISSUE THREAD

**Issue by Kekun** [geigi/cozy#405]
The preferences window and the about dialog should be transient to the main window. Maybe there are other cases of that, but I barely started using the app so I don't know.

### System Information
- Operating System: Fedora Silverblue
- Installation source: Flathub
- Version of cozy: 0.7.8

**Comment by geigi** [comment]
Thanks for reporting :)

**Comment by geigi** [comment]
Both windows are already set transient for the main window. You can also verify this as both windows will never hide behind the main window. Did you meant setting them as a _modal_ so interaction with the main window is blocked?

**Comment by Kekun** [comment]
Yes that's what I meant. 🙂

**Comment by geigi** [comment]
Thanks for the quick feedback :)
