### ISSUE TITLE
Redesign the preferences layout

### ISSUE THREAD

**Issue by Kekun** [geigi/cozy#406]
There are 5 pages which is a lot, and out of these 5 one only has 2 preferences and another only has 1!

The preferences layout can probably be rearranged to work better, which will require the contribution of a designer. The best is to ask in #gnome-design.

### System Information
- Operating System: Fedora Silverblue
- Installation source: Flathub
- Version of cozy: 0.7.8

**Comment by artm** [comment]
Don't want to file another UI issue, but if I did it would say *make @Kekun responsible for UI design decisions*.

**Comment by geigi** [comment]
Thanks for reporting :) I'm closing this issue as it is closely related to #404 and is best implemented in one step.

**Comment by geigi** [comment]
When the time has come for a redesign I'll definitely ask @Kekun or in #gnome-design!
