### ISSUE TITLE
Weird frame

### ISSUE THREAD

**Issue by Kekun** [geigi/cozy#407]
There is this weird frame, I didn't search what causes it.

![box](https://user-images.githubusercontent.com/2536339/106041557-3d277600-60dc-11eb-9c72-62783692c7ab.png)

### System Information
- Operating System: Fedora Silverblue
- Installation source: Flathub
- Version of cozy: 0.7.8

**Comment by geigi** [comment]
This issue is already fixed in a feature branch and will be included in the next release. Thanks for reporting anyway!
