### ISSUE TITLE
Books are found but "unavailable"

### ISSUE THREAD

**Issue by artm** [geigi/cozy#408]
### Bug/Feature description

I let Cozy scan for books, it found three, two of them with wrong titles, all of them marked with Unknown author / reader, but all three are unusable and disappear if I select "hide unavailable books"

### Steps to reproduce

1. have Ubuntu 20.10
2. install flatpak
3. install cozy from flatpak
4. have a folder with audiobooks in the format I use
5. make this folder cozy's main folder
6. let cozy scan the folder

Example of a book that got recognized (but unplayable):

![image](https://user-images.githubusercontent.com/64227/106355920-a20ce700-62fb-11eb-8011-065a105290d7.png)

Example of a book that got URL encoded title:

![image](https://user-images.githubusercontent.com/64227/106355934-b650e400-62fb-11eb-8b2d-6f684ad5d241.png)

What they look like in Cozy:

![image](https://user-images.githubusercontent.com/64227/106355951-d7193980-62fb-11eb-899a-a0e66538a314.png)

### System Information
- Operating System: Ubuntu 20.10
- Installation source: Flatpak
- Version of cozy: 0.7.8

**Comment by geigi** [comment]
Cozy only works with properly tagged media, make sure this is done with a separate tagging tool of your choice :) Be aware that most audiobooks are tagged like this (although you can change this in Cozy's settings):
artist: reader
composer: author

If books can't be played back and vanish when activating "hide unavailable books" Cozy can't find the books at the path where it imported them from.

**Comment by artm** [comment]
Ok, I'll try tagging and rescanning. And maybe rename the paths so they only contain ASCII characters. Thanks.

**Comment by geigi** [comment]
Sure :) still odd that this happened. I'll have a look if there is an encoding issue somewhere.

**Comment by artm** [comment]
The retagging helped to have correct titles, authors and narrators (what Cozy calls "reader"), but the books are still unavailable. This time I also see some vagues error messages:

![image](https://user-images.githubusercontent.com/64227/106359098-b0b1c900-6310-11eb-8d07-becef8d3dbcb.png)

This is right after I scanned for the books, does Cozy use different file system APIs for scanning and loading files for playback? The scanner finds them alright, but the rest of Cozy considers them missing. This is very confusing :-)

**Comment by artm** [comment]
OK, so I toggled the folder to be "internal", now the books look like they can be played, and if I try to play them the error message is more useful: it still looks for the files in the old location (I renamed the folders at some point to see if that helps). 

![image](https://user-images.githubusercontent.com/64227/106359264-dc817e80-6311-11eb-9361-9dd263c0da05.png)

Rescanning again fixed it finally.

**Comment by geigi** [comment]
Ok this is indeed quite confusing. The whole internal/external situation is something I'll fix in the future. Glad tough that it is working for you now!
