### ISSUE TITLE
Cozy creates two folders in the home directory when localized

### ISSUE THREAD

**Issue by ericonr** [geigi/cozy#416]
### Bug/Feature description

I am using cozy with `LANG=pt_BR.UTF-8` in my environment. If I launch cozy for the first time, it will create two directories, `Audiobooks` and `Audiolivros`. Given that the UI defaults to `Audiolivros`, it would probably be best to create only the translated one, and avoid cluttering the home directory even more.

### Steps to reproduce

- Remove `~/Audiobooks` and `~/Audiolivros` directories. 
- Export `LANG=pt_BR.UTF-8`, launch cozy for the first time (delete files from `~/.cache/cozy` and `~/.local/share/cozy`).
- See that there are now two new directories in `~/` instead of just one.

### System Information

- Operating System: Linux
- Installation source: System package
- Version of cozy: 0.8.1

**Comment by geigi** [comment]
Thanks for reporting!

**Comment by geigi** [comment]
I fixed the issue, it will be included in the next release :)

**Comment by ericonr** [comment]
Great, thank you lots :D
