### ISSUE TITLE
[Bug] Media controls are broken

### ISSUE THREAD

**Issue by dspacejs** [geigi/cozy#425]
### Bug description

Clicking the rewind button doesn't reverse the track's progress:

![Peek 2021-02-05 12-43](https://user-images.githubusercontent.com/9282837/106980638-76cd4080-67b0-11eb-8a64-fc75360542ad.gif)

The same goes for external media controls (such as the Ubuntu media controls, or devices like headphones).

### Steps to reproduce

1. Load a track
2. Try using the controls

This may be hard to debug, since I've noticed it happens sometimes, but then randomly starts working again. Therefore I'm not sure what the exact conditions are to reproduce it.

### System Information
- Operating System: Ubuntu 20.04.1 LTS
- Installation source: flatpak
- Version of cozy: 0.8.1

**Comment by geigi** [comment]
Thanks, this is indeed very hard to debug but happens sometimes. I haven't experienced this bug myself but there have been some other people who experienced this bug. The good thing is I'm currently rewriting and refactoring the media playback. The new code should be a lot more reliable :)

**Comment by geigi** [comment]
The player refactoring is now merged and will be included in the next release. I'm pretty confident that an issue like this should not occur anymore. If it does feel free to reopen this issue :)

**Comment by dspacejs** [comment]
@geigi great when is the next release?

**Comment by geigi** [comment]
I'm a bit busy at the moment so it's difficult to tell you a date. I'll still need to refactor the offline feature to support the new player. Maybe in about 2-3 weeks.

**Comment by dspacejs** [comment]
@geigi cool, thanks for your work, appreciate it.
