### ISSUE TITLE
[Bug] Audiobook playback speed not cached after closing app

### ISSUE THREAD

**Issue by dspacejs** [geigi/cozy#426]
### Bug description

The speed you used for an audiobook should be remembered once you close the app. Otherwise you need to manually change it again to the optimal speed you configured prior, which is a hassle.

I'm labelling this as a bug instead of a feature request because this used to work, but suddenly broke in one of the latest updates (not sure which).

### Steps to reproduce

1. Open an audiobook
2. Change the playback speed
3. Close the app
4. Play the same audiobook. The speed should have reset to the default

### System Information
- Operating System: Ubuntu 20.04.1 LTS
- Installation source: flatpak
- Version of cozy: 0.8.1

**Comment by geigi** [comment]
Thanks for reporting, this will be fixed in the next release.
