### ISSUE TITLE
Issue with metadata editing and display

### ISSUE THREAD

**Issue by adsywad** [geigi/cozy#428]
### Feature description - User perspective

**Problems**
Narrators/ readers show up in the left-hand panel along with all authors. There's no discrimination between these and so as the library increases it becomes cumbersome for the user.  Additionally,  beneath the title all that's displayed is "Unknown", and unable to edit or add any tags or build collections.

**Request** 
More controls in the application preferences and/ or UI so that a user can edit how Cozy allocates the metadata held for each audiobook; and, to edit or remove meta data as appropriate. If I could edit the metadata in bulk for my audiobooks I could fix this across all my books, I could also add in more data like tags that I could use for searching and organising my collections.
Thanks

### System Information
- Operating System: Linux Mint 20 Mate
- Installation source: Flatpak
- Version of cozy: 0.8.1

**Comment by geigi** [comment]
Hey thanks for reporting :)

I'm not sure wether I understand your issue.
There are only two options as far as I can see:
Storing the author in the artist Tag and the reader in the composer Tag or the other way around. This can be switched in settings.

Metadata manipulation is a feature that I don't want to include in Cozy. There are already lots of tools that do this very well and therefore I want to keep the focus in playback :)

**Comment by adsywad** [comment]
Hi Thanks for quick reply.
> Storing the author in the artist Tag and the reader in the composer Tag or the other way around. This can be switched in settings.

Yes I did this and there is still "Unknown" displayed. I should just clarify that the title is shown and beneath that, where I would expect the Author, it shows "unknown". Authors are displayed in the side panel but so too are the readers/narrators. And even forcing a refresh doesn't seem to help.

> Metadata manipulation is a feature that I don't want to include in Cozy. There are already lots of tools that do this very well and therefore I want to keep the focus in playback :)

Fair enough, be great to know of any recommendations if there are any. 

What about tagging books or some way to organise and create collections?

Thanks again.

**Comment by geigi** [comment]
This sounds like your media files are not consistently tagged. "Unknown" will be used when Cozy doesn't find an author (or composer) tag. When you change metadata and issue a rescan Cozy will detect all changed files and reimport those.

I used **easytag** for my files. Can you please check that all your audiobooks are correctly tagged?

Let's discuss the organization feature in a different issue from now on: #434

**Comment by adsywad** [comment]
> This sounds like your media files are not consistently tagged. "Unknown" will be used when Cozy doesn't find an author (or composer) tag. When you change metadata and issue a rescan Cozy will detect all changed files and reimport those.
> 
> I used **easytag** for my files. Can you please check that all your audiobooks are correctly tagged?
> 
> Let's discuss the organization feature in a different issue from now on: #434

Thanks that's helpful, The files I have use the tags, Artist; Album Artist; Composer, which could be relevant. Currently I have Artist and Album Artist populated. 
Which tags map to Author and which to Reader?
