### ISSUE TITLE
[Bug] Playing a previous chapter that's finished skips to next chapter

### ISSUE THREAD

**Issue by dspacejs** [geigi/cozy#433]
### Bug description

If you play a chapter of an audiobook that's finished, it'll skip to the following chapter instead of the beginning of the chapter you selected. And because it automatically plays it, it's very difficult to stop it before it skips.

### Steps to reproduce

1. Play an audiobook with multiple chapters
2. Finish a chapter
3. Go to the next chapter
4. Play the chapter you finished
5. It should automatically skip to the chapter after the finished one, instead of letting you replay the finished chapter

### System Information
- Operating System: Ubuntu 20.04.1 LTS
- Installation source: flatpak
- Version of cozy: 0.8.1

**Comment by geigi** [comment]
Thanks again for reporting :) I noticed this too and I've already fixed this in the player rewrite which is almost finished. I'll close this issue when I merge the rewrite.

**Comment by geigi** [comment]
This issue will be resolved in the next release of Cozy :)
