### ISSUE TITLE
[Feature] Reset progress for all tracks in audiobook

### ISSUE THREAD

**Issue by dspacejs** [geigi/cozy#441]
There's a few audiobooks I frequently replay on a regular basis. I like listening to it from start-to-finish. But if I didn't finish some of the tracks (chapters), when the player hits this track it'll start from where I left off last time instead of the beginning.

It'd be good if there's a button somewhere to reset the progress for the audiobook. Something that's not in the main view so it's not accidentally clicked. Like a menu item in a dropdown when you right-click the audiobook, that says "Reset all progress". It could also open a prompt to confirm you want to take this action.

**Comment by geigi** [comment]
Hey :) This is related to #443 and #397
The UX in the next release will be:
Playing the current chapter will resume from the previous position. Selecting a different chapter in the same book will always start from the beginning of the chapter. 
Resetting the progress will be then simply a matter of clicking on the first chapter and it'll play from the beginning. The following chapters will then also be played from the beginning again :)
I think the action of resetting the progress of all chapters is not needed then.

**Comment by dspacejs** [comment]
@geigi oh yeah, oops, I accidentally posted the same issue lol. Just different wording so I didn't realise.
