### ISSUE TITLE
Adaptive UI

### ISSUE THREAD

**Issue by bertob** [geigi/cozy#443]
Since audiobooks are a great on the go, it would be cool to be able to use the app on narrow screens (e.g. phones). It would also be a good opportunity to port to latest design patterns and widgets. I haven't spent a ton of time thinking about it, but some structural ideas:

- Playback bar at the bottom similar to Podcasts
- Playback screen coming up from the bottom as a flap, rather than being a standard stack page with a back button
- Navigation at the top (view switcher on top-level views, title and back button on sub-views)

**Comment by geigi** [comment]
Hey, thanks for your Input :) there is already an issue open for this request: #393
I'm closing this one as a duplicate, most of your suggestions are also already discussed there :)

**Comment by bertob** [comment]
Oops, I searched for existing issues, but I guess not using the right terms :)
