### ISSUE TITLE
Edit M4B Files

### ISSUE THREAD

**Issue by trymeouteh** [geigi/cozy#454]
Please add an editor to be able to edit M4B files. There are no known M4B editors out there on Linux currently. Please allow us to edit the following things on a M4B file.

- Title
- Author
- Genre
- Chapters
- Cover Art

**Comment by geigi** [comment]
Hi :) thanks for your suggestion. Cozy will only focus on playback, editing metadata is out of focus for the project. Sorry if that disappoints you.

**Comment by trymeouteh** [comment]
Do you know of any open source M4B editors?

**Comment by geigi** [comment]
The only one I know is a command line tool: https://github.com/sandreas/m4b-tool#fixed-chapters

It has multiple ways of creating chapters. One of them is specifying them in a separate text file. I've not used the tool myself but it looks interesting.

**Comment by alexminder** [comment]
> Do you know of any open source M4B editors?

For tag only you can use any Tag editor. Most of them supports MP4.

More features have next projects:
- MP4Box ( https://gpac.wp.imt.fr )
- mp4tags ( https://code.google.com/p/mp4v2/ )

**Comment by alexminder** [comment]
For example, to produce Apple compatible Audiobook you can use:

`MP4Box -chap chapters.txt -brand 'M4B ' -itags name="TITLE":artist="Narrator":writer="AUTHOR":track="1/1":disk="1/1":genre=Audiobook:cover=cover.jpg -lang en-US  FILE.m4b`

**Comment by trymeouteh** [comment]
https://github.com/geigi/cozy/issues/541

An alternative to M4B?
