### ISSUE TITLE
No UTF-8 support

### ISSUE THREAD

**Issue by nicker7** [geigi/cozy#455]
### Bug/Feature description
the program does not have UTF-8 support for the fonts of Audiobooks. Leaving the space with %20, the ã with %C3%A3 and so on.

### Steps to reproduce
Try to rename files with characters like these here, ç ~ ´ ^ `

### System Information
- Operating System: Linux Mint 20.1 Cinnamon
- Installation source: Flatpak via application manager
- Version of cozy: 0.8.1

![photo_2021-03-14_19-06-21](https://user-images.githubusercontent.com/48894535/111085929-679c8980-84f8-11eb-83d4-b32cd38f4535.jpg)

![photo_2021-03-14_19-09-26](https://user-images.githubusercontent.com/48894535/111086009-dda0f080-84f8-11eb-8ce7-71ad2e158d80.jpg)

**Comment by geigi** [comment]
Hi :) this looks like a tagging issue. Could you please check with a tool like easyTAG that the Tags are correct for your files?

**Comment by geigi** [comment]
File names are only the fallback if no tags are present

**Comment by nicker7** [comment]
> Hi :) this looks like a tagging issue. Could you please check with a tool like easyTAG that the Tags are correct for your files?

Now it worked, I have to put the name of the title and the tracks all via tag for the program to recognize correctly, it is a little bit of work, but it works.

**Comment by geigi** [comment]
Glad it's working now, thanks for the feedback :)
