### ISSUE TITLE
Croatian translation

### ISSUE THREAD

**Issue by milotype** [geigi/cozy#456]
Please enable Croatian (hr) translation at https://www.transifex.com/geigi/cozy/
Thank you

**Comment by geigi** [comment]
Hey, do you want to translate Cozy to Croatian? I'm only adding languages when translators are present :)

**Comment by milotype** [comment]
Yes. I`ve already translated the "app"-file and part of the "extra"-file localy with the files from GitHub, but I thought you wouldn't accept a PR. I'm a translator at Transifex: https://www.transifex.com/user/profile/milotype/

**Comment by geigi** [comment]
Awesome! Thanks for your contribution! :) I'll add the language now and I'll invite you to the team. 
Transifex integrates better with Cozys workflow currently so this is perfect.
Note that the next release of Cozy will be propably in 2-3 weeks but your translation will be included then.

**Comment by milotype** [comment]
Thank you! I've just updated the Croatian files ...
If you want and if needed, you can also allow me to review translations ...

**Comment by geigi** [comment]
Done :) You should also be able to allow other people to join the Croatian translation now :)

**Comment by milotype** [comment]
Thanks.
Croatian translation of the app is complete.
Croatian translation of the extra-file is incomplete (but the essential part is translated).

**Comment by geigi** [comment]
Awesome :) yes there is a lot from old updates in the extra file That is not necessary.
