### ISSUE TITLE
Long titles without a whitespace do not get wrapped which results in very wide columns

### ISSUE THREAD

**Issue by paper42** [geigi/cozy#469]
### Bug/Feature description
I have an audio book which has wrong metadata like a long title without spaces (`%20` instead of spaces). This means the title doesn't get wrapped in the flowbox and all of its 60 characters are on one line. This results in a very wide column with a lot of empty space around it. This bug is also distributed to other columns, because the flowbox is set to be homogenous.

### Steps to reproduce
have an audiobook with a long title (like 60 characters) without spaces

### System Information
- Operating System: Void Linux
- Installation source: manual build
- Version of cozy: 0.9.3

**Comment by geigi** [comment]
Thanks for reporting :)

**Comment by chris-kobrzak** [comment]
Hi @paper42, I believe this should be fixed as of version 1.0.3 (PR #525). If you could try and import that book again it'd be greatly appreciated.

CC @geigi

**Comment by paper42** [comment]
@chris-kobrzak I am sorry that I didn't test this earlier. Your PR fixed the issue, thanks a lot! But, there are more :( When opening a book with a long title, the detailed view (with the book on the left and chapters on the right) is spread across multiple monitors because the window width is derived from the length of the title.

**Comment by geigi** [comment]
The issue in the book detail view will be resolved with v1.1 which will ship with a UI redesign :) it's already implemented in a feature branch.
