### ISSUE TITLE
Not launching after install

### ISSUE THREAD

**Issue by Frank-Schwarz** [geigi/cozy#48]
Installed .deb on Linux Mint 18
restarted computer
tried to launch but nothing happening.
new to linux so not sure if I messed anything up.
reinstalled and tried to launch cozy again.
still nothing.

**Comment by FoxyRiot** [comment]
$ sudo apt install python3-pip
$ pip3 install peewee

**Comment by Frank-Schwarz** [comment]
FoxyRiot - did that, but still nothing. Not sure what's going on.
restarted computer
Launched Cozy and got a small pinwheel spinning then nothing.

**Comment by geigi** [comment]
Could you try running cozy from the terminal and post the output here?
`$ com.github.geigi.cozy`

**Comment by Frank-Schwarz** [comment]
Traceback (most recent call last):
  File "/usr/bin/com.github.geigi.cozy", line 21, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'

**Comment by geigi** [comment]
Seems like I missed a dependency in the .deb...
Could you try installing `python3-gobject` and start cozy again from the terminal?

**Comment by Frank-Schwarz** [comment]
black_ghost@black-ghost ~ $ sudo apt install python3-pip
[sudo] password for black_ghost: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-pip is already the newest version (8.1.1-2ubuntu0.4).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
black_ghost@black-ghost ~ $ sudo apt install python3-gobject
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package python3-gobject is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python3-gobject' has no installation candidate
black_ghost@black-ghost ~ $ com.github.geigi.cozy
Traceback (most recent call last):
  File "/usr/bin/com.github.geigi.cozy", line 21, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
black_ghost@black-ghost ~ $ 

I appreciate all the help with this.

**Comment by geigi** [comment]
Thanks, my bad, the package is named `python3-gi` in your distro. Could you try installing that?

**Comment by Frank-Schwarz** [comment]
$ sudo apt install python3-gi

Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-gi is already the newest version (3.20.0-0ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by Frank-Schwarz** [comment]
com.github.geigi.cozy
Traceback (most recent call last):
  File "/usr/bin/com.github.geigi.cozy", line 21, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'

**Comment by geigi** [comment]
Ok thanks, I think I'll have to download a Linux Mint 18 iso and have a closer look at the problem...

**Comment by geigi** [comment]
Which version of Linux Mint are you running? Cinnamon, Xfce, MATE or KDE? And 64 or 32 bit?

**Comment by Frank-Schwarz** [comment]
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=18.2
DISTRIB_CODENAME=sonya
DISTRIB_DESCRIPTION="Linux Mint 18.2 Sonya"
NAME="Linux Mint"
VERSION="18.2 (Sonya)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 18.2"
VERSION_ID="18.2"
HOME_URL="http://www.linuxmint.com/"
SUPPORT_URL="http://forums.linuxmint.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/linuxmint/"
VERSION_CODENAME=sonya
UBUNTU_CODENAME=xenial
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=18.2
DISTRIB_CODENAME=sonya
DISTRIB_DESCRIPTION="Linux Mint 18.2 Sonya"
NAME="Linux Mint"
VERSION="18.2 (Sonya)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 18.2"
VERSION_ID="18.2"
HOME_URL="http://www.linuxmint.com/"
SUPPORT_URL="http://forums.linuxmint.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/linuxmint/"
VERSION_CODENAME=sonya
UBUNTU_CODENAME=xenial

Linux black-ghost 4.8.0-53-generic #56~16.04.1-Ubuntu SMP Tue May 16 01:18:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by geigi** [comment]
I just tested cozy with Linux Mint 18.2 Cinnamon and KDE and it was both working fine... 
Could you execute those commands and paste the output here?
```
$ python3 -c "import sys; print(sys.path)"
$ ls /usr/lib/python3/dist-packages
$ ls /usr/lib/python3/dist-packages/gi
$ ls /usr/lib/python3.5/dist-packages
```

**Comment by Frank-Schwarz** [comment]
black_ghost@black-ghost ~ $ python3 -c "import sys; print(sys.path)"
['', '/usr/local/lib/python36.zip', '/usr/local/lib/python3.6', '/usr/local/lib/python3.6/lib-dynload', '/home/black_ghost/.local/lib/python3.6/site-packages', '/usr/local/lib/python3.6/site-packages']
black_ghost@black-ghost ~ $ ls /usr/lib/python3/dist-packages
apt
apt_clone-0.2.1.egg-info
apt_clone.py
aptdaemon
apt_inst.cpython-35m-x86_64-linux-gnu.so
apt_pkg.cpython-35m-x86_64-linux-gnu.so
aptsources
AptUrl
apturl-0.5.2.egg-info
blinker
blinker-1.3.egg-info
Brlapi-0.6.4.egg-info
brlapi.cpython-35m-x86_64-linux-gnu.so
caffeine-2.9.4.egg-info
cairo
_cffi_backend.cpython-35m-x86_64-linux-gnu.so
chardet
chardet-2.3.0.egg-info
CommandNotFound
command_not_found-0.3.egg-info
cozy
Crypto
cryptography
cryptography-1.2.3.egg-info
cups.cpython-35m-x86_64-linux-gnu.so
cupsext.cpython-35m-x86_64-linux-gnu.so
cupshelpers
curl
dbus
_dbus_bindings.cpython-35m-x86_64-linux-gnu.so
_dbus_glib_bindings.cpython-35m-x86_64-linux-gnu.so
deb822.py
debconf.py
debian
debian_bundle
defer
defer-1.0.6.egg-info
dirspec
dirspec-13.10.egg-info
easy_install.py
ewmh
ewmh-0.1.5.egg-info
gi
hpmudext.cpython-35m-x86_64-linux-gnu.so
httplib2
httplib2-0.9.1.egg-info
_icu.cpython-35m-x86_64-linux-gnu.so
icu_docs.py
icu.py
idna
idna-2.0.egg-info
jwt
louis
louis-2.6.4.egg-info
lsb_release.py
lxml
lxml-3.5.0.egg-info
mako
Mako-1.0.3.egg-info
markupsafe
MarkupSafe-0.23.egg-info
mutagen
mutagen-1.31.egg-info
NvidiaDetector
oauthlib
oauthlib-1.0.3.egg-info
Onboard
onboard-1.2.0.egg-info
oneconf
oneconf-0.3.9.egg-info
orca
pcardext.cpython-35m-x86_64-linux-gnu.so
pexpect
pexpect-4.0.1.egg-info
PIL
Pillow-3.1.2.egg-info
pip
pip-8.1.1.egg-info
piston_mini_client
piston_mini_client-0.7.5.egg-info
pkg_resources
psutil
psutil-3.4.2.egg-info
ptyprocess
ptyprocess-0.5.egg-info
pyasn1
pyasn1-0.1.9.egg-info
pyatspi
__pycache__
pycrypto-2.6.1.egg-info
pycups-1.9.73.egg-info
pycurl-7.43.0.egg-info
pycurl.cpython-35m-x86_64-linux-gnu.so
pygobject-3.20.0.egg-info
pygtkcompat
PyICU-1.9.2.egg-info
PyICU.py
PyJWT-1.3.0.egg-info
python_apt-1.1.0.b1.egg-info
python_debian-0.1.27.egg-info
python_xapp-1.0.0.egg-info
python_xlib-0.14.egg-info
pyxdg-0.25.egg-info
Quirks
reportlab
reportlab-3.3.0.egg-info
requests
requests-2.9.1.egg-info
scanext.cpython-35m-x86_64-linux-gnu.so
sessioninstaller
sessioninstaller-0.0.0.egg-info
setproctitle-1.1.8.egg-info
setproctitle.cpython-35m-x86_64-linux-gnu.so
setuptools
setuptools-20.7.0.egg-info
six-1.10.0.egg-info
six.py
speechd
speechd_config
system_service-0.3.egg-info
tccalib
thin_client_config_agent-0.8.egg-info
UbuntuDrivers
ubuntu_drivers_common-0.0.0.egg-info
UbuntuSystemService
ufw
ufw-0.35.egg-info
unohelper.py
uno.py
urllib3
urllib3-1.13.1.egg-info
virtkey-0.63.0.egg-info
virtkey.cpython-35m-x86_64-linux-gnu.so
wheel
wheel-0.29.0.egg-info
xapian
xapp
xdg
xkit
xkit-0.0.0.egg-info
Xlib
black_ghost@black-ghost ~ $ ls /usr/lib/python3/dist-packages/gi
_constants.py                              _option.py
docstring.py                               overrides
_error.py                                  _propertyhelper.py
_gi_cairo.cpython-35m-x86_64-linux-gnu.so  __pycache__
_gi.cpython-35m-x86_64-linux-gnu.so        pygtkcompat.py
_gobject                                   repository
importer.py                                _signalhelper.py
__init__.py                                types.py
module.py
black_ghost@black-ghost ~ $ ls /usr/lib/python3.5/dist-packages
ls: cannot access '/usr/lib/python3.5/dist-packages': No such file or directory

I also included:
black_ghost@black-ghost ~ $ python3
Python 3.6.3 (default, Nov 12 2017, 15:32:47) 
[GCC 5.4.0 20160609] on linux

**Comment by geigi** [comment]
Ok there seems to be an issue with your `PYTHONPATH`. 
Normally Linux Mint (aswell as all Debian destributions) save their python libs in `/usr/lib/python3/dist-packages` which is missing from your `PYTHONPATH` (the first command you executed prints this path). From the `ls` we can see that the missing package is there (folder `gi`), but cannot be found by python. After you've added this path back to the variable, you should be able to run cozy. There are a lot of ways on how to do this, check this out for example:
https://stackoverflow.com/questions/3402168/permanently-add-a-directory-to-pythonpath

**Comment by Frank-Schwarz** [comment]
oh man what a headache.
I appreciate all the help. I took the Python 3.6 off my system and launched Cozy.
Cozy is actively importing my library!
This is going to take a long time. LOL
1114 books.
Thank you for the help.

**Comment by geigi** [comment]
Awesome!! Man that's a lot of books :D Let me know how good cozy can handle your library ;)

**Comment by Frank-Schwarz** [comment]
It's chugging along. Nothing to really see right now.
Hopefully by tomorrow.
