### ISSUE TITLE
`SqliteQueueDatabase` object has no attribute 'server_version' when running from source

### ISSUE THREAD

**Issue by chris-kobrzak** [geigi/cozy#483]
### Bug/Feature description

```
['app/bin/com.github.geigi.cozy']
00:32:36 [MainThread  ] [applicatio] [INFO ]  ('ubuntu', '20.04', 'focal')
00:32:36 [MainThread  ] [applicatio] [INFO ]  Starting up cozy 0.9.5
handle exception
Traceback (most recent call last):
  File "~/Projects/cozy/app/lib/python3/dist-packages/cozy/application.py", line 86, in do_startup
    init_db()
  File "~/Projects/cozy/app/lib/python3/dist-packages/cozy/control/db.py", line 27, in init_db
    sqlite_version = ".".join([str(num) for num in _db.server_version])
AttributeError: 'SqliteQueueDatabase' object has no attribute 'server_version'
```

### Steps to reproduce

Build the app with `meson` and `ninja` commands as per the project README. When you execute:

```
XDG_DATA_DIRS=app/share:/usr/share \
PYTHONPATH=app/lib/python3/dist-packages \
  app/bin/com.github.geigi.cozy
```

... the error pasted above is thrown and the application fails to load.

If I edit the build file `app/lib/python3/dist-packages/cozy/control/db.py` and hard-code [sqlite_version](/geigi/cozy/blob/master/cozy/control/db.py#L27) to a number, the application runs without any issues.

### System Information
- Operating System: Ubuntu 20.04.2 LTS
- Installation source: GitHub
- Version of cozy: `5d239fe`

**Comment by chris-kobrzak** [comment]
I've provisioned an Ubuntu box again, installed all required packages and I haven't been able to reproduce the issue so closing this ticket.

**Comment by geigi** [comment]
Hi,
Sorry for the late answer.

I'm glad you got it working :) if there is anything that doesn't work or you need some support let me know :)
