### ISSUE TITLE
Another launch failure - Ubuntu 17.10

### ISSUE THREAD

**Issue by Thomas-O** [geigi/cozy#51]
Cozy won't launch on Ubuntu 17.10. The problem seems to be with the Pythonpath - at least I have the same reports as issue no.50.

Is there anyway to get around this without changing the path or removing python 3.6? I'm not super technical so changing the path would be a week-long challenge, and I'm never keen on removing something unless I'm 100% certain it's not needed.

I installed Cozy via the deb.

Thanks for your help.

Thomas

**Comment by geigi** [comment]
The launch problems should now be fixed also for Ubuntu 17.10 with the latest deb (the version number hasn't changed)

**Comment by Thomas-O** [comment]
Launch is working just fine now. Thank you.
