### ISSUE TITLE
specify multiple directories for library

### ISSUE THREAD

**Issue by HansCz** [geigi/cozy#52]
It would be useful to be able to specify multiple directories where Cozy will scan for audiobooks.

**Comment by albertaparicio** [comment]
It would be good also to let any directory be scanned. I have tried the Flatpak version and I can only scan directories in ~/Music. I would like to scan a different hard drive directory

Thanks

**Comment by geigi** [comment]
@albertaparicio Hey :) This is just a limitation of the flatpak version. The flatpak team suggested to do this to improve the security provided by the flatpak sandbox. You can override the default setting for `com.github.geigi.cozy` and add access to other directories using the flatpak tool: http://docs.flatpak.org/en/latest/working-with-the-sandbox.html#overriding-sandbox-permissions

**Comment by da2x** [comment]
I also wondered about this. @geigi, shouldn’t this limitation be documented in the Preferences: Files dialog?

**Comment by geigi** [comment]
@da2x Do you mean selecting multiple directories or the flatpak issue (which should be fixed in the current flatpak version)?

**Comment by da2x** [comment]
I’m using the flatpak version and understood this to be a limitation of the flatpak sandbox. So it would be useful to document this limitation in the dialog, as I also wanted to add multiple directories.

**Comment by geigi** [comment]
This feature will be included in the next release :)
