### ISSUE TITLE
Can't open app anymore

### ISSUE THREAD

**Issue by dspacejs** [geigi/cozy#523]
### Bug description

I just tried opening the app and this was shown:

![Screenshot from 2021-06-03 15-52-12](https://user-images.githubusercontent.com/9282837/120597083-bf0d1e80-c483-11eb-94a4-a0032b7bd07c.png)

I don't recall updating Cozy (unless it was done automatically, and I assume it was).

### Steps to reproduce

I'm not sure what caused this, or how to reproduce it. All I've done is opened the app, I can't even get to the interface.

### System Information
- Operating System: Ubuntu 20.04.2 LTS (GNOME 3.36.8)
- Installation source: flatpak
- Version of cozy: 1.0.2

**Comment by geigi** [comment]
Hey,

Could you please upload Cozy's log after you tried starting Cozy?

```
~/.var/app/com.github.geigi.cozy/data/cozy/cozy.log

```

**Comment by shauravkhadka** [comment]
Did anyone get a fix?

**Comment by geigi** [comment]
@shauravkhadka please upload Cozy's log file here so that I can have a look at your problem:
```
~/.var/app/com.github.geigi.cozy/data/cozy/cozy.log
```

**Comment by dspacejs** [comment]
@geigi I did `tail -f` and it didn't log anything during startup. But I've attached the log file anyway, maybe there's something useful
[cozy.log](https://github.com/geigi/cozy/files/6597913/cozy.log)

**Comment by geigi** [comment]
Thanks for the log! There is one line that shows the error:
```
15:52:04 [MainThread  ] [db_updater] [ERROR]  UNIQUE constraint failed: file.path
```
Seems like somehow one file is present multiple times in Cozy's DB. This was possible previously but since v1.0 this cannot happen anymore. But I missed to test this case when migrating the db to the new schema. I'll work on a fix.

**Comment by shauravkhadka** [comment]
Hey, so You're Geigi(The developer himself?) first of all, thanks for your work. But, I guess there was some problem during the last update of the software. I have the same problem as shown in the picture above. and also I couldn't locate cozy in terminal or synaptic package manager.

**Comment by geigi** [comment]
I found the issue. The fix will be included in the next release.

Note: If you find duplicate chapters in your library you can use "Force refresh" in the settings to scan all files again. This will take longer than usual.

**Comment by geigi** [comment]
@shauravkhadka Thanks, I'm happy you're enjoying Cozy. 
Did you install Cozy via Flathub/Flatpak? Then you can find Cozy on your system with the command `flatpak list`. 
I fixed an issue during the DB update but I can only verify that it is the same issue you experience if you upload Cozy's log file which is located here:
```
~/.var/app/com.github.geigi.cozy/data/cozy/cozy.log
```

**Comment by shauravkhadka** [comment]
[cozy.log](https://github.com/geigi/cozy/files/6598548/cozy.log)

I installed it through software package manager in Linux mint and it shows flathub in detail there. It also says to downgrade to older version before the problem is fixed. can you help me with how to do that?

**Comment by shauravkhadka** [comment]
![image](https://user-images.githubusercontent.com/58943767/120803797-a4aa7200-c563-11eb-8f47-4ba927476e94.png)
doesn't show up in the list of packages

**Comment by geigi** [comment]
@shauravkhadka Thanks for the log! Your issue will be fixed in the next release which I will publish later today.
Linux Mint installed Cozy as a [Flatpak](https://flatpak.org/) that's why you can't see it the usual way. 
If you use `flatpak list` you'll find Cozy listed there.
Downgrading with Flatpak is a big complicated currently, therefore I suggest to wait a couple of hours then the new version of Cozy will be out including the fix.

**Comment by shauravkhadka** [comment]
oh okay, I get it now. Thanks, I'm new to Linux so didn't know about these things. I've very excited for the new release.

**Comment by geigi** [comment]
No worries :) Flatpak is completely independent from your apt / synaptics package manager, but the Linux Mint software package manager has support for Flatpak. That's why you can see it there but not in other tools. I can see that this might be confusing for people who are new to Linux :)

**Comment by geigi** [comment]
FYI: I just published the new release :)

**Comment by shauravkhadka** [comment]
Thanks, I'll check it out

**Comment by dspacejs** [comment]
@shauravkhadka you have to do `flatpak update`.

@geigi it works fine, thanks for the fix.

**Comment by shauravkhadka** [comment]
@dspacejs did it @geigi works like charm, thanks.
