### ISSUE TITLE
Alternate display for playback progress

### ISSUE THREAD

**Issue by HansCz** [geigi/cozy#53]
As it is now, the playback progress, i.e. the line that fills up while playing, and has a handle you can drag back and forth to move around in the current file, allows me to scrub through the file currently playing.
I was wondering if it would be possible to have the playback progress encompass all files in a given audiobook,

Example:
An audiobook consists of 5 files each 60 minutes long.
As it is now,  I can only drag from 0:00 to 60:00
I would like to be able to drag from 0:00 to 300:00 even though the audiobook consists of 5 files

As for how to allow the user to choose whether the playback progress only encompasses one file or the entire audiobook, I would suggest having it as an option in the preferences, and maybe alternately allow to switch between the two modes by clicking the total duration value to the right of the playback progress line.

I hope this makes sense, otherwise feel free to ask for further explanation.

**Comment by geigi** [comment]
This is a cool idea, I will definitely test this. The fast file switching that is needed might cause some problems on slower computers with hard drives but I think it's pretty cool as an option :)

**Comment by HansCz** [comment]
What do you believe will cause the slowdown?
I have only started skimming your code, and am not entirely at home in it yet :)

Do you read a given entire file into memory before playing any part of it, or?
I am curious to find out how you have constructed it.

**Comment by geigi** [comment]
It could slow down if a drive has to spin up or something like that. But maybe it's not as big of an issue as I thought ;)

Cool! If you need any help let me know. This is my first python & gtk project so it's probably not the best coding style.
I'm using a `gstreamer playbin` for the playback. This makes the playback a lot easier as it does a lot of stuff automatically. The only thing it really needs to get the playback running is a path to a file. It also does the buffering automatically by copying only a part of the track into the memory.
You can find all of the player related code in `cozy/player.py`.

**Comment by geigi** [comment]
I've implemented this feature and it'll be in the next release ;)
