### ISSUE TITLE
Trim book title

### ISSUE THREAD

**Issue by dspacejs** [geigi/cozy#539]
### Feature description

The title is way too long in this example, and it should be trimmed (otherwise the progress bar is tiny):

![Screenshot from 2021-06-15 11-37-41](https://user-images.githubusercontent.com/9282837/121982190-37ea6f80-cdce-11eb-9c6a-6c71cb08216d.png)

The sidebar can have the full title, but the top bar should be a short version in this case:

![Screenshot from 2021-06-15 11-39-32](https://user-images.githubusercontent.com/9282837/121982329-76802a00-cdce-11eb-9969-8e76758a90b0.png)

### Steps to reproduce

1. Add a book with a really long title
2. Play it

### System Information
- Operating System: Ubuntu 20.04.2 LTS
- Installation source: flatpak
- Version of cozy: 1.0.3

**Comment by geigi** [comment]
Thanks for reporting :) I'm working on a UI redesign where this issue is solved.
