### ISSUE TITLE
Offering a danish translation

### ISSUE THREAD

**Issue by HansCz** [geigi/cozy#54]
If you would like a danish translation, I am able an willing :)

**Comment by geigi** [comment]
Yeah that would be awesome! You can translate cozy using transifex (or create a pull request):
https://www.transifex.com/geigi/cozy/
As I'm currently starting to implement orca screen reader support, there will be new stuff to translate in the next versions. But I'm happy about everyone that wants to contribute :)

**Comment by HansCz** [comment]
Nice!
I have my own po editor set up, so I'll send you a pull request when it's done.

**Comment by Distil62** [comment]
I send on transifex for make a french translation.

**Comment by geigi** [comment]
@Distil62 Awesome! I just found all the requests on Transifex and added you to the team :)

**Comment by Distil62** [comment]
French done.

**Comment by geigi** [comment]
@Distil62 Thanks! It's included in the latest release :)

**Comment by HansCz** [comment]
Hey @geigi 
I just requested Danish on transifex, could you please add it?

**Comment by geigi** [comment]
@HansCz Cool, I've added Danish and sent you an invitation ;)
