### ISSUE TITLE
Sidebar progress not changing

### ISSUE THREAD

**Issue by dspacejs** [geigi/cozy#540]
### Bug description

The progress in the sidebar isn't changing:

![Screenshot from 2021-06-15 11-39-32](https://user-images.githubusercontent.com/9282837/121982370-8a2b9080-cdce-11eb-85d2-5477a8165b1a.png)

### Steps to reproduce

1. Play an audiobook
2. Check the progress in the sidebar, it shouldn't change (even if the top bar's progress is) 

### System Information
- Operating System: Ubuntu 20.04.2 LTS
- Installation source: flatpak
- Version of cozy: 1.0.3

**Comment by geigi** [comment]
Thanks for reporting, this will be definitely fixed in the next release.

**Comment by geigi** [comment]
The sidebar works correctly in the current master branch
