### ISSUE TITLE
Set window size? 

### ISSUE THREAD

**Issue by Stochastica72** [geigi/cozy#544]
### Bug/Feature description
Is there a way to set the window size? Preferably from the command line? I open cozy without running a window manager and I would like to be able to force it full screen. 
### System Information
- Operating System: 
- Installation source: 
- Version of cozy:

**Comment by geigi** [comment]
Hey :) Currently there is no way to do that without a window manager. Maybe there is a generic GTK way to do this but I don't know...

**Comment by rdbende** [comment]
Hi,

you can achieve this using `gsettings` (for the Flatpak version you'd need to run this command inside the sandbox):
```
gsettings set com.github.geigi.cozy window-maximize true
```

There are no plans, however to add a command line option for this.
