### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by forteller** [geigi/cozy#546]
### Bug/Feature description
Hi. This seems like a great tool, but unfortunately it does not work for me. I just installed the Flathub version via Software and tried it for the first time, and there's no sound. I've verified that I get sound from other applications, and that the volume in Cozy is high. I've tried six different audiobooks, all mp3s. 

### Steps to reproduce
- Import a folder
- Try to play a book
- Notice no sound

### System Information
- Operating System: Ubuntu 21.04
- Installation source: Software 3.38.1 (Source: dl.flathub.org
- Version of cozy: 1.0.3

Thanks!

**Comment by geigi** [comment]
Hi!

This is very likely an issue with your setup as this never occurred before. But maybe I can help a bit. Could you upload Cozy's log here?

```
~/.var/app/com.github.geigi.cozy/data/cozy/cozy.log
```

Did you make sure that Cozy's volume is also at 100% in your system settings? Also did you make any settings/modifications with flatpak?

**Comment by forteller** [comment]
Wow, ok, so the app volume in system settings was the problem. It was set to 0. But why? I never changed those settings, it was just automatically set to 0 the first, and every, time I opened the application.

Thank you for the help, and the work you do! 

Here's the log, in case there's something in it that could help you make sure this doesn't happen again for anyone else.
[cozy.log](https://github.com/geigi/cozy/files/6840425/cozy.log)
[cozy_1.log](https://github.com/geigi/cozy/files/6840434/cozy_1.log)

**Comment by geigi** [comment]
That's weird... There is nothing suspicious in the log. So this bug still occurs every time you open Cozy again? Is the volume slider in Cozy linked to the slider in system settings on your machine?

**Comment by forteller** [comment]
Sorry, I did not express myself clearly. That's my fault.

What I meant to say is that the volume for Cozy in the system settings was set to 0 every time I opened it, until I changed it manually. That is, I just wanted to convey that it didn't just happen the first time I opened it, it was always 0 until I changed it. After I changed it it's staying on the spot I changed it to. 

Cozy does not change it back. But it should not be 0 by default, no other applications have done that, and it's extremely confusing. If I was not the kind of person who report issues like this I would just assume the application was broken and given up on it.

Regarding your question about the sliders: Yes, now when I change the volume in Cozy it also changes the volume for Cozy in the system settings. But before reporting the issue I did check the volume slider inside Cozy, and it was set to 100, while, as you know, the Cozy volume in the system settings where 0. I don't remember if I tried to change the volume inside Cozy or not before reporting the issue. I might not have, since it was already set to 100.

**Comment by geigi** [comment]
Thanks for the clarification :) cozy also doesn't set the volume to 0 by default. I've tested it on a clean system again. It must be some weird bug either in cozy or the desktop environment... do you use gnome in your System?

A workaround in cozy's code that might fix the problem: Setting the player volume explicitly to the default value (100%) at first startup.

**Comment by forteller** [comment]
I use Gnome, yes. That workaround sounds like a good idea. :)
