### ISSUE TITLE
Folder/File naming

### ISSUE THREAD

**Issue by asim-vax** [geigi/cozy#56]
Hi,
Apologies for this - How should the folder be named/file names work for it to a) pick up the authors name and b) handle audio book split into separate files?

Thanks,

**Comment by geigi** [comment]
Hey,
the file/folder names are actually irrelevant. Cozy get's all of this information from the metadata in your audiofiles. 
I use EasyTag to set these right for my files, which worked pretty well. Be sure to add the **book reader** to the **Artist field**, and the **book author** to the **Composer field**. This seems to be how most audiobooks are tagged ;)

**Comment by asim-vax** [comment]
thank you very much :) very much appreciated!
