### ISSUE TITLE
Lost book covers during initial scan

### ISSUE THREAD

**Issue by Frank-Schwarz** [geigi/cozy#57]
This issue started at 0.4.1
I have updated to 0.4.2 with the .deb
I have a huge audiobook library, but have not had a full scan yet.
Some covers were there, but have now disappeared.

Could you let me know what I should do to help you figure out this issue

Linux Mint 18.2 Cinnamon

**Comment by Frank-Schwarz** [comment]
System:    Host: black-ghost Kernel: 4.10.0-40-generic x86_64 (64 bit gcc: 5.4.0)
           Desktop: Cinnamon 3.4.6 (Gtk 3.18.9-1ubuntu3.3)
           Distro: Linux Mint 18.2 Sonya
Machine:   Mobo: MSI model: FM2-A55M-E33 (MS-7721) v: 2.0
           Bios: American Megatrends v: V11.3 date: 07/16/2013
CPU:       Quad core AMD A8-5600K APU with Radeon HD Graphics (-MCP-) cache: 8192 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm) bmips: 28749
           clock speeds: max: 3600 MHz 1: 1900 MHz 2: 1900 MHz 3: 3200 MHz
           4: 2800 MHz
Graphics:  Card: Advanced Micro Devices [AMD/ATI] Cedar [Radeon HD 5000/6000/7350/8350 Series]
           bus-ID: 01:00.0
           Display Server: X.Org 1.18.4 drivers: ati,radeon (unloaded: fbdev,vesa)
           Resolution: 1920x1080@60.00hz
           GLX Renderer: Gallium 0.4 on AMD CEDAR (DRM 2.49.0 / 4.10.0-40-generic, LLVM 4.0.0)
           GLX Version: 3.0 Mesa 17.0.7 Direct Rendering: Yes
Audio:     Card-1 Advanced Micro Devices [AMD] FCH Azalia Controller
           driver: snd_hda_intel bus-ID: 00:14.2
           Card-2 Advanced Micro Devices [AMD/ATI] Cedar HDMI Audio [Radeon HD 5400/6300 Series]
           driver: snd_hda_intel bus-ID: 01:00.1
           Card-3 Microsoft LifeCam Studio driver: USB Audio usb-ID: 002-004
           Sound: Advanced Linux Sound Architecture v: k4.10.0-40-generic
Network:   Card-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller
           driver: r8169 v: 2.3LK-NAPI port: d000 bus-ID: 02:00.0
           IF: enp2s0 state: up speed: 1000 Mbps duplex: full mac: <filter>
           Card-2: Qualcomm Atheros AR93xx Wireless Network Adapter
           driver: ath9k bus-ID: 03:00.0
           IF: wlp3s0 state: down mac: <filter>
Drives:    HDD Total Size: 3762.8GB (30.5% used)
           ID-1: /dev/sda model: Crucial_CT512MX1 size: 512.1GB
           ID-2: /dev/sdb model: TOSHIBA_DT01ACA0 size: 500.1GB
           ID-3: /dev/sdc model: WDC_WD2003FYYS size: 2000.4GB
           ID-4: /dev/sdd model: ST3750528AS size: 750.2GB
           Optical: No optical drives detected.
Partition: ID-1: / size: 454G used: 34G (8%) fs: ext4 dev: /dev/sda1
           ID-2: swap-1 size: 17.13GB used: 0.00GB (0%) fs: swap dev: /dev/sda5
RAID:      No RAID devices: /proc/mdstat, md_mod kernel module present
Sensors:   System Temperatures: cpu: 40.0C mobo: N/A gpu: 48.5
           Fan Speeds (in rpm): cpu: N/A
Info:      Processes: 243 Uptime: 13 min Memory: 3075.0/16064.3MB
           Init: systemd runlevel: 5 Gcc sys: 5.4.0
           Client: Shell (bash 4.3.481) inxi: 2.2.35

**Comment by geigi** [comment]
Ok so you started an import with cozy but it did not finish completely? And from the files that are already imported some book covers got missing after the update? Is there a reason you didn't do a full scan yet?

**Comment by Frank-Schwarz** [comment]
There are no book covers. I have some book titles and some reader names.
I have not done a full scan because after hours of importing cozy show only halfway completed. Usually, I have it sitting in the background churning away, but have never made it past the halfway mark. I figured it was just because my library is so large.

**Comment by geigi** [comment]
Ok so this sounds like I definitely have to take a look at the importer again and if I can speed this up somehow. Are the audiobooks of you properly tagged? Do they have the album cover embedded in the files or is it a separate image file side-by-side with the audio files?

**Comment by Frank-Schwarz** [comment]
Most are properly tagged and most have embedded covers

**Comment by Frank-Schwarz** [comment]
2 builds ago it was grabbing the covers.

**Comment by geigi** [comment]
Ok I'll have a look. Must be something I changed then...

**Comment by geigi** [comment]
Ok I have no idea what is causing this... Do you see the placeholder image for the book covers or no book cover at all?
![a](https://github.com/geigi/cozy/raw/master/data/img/blank_album.png)

**Comment by Frank-Schwarz** [comment]
no covers at all

**Comment by geigi** [comment]
Ahh I see, I looked at the wrong places. Could you start cozy from the terminal again and post the output here? There will be probably an error message.
Btw: Thanks a lot for all your effort! It's people like you that really help making open source projects flourish ;)

**Comment by Frank-Schwarz** [comment]
Any way I can help. This is a great project!

black_ghost@black-ghost ~ $ com.github.geigi.cozy
/home/black_ghost/.local/share/cozy
['/usr/bin/com.github.geigi.cozy']
INFO:main:Starting up cozy 0.4.2
INFO:ui:Initialize main window
Traceback (most recent call last):
  File "/usr/bin/com.github.geigi.cozy", line 63, in do_activate
    self.ui.activate()
  File "/usr/lib/python3/dist-packages/cozy/ui.py", line 48, in activate
    self.refresh_content()
  File "/usr/lib/python3/dist-packages/cozy/ui.py", line 570, in refresh_content
    self.book_box.add(BookElement(b, self))
  File "/usr/lib/python3/dist-packages/cozy/book_element.py", line 191, in __init__
    self.art = AlbumElement(self.book, 180, True)
  File "/usr/lib/python3/dist-packages/cozy/book_element.py", line 27, in __init__
    pixbuf = get_cover_pixbuf(book, size)
  File "/usr/lib/python3/dist-packages/cozy/db.py", line 143, in get_cover_pixbuf
    loader.close()
GLib.Error: gdk-pixbuf-error-quark: Unrecognized image file format (3)

**Comment by geigi** [comment]
Ok awesome! Looks like there is an embedded album image that can not be properly recognized. I'll create a fix for this.

**Comment by geigi** [comment]
Hey sorry for the late answer, the new version has the fix included: Let me know if something is not working ;) https://github.com/geigi/cozy/releases/download/0.4.3/com.github.geigi.cozy_0.4.3_all.deb

**Comment by geigi** [comment]
I've also created a repository for Ubuntu 17.10: https://software.opensuse.org//download.html?project=home%3Ageigi&package=com.github.geigi.cozy

**Comment by Frank-Schwarz** [comment]
Awesome. Going to try this out. will report any issues. Thank you so much for the help.
