### ISSUE TITLE
Translation and terminology - suggest replacing term 'track' with 'part'

### ISSUE THREAD

**Issue by HansCz** [geigi/cozy#60]
I invite you to consider if exchanging the term 'track' with the term 'part' would be more easily understandable to the user.

I get that 'track' is the term used internally in the code. Here, 'track' refers to a given sound file that is part of an audio book.

But the term 'track' conventionally refers to a single performance on an album of musical performances. One that more often than not can exist outside the context of the album and still make sense on its own.

In an audiobook, a track is much more closely tied to the tracks that come before and after. I.e. given the sequential nature of a narrative, It is unlikely that a track would make much sense without having listened to its preceding tracks.

Would it therefore not make a lot of sense to rename 'tracks' to 'parts'?

**Comment by geigi** [comment]
That makes sense, I like "part" a lot better than "track". Thanks for your suggestion! I will change this in the next couple of days.
