### ISSUE TITLE
Flatpak: audiobook folder outside xdg-music

### ISSUE THREAD

**Issue by tellingsen** [geigi/cozy#61]
The flatpak version hosted on flathub doesn't allow the selection of an audiobook directory outside the directory specified in `~/.config/user-dirs.dirs` as `XDG_MUSIC_DIR`. 

From looking at the [manifest file](https://github.com/flathub/com.github.geigi.cozy/blob/master/com.github.geigi.cozy.json) on the flathub repo it appears that the flatpak sandbox permissions are only set to allow access to the xdg-music directory (line 13: `--filesystem=xdg-music`). 

I would request that line 13 be changed to `--filesystem=home` thus allowing users to specify any directory within their home directory as their audiobook dir.

In the meantime users who run the flathub version and who have their audiobook directory outside their music directory can override the sandbox setting by runing the following command:
`flatpak --user override --filesystem=home com.github.geigi.cozy`

**Comment by geigi** [comment]
I've changed this in the latest flatpak version: https://github.com/flathub/com.github.geigi.cozy/commit/7e85bdf4e31c71c3006f114a194d244d77b111e3

**Comment by tellingsen** [comment]
Oh, great - thank you! And thank you for your work getting out the flatpak version :)
