### ISSUE TITLE
Missing signing key on Launchpad PPA page for Cozy stable release

### ISSUE THREAD

**Issue by TheJags** [geigi/cozy#613]
### Bug/Feature description
I'm trying to add launchpad PPA for Cozy stable release, and import GPG key from it's signing key / fingerprint but couldn't find any key.
### Steps to reproduce
[https://launchpad.net/~cozy-team/+archive/ubuntu/cozy](https://launchpad.net/~cozy-team/+archive/ubuntu/cozy)

Doesn't list any signing key.
### System Information
- Operating System: Ubuntu MATE Hirsute 21.04
- Installation source: https://launchpad.net/~cozy-team/+archive/ubuntu/cozy
- Version of cozy: 1.1.0-2~ubuntu21.04.1

Many thanks.

**Comment by geigi** [comment]
@apandada1 maybe you can help out here? 😊

**Comment by apandada1** [comment]
I did not get this when I installed. I will check. Not sure if my keys expire. Could you post the full output?

**Comment by apandada1** [comment]
I was able to install it without any errors in a Ubuntu MATE 21.04 live image running in a VM. 
![image](https://user-images.githubusercontent.com/3063132/128645053-ec086f41-6d37-496a-b886-d9bdb4180fa4.png)


Could you ask a question at http://askubuntu.com ? It might be a problem specific to your system, and people there can help you troubleshoot.

You can post the full error message here too, I will try to figure out the issue.

**Comment by TheJags** [comment]
@apandada1 @geigi By now I have found a workaround, and have installed `Cozy` on `Ubuntu MATE Hirsute 21.04` already.

But just to be extra clear, here are two screenshots regarding the `signing key / fingerprint` I was looking for.

(1) Cozy PPA page: Where there is no signing key / fingerprint listed:
![Cozy_PPA](https://user-images.githubusercontent.com/47936415/128645442-ee0fa73b-b43f-4ef4-9853-a8a1d164e028.jpg)

(2) SMPlayer PPA page: Where you can see signing key / fingerprint is listed.
![SMplayer_PPA](https://user-images.githubusercontent.com/47936415/128645446-056333a1-de90-4605-990a-94e0cf9c9100.jpg)

By the way, this is how I have added the PPA / import GPG key:

````
sudo nano /etc/apt/sources.list
And added:
deb [arch=amd64 signed-by=/usr/share/keyrings/cozy-archive-keyring.gpg] http://ppa.launchpad.net/cozy-team/cozy/ubuntu hirsute main
Then:
sudo gpg --no-default-keyring --keyring /usr/share/keyrings/cozy-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 5DD7991B3AA59025
sudo apt update
sudo apt install cozy
````

Many thanks for your quick replies.

**Comment by apandada1** [comment]
I just noticed that the PPA does not show a signing key while other PPAs do have one. I asked a question here, and someone said that the key exists, but it is somehow not shown in the Launchpad page. I have no clue why it is so.
https://askubuntu.com/questions/1356784/why-does-my-ppa-not-have-any-signing-key

Note that it adds the same key when I add the PPA it to the system.
![image](https://user-images.githubusercontent.com/3063132/128645558-ec882e77-8c9a-4f70-85b1-ececdcc826f1.png)

**Comment by TheJags** [comment]
> I just noticed that the PPA does not show a signing key while other PPAs do have one. I asked a question here, and someone said that the key exists, but it is somehow not shown in the Launchpad page. I have no clue why it is so.
> https://askubuntu.com/questions/1356784/why-does-my-ppa-not-have-any-signing-key
> 
> Note that it adds the same key when I add the PPA it to the system.

Yes, I did see that question on AskUbuntu, and yes, that is the key that was added with this command:

`sudo gpg --no-default-keyring --keyring /usr/share/keyrings/cozy-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 5DD7991B3AA59025
`

As I have mentioned in my previous post, I found a workaround and the issue is resolved for me...

But I would say, if you somehow resolve the issue with Launchpad PPA, it would help many others.

Thank you so much for quick reply and AskUbuntu thread :)

**Comment by apandada1** [comment]
If one uses `add-apt-repository`, this issue would not appear (If launchpad
does not show it, there is nothing I can do about it).

Let's see if we get any other solution in Ask Ubuntu.

**Comment by TheJags** [comment]
> If one uses `add-apt-repository`, this issue would not appear...

Yes, but I believe nowadays adding repository / PPA by `add-apt-repository` is no longer a preferred way.

Here are few discussions on it:

https://manpages.debian.org/testing/apt/apt-key.8.en.html

https://www.linuxuprising.com/2021/01/apt-key-is-deprecated-how-to-add.html

https://askubuntu.com/questions/1328806/how-to-solve-apt-key-deprecated

Lastly, I recognized your name on PPA page, as you're very active on AskUbuntu; and that's the reason I raised an issue here.

Thanks again :)

**Comment by apandada1** [comment]
I added the key to the [PPA description](https://launchpad.net/%7Ecozy-team/+archive/ubuntu/cozy). I will also file a bug in Launchpad support. Right now there is nothing more I can do about it (as I can't control how Launchpad works).

**Comment by TheJags** [comment]
> I added the key to the [PPA description](https://launchpad.net/%7Ecozy-team/+archive/ubuntu/cozy). I will also file a bug in Launchpad support. Right now there is nothing more I can do about it (as I can't control how Launchpad works).
> 
> Can we close this issue?

Yes, and thank you for adding signing key to the PPA description.

**Comment by geigi** [comment]
Thanks @apandada1 for helping out :) I just noticed you're not in the contributors list yet, I'll add you next time I'm at my laptop :)
