### ISSUE TITLE
Use HdyPreferencesWindow

### ISSUE THREAD

**Issue by bertob** [geigi/cozy#614]
The current preferences window has a number of minor issues (padding inside the dialog, stack switcher instead of view switcher, non-rounded listboxes, non-modal, etc.) that wouldn't happen if it was an HdyPreferencesWindow :)

![image](https://user-images.githubusercontent.com/1908896/128699262-1f2382d7-e478-48ff-8569-7ccf34b620a2.png)

**Comment by geigi** [comment]
Thanks for reporting! :) There is already an issue open regarding this: #404 I'll close this one as a duplicate.
