### ISSUE TITLE
Add m4b support

### ISSUE THREAD

**Issue by cjfloss** [geigi/cozy#62]
The application do not read the cover-art and the artist from .ogg files

the application do not recognize .m4b files

**Comment by geigi** [comment]
Ogg should be working, could you import a few of your ogg files on a fresh cozy (backup and remove the database from ~/.local/share/cozy/) by drag & dropping them to the cozy window? Please start cozy from the terminal and paste the output here:
`$ com.github.geigi.cozy -d`

**Comment by geigi** [comment]
Thanks for reporting all of those issues!

**Comment by Cleiton-Floss** [comment]
I have deleted the database and imported two books
- Arthur Schopenhauer - The Art Of Controversy (.mp3)
- Charles Darwin - Origin Of The Species (.ogg)

**Comment by Cleiton-Floss** [comment]
Here is the output https://pastebin.com/RiZNk1Rm

![screenshot from 2017-12-25 17 50 53](https://user-images.githubusercontent.com/5838486/34343344-e4e52980-e9a9-11e7-9746-c68130e4dd1d.png)
![screenshot from 2017-12-25 17 51 02](https://user-images.githubusercontent.com/5838486/34343348-eb5d9f2c-e9a9-11e7-8c6e-15cf376fe3bb.png)

**Comment by geigi** [comment]
Thanks! Ok it seems like the ogg's don't have a embedded cover image using the standard "metadata_block_picture" tag. This tag should contain the cover image. Could you verify this with a tagging tool like `easytag`?
I've fixed the reader issue, this will be resolved in the next update ;)

**Comment by Cleiton-Floss** [comment]
![cdoots-meta](https://user-images.githubusercontent.com/5838486/34358827-b7f429ac-ea31-11e7-9be3-e5320ea6300b.png)

**Comment by geigi** [comment]
Ok found the issue: "gdk-pixbuf-error-quark: Unrecognized image file format (3)"
The image is not recognized by GTK and I cannot fix this. The best solution for you would be to save the image as a fresh jpg or png and add it with easytag or the app of your choice to the files.
Maybe it would be a good idea to let the user know when this happens.

**Comment by da2x** [comment]
Is this issue tracking m4b support? or the image format extraction problem? Most my books are in m4b format, limiting Cozy’s usefulness.

**Comment by geigi** [comment]
This issue was about both but I changed the title to m4b support only

**Comment by mmcdole** [comment]
I had assumed Cozy supported m4b books, but I see now that it does not.  It seems to hang on 'Importing' when I originally tried, so it might be worth throwing up a dialog or something for unsupported format.

Would love to see support for M4B audiobooks!

**Comment by Spearmen** [comment]
> I had assumed Cozy supported m4b books, but I see now that it does not. It seems to hang on 'Importing' when I originally tried, so it might be worth throwing up a dialog or something for unsupported format.
> 
> Would love to see support for M4B audiobooks!

Me To

**Comment by Spearmen** [comment]
I would also love to see Cozy get M4B support it would make it a lot more viable as an Audiobook player.

**Comment by mweinelt** [comment]
Unfortunately mutagen seems to lack support for chapter information in MP4 files, which would be kind of a blocker, wouldn't it? 

https://github.com/quodlibet/mutagen/issues/295

**Comment by geigi** [comment]
Indeed... Maybe there is another python library that is capable of m4b. Otherwise we can always use ffmpeg to get the chapter information.

**Comment by rpgdev** [comment]
For the record, just renaming the files to mp3s works on Fedora KDE... Cozy reads the tags correctly and everything. Don't know if this would be the case for other distros or multimedia backends but if that is the case it would be a matter of just making Cozy simply read the files as is no? 

This is not the most reliable workaround, it's quite messy actually but it helps me avoid doing a lossy transcode for a particular book at the moment.

**Comment by geigi** [comment]
Thanks :) do you have a m4b file with included chapters? That’s the only thing that will probably not work...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mweinelt** [comment]
I wrote a parser for m4b against mutagen, but the maintainers are not really responsive, but it works.

See https://github.com/quodlibet/mutagen/issues/295#issuecomment-478301645

**Comment by rpgdev** [comment]
> Thanks :) do you have a m4b file with included chapters? That’s the only thing that will probably not work...

Not at the moment or not that I'm aware. I don't consume a lot of audiobooks so I'm not sure.

**Comment by geigi** [comment]
Ok thanks @rpgdev 

@mweinelt cool! Is it fully working? Maybe they will include it if we/you create a merge request?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mweinelt** [comment]
It is working, but I don't know in which data structure to expose it in and asked for guidance with regard to that which I never received.

**Comment by pokemontotalwar** [comment]
Darn, I built this with the @mweinelt code added slightly expecting cozy to just support the new code. Is there any way someone could fork mutagen and use that in Cozy, or perhaps they would be more responsive to a pull request? They seem to have most of their pull requests closed, at least. I'm not entirely sure if licensing allows a fork, though, and it would complicate Cozy's distribution.

**Comment by geigi** [comment]
There is some new code that needs to be added to cozy aswell. I haven't had a deep look into this yet, but I think it would be much more desirable to have this functionality in mutagen. Sadly I also didn't receive an answer from them.

**Comment by deadpyxel** [comment]
Any plans for adding m4b support? Or a work around with file conversion that is suggested? I have half a terabyte of audiobooks and this looks like an excellent player for that.

**Comment by geigi** [comment]
Yes I definitely want to add m4b support to cozy. The major issue is that the metadata library `mutagen` I'm using to detect tags from media doesn't support m4b chapters: https://github.com/quodlibet/mutagen/issues/295

Seems like there is currently no progress on this. So I'll have to find another python library that supports m4b chapters, build something myself or build this feature for mutagen. So there is no short term solution for this...

In the meantime you could try this tool: https://github.com/sandreas/m4b-tool

**Comment by mweinelt** [comment]
Poked lazka on IRC today and we have an early review.

https://github.com/quodlibet/mutagen/pull/398

**Comment by mweinelt** [comment]
If somebody has an m4b file with chapters that has a liberal license and could be added to the test suite of mutagen that would be awesome.

**Comment by deadpyxel** [comment]
@mweinelt I commented on the original PR, hopefully that link helps

**Comment by mweinelt** [comment]
> Poked lazka on IRC today and we have an early review.
> 
> [quodlibet/mutagen#398](https://github.com/quodlibet/mutagen/pull/398)

Merged!

**Comment by geigi** [comment]
Awesome, thanks a lot for your work! 😊 I’ll start developing on cozy next week with the mutagen master. When a new version of mutagen is released and cozy’s implementation is ready, we can finally ship this feature.

**Comment by mweinelt** [comment]
Hey @geigi, any progress on your end?

**Comment by geigi** [comment]
@mweinelt hey, yes there has been quite some progress. I've started an almost complete refactoring of cozy as this was the application I learned to programm python with, so naturally there were quite a few problems under the hood. E.g.: there was no abstraction between the database and the UI which made it impossible to simply support audio files containing multiple chapters.

A lot of components are now already refactored so that audio files containing multiple chapters can be properly supported. There are still some parts missing though:

- The book overview
- The titlebar
- The player component
- The importer (currently in progress)

Until everything is finished it might still take me a few months as I'm doing all of this in my free time. But it's getting there and a big part (the database abstraction and writing tests for it) is already done! 🙂

**Comment by geigi** [comment]
Some updates for you: 
Cozy 0.7 is now out which features a completely new importer that is designed to also support multi chapter files!

**Whats next?**
The next feature I'll be working on will be m4b support. Whats missing?
- [ ] Database design to store the chapters
- [ ] A small extension for the importer which reads chapters from m4b files (only if a matching version of mutagen is installed)
- [ ] Rewrite of a lot UI logic to support the new abstraction layer, which supports multiple chapters per file

I think this will be great when it's ready ;) And thanks for your patience :)

**Comment by geigi** [comment]
Hey everyone,

I have an update for you :) I just finished the m4b chapter support!
With the m4b files I own everything seems to work fine and chapters are properly detected. Also the playback, jumping between chapters, etc... seem to work fine.

Before I'll release a new version of Cozy including m4b I want to test this a little bit more. The update will require database migrations (Cozy will do a backup before the migrations but in case of a failure the user would have to restore it manually) which should work without problems but I want to write more tests also regarding the player. 

Next I'll prepare the UI strings so the translators do have enough time to translate everything for the next update.

If anyone is interested in testing with your own set of m4b files lets get in touch.

Thanks for your patience!
