### ISSUE TITLE
Cozy does not remember the size of the last opened window

### ISSUE THREAD

**Issue by apandada1** [geigi/cozy#621]
### Bug/Feature description
Suppose cozy is full-screened or resized. When it is closed and opened again, it does not remember its last size.
This would be an issue with screens in portrait mode (e.g. phones/tablets), where cozy has to be resized every time.

### Steps to reproduce
Open Cozy, and change the window size/full screen it.
Close and reopen Cozy. It does not remember the Window size.

### System Information
- Operating System: Ubuntu and Manjaro (both running XFCE)
- Installation source: PPA and AUR
- Version of cozy: 1.1.0 (also tried latest GitHub source with commit https://github.com/geigi/cozy/commit/6577b79802d039bfe5d67d8e06feea2847f7410d)

**Comment by geigi** [comment]
Thanks for this feature request :)
