### ISSUE TITLE
Submit to elementary OS 6 AppCenter

### ISSUE THREAD

**Issue by hanaral** [geigi/cozy#636]
### Bug/Feature description
Repo description says elementary OS 6 AppCenter support when it releases, so let's see a 6 version too (I'm sure the old icon still looks fine 😉️ )

**Comment by geigi** [comment]
Hey, releasing on the App Center is currently not possible, have a look at: #551

Please use the flatpak from flathub :)

**Comment by rdbende** [comment]
Since we are using GNOME's design guidelines now, I don't think it would be possible to submit Cozy to elementary's App Center. elementary OS users can use Sideload to install Flatpak apps from Flathub.
