### ISSUE TITLE
Huge grid gaps

### ISSUE THREAD

**Issue by bertob** [geigi/cozy#637]
The current grid layout looks pretty broken at many window sizes, because the gaps between cards are huge:

![cozy-grid2](https://user-images.githubusercontent.com/1908896/130461951-5707710b-c9f6-463e-97d7-83bf8c979fb4.png)

Ideally the spacing between and around columns should be fixed (probably 12px), and their size should dynamically change to fill the entire width given the current number of cards that can fit with the minimum card size.

I've also noticed that some cards are wider than the rest (I assume due to the title string?), which probably contributes to the column gap issue.

### System Information
- Operating System: Fedora 34
- Installation source: Flathub
- Version of cozy: 1.1.2

**Comment by geigi** [comment]
FYI: This will be fixed with GTK4 as it supports this natively.
