### ISSUE TITLE
No Album covers being imported

### ISSUE THREAD

**Issue by kachapman** [geigi/cozy#651]
### System Information
- Operating System: Pop!IOS 21.04
- Installation source: Pop Store (flatpack)
- Version of cozy: 1.1.2

**Comment by geigi** [comment]
Hey, I can't help you without the additional information I requested from you. Otherwise I need to close this issue unfortunately...

**Comment by kachapman** [comment]
I'm sure that your fix works, I just stopped using the app. Thanks for checking in.
