### ISSUE TITLE
roadmap for cozy

### ISSUE THREAD

**Issue by cstackpole** [geigi/cozy#656]
### Feature description

Is there a roadmap available for users to see?

The real reason why I'm asking is because for various reasons my digital audiobook collection has grown quite significantly over the last year and I'm trying to manage them. I've started tagging my audiobooks with lots of useful information but I do not have a good way to mange it all. To be honest, what I want is an audiobook form of https://calibre-ebook.com/ (yes, there is a 3rd-party plugin that is very old and unmaintained - it didn't work for me and neither does zipping all my audio files) .

I added the book description and some tags to the comment section of my tag, but cozy doesn't recognize that (it seems). Especially for the audio books that I've not yet listened to, getting a description would be nice to fit a book to my mood (esp if I haven't read it or it has been a really long time).

I'd like to sort based on if it is fiction or non-fiction, action, adventure, children, adult, ect. 

I'd like to be able to leave personal ratings. For both the book and the narrator. Why? Well I've got books I loathed from authors I love - it happens :-) . I've also bought an audiobook for a book series I really like and the narrator is /terrible/ (and the audio painfully soft) so I bought a different narration of the same audiobook. I've also got an audiobook on CD that's well done, but I also have the https://www.graphicaudio.net/ version and that is a whole big production - not a simple narration. I'd like to keep, rate, and note each accordingly for when I go back through my audiobooks in the future.

I've also been using the URL tag a lot. In some cases I link to the authors official webpage for standalone books. But I've got a few audiobooks where I picked up the first in the series to see if I liked it enough to get other books. In that case, I've been linking to the store URL (example, the graphicaudio.net page). I think that information would be very useful to display in the UI.

On the topic of series, I would like to have better management of series so I can sort between publication date or story-time-line (eg:The Chronicles of Narnia publication vs reading order is a well known debate).

And there are other features too, but that's enough rambling for now to make my point. :-)

That's a really long winded way of saying that if there was a rough roadmap available it would be easier for me to line up the things I'm looking for and know if Cozy is the project I should pursue or if I'm asking for things that no one else is and should keep looking. There is the obvious "these are features I'm looking for", but my real request for the moment is to know if these requests align with the hopes/goals of the project long term or not. :-)

### System Information
- Operating System: Lubuntu 21.04
- Installation source: PPA
- Version of cozy: 1.1.2

Thanks to everyone who is contributing to this project, by the way. I've only started looking at audiobook management software and realizing how challenging it must be. Kudos to those making it happen!

**Comment by sophie-h** [comment]
@geigi What do you think about finding an additional maintainer and new contributors? The Circle team would be willing to help post and ask around the community. It would be great if there were a way to keep the project alive. See also #760

**Comment by geigi** [comment]
@sophie-h Thanks for reaching out! I think this is a good idea. Sadly I currently don't have the time that this project and the users deserve...
What information would be necessary for posting in the community?
As the project is already ~5 years old and the codebase is not the smallest I think it might be a little bit overwhelming for a beginner so would be awesome to find somebody with some experience in Python and GTK3/4 as I currently cannot provide lots of guidance for a beginner. Things can get a little complicated quite quickly when dealing with many different audio files and tagging.

**Comment by sophie-h** [comment]
Hey, thanks for all your work so far.

I would suggest to post the following text and see what happens. Let me know what you think :)

---

The popular audiobook player [Cozy](https://apps.gnome.org/app/com.github.geigi.cozy/) and GNOME Circle app needs your help! Cozy has over 50,000 downloads on Flathub alone and is packaged in popular distributions like Fedora. 

Unfortunately, the original maintainer Julian Geywitz currently doesn't have time to maintain the project. Therefore, the project seeks new maintainers, ideally experienced with Python, porting projects to GTK 4, and handling audio. Maintaining this project is certainly not for beginners, and there are no resources to onboard a new maintainer. One of the pending tasks is porting the app to GTK 4.

If you are interested you can comment on the [Roadmap](https://github.com/geigi/cozy/issues/656) issue or coordinate with others in #circle:gnome.org.

**Comment by Corsseir** [comment]
@geigi Did you consider just selling this app to make it profitable for you? Me and many others I believe would pay for Cozy with pleasure.

**Comment by rdbende** [comment]
Here's our roadmap for v2.0.0: https://github.com/geigi/cozy/milestone/7.
It includes #802 into which I've incorporated popular requests, and also some of your points. Metadata editing is not planned, but it would be great to display URLs and descriptions, and also have more sorting/filtering options based on the metadata.
I think this issue can now be closed.
