### ISSUE TITLE
Audio Book Library path cannot handle symlinks (flatpak version)

### ISSUE THREAD

**Issue by feinstaub** [geigi/cozy#66]
My Audio Book Library contains symlinks. It is currently not possible to select such a path. Is is possible to still listen to a single audio book? For the flatpack version only. openSUSE Tumbleweed packaged version works.

**Comment by geigi** [comment]
I think this is a restriction to flatpak because symlink would allow breaking out of the sandbox flatpak provides. I don't know if I can change this behaviour but I'll have a look.

**Comment by geigi** [comment]
This should now be possible as the flatpak allows access to the whole filesystem now :)
