### ISSUE TITLE
Cozy fails to launch :(

### ISSUE THREAD

**Issue by susan3333333** [geigi/cozy#667]
### Bug/Feature description
When launched nothing happens, launch thru terminal get this:
```
Traceback (most recent call last):
  File "/usr/bin/com.github.geigi.cozy", line 130, in <module>
    from cozy.application import Application
  File "/usr/lib/python3.8/site-packages/cozy/application.py", line 15, in <module>
    from cozy.ui.widgets.seek_bar import SeekBar
  File "/usr/lib/python3.8/site-packages/cozy/ui/widgets/seek_bar.py", line 10, in <module>
    @Gtk.Template.from_resource('/com/github/geigi/cozy/seek_bar.ui')
  File "/usr/lib64/python3.8/site-packages/gi/module.py", line 123, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Gtk' object has no attribute 'Template'
```

### Steps to reproduce
Install cozy and launch
### System Information
- Operating System:  OpenSuse Tumbleweed
- Installation source: Default repo
- Version of cozy: 1.1.2-1.2

**Comment by geigi** [comment]
Sorry for the late reply... Seems like the OpenSuse build is broken. I currently don't have a OpenSuse setup so it will take some time to fix this sorry... I suggest to use the [Flatpak](https://flathub.org/apps/details/com.github.geigi.cozy) for now

**Comment by jubalh** [comment]
cozy 1.1.2 works fine for me on openSUSE Tumblweed.
I don't know much about Python, but I know about packaging. If you need help just ping me.

**Comment by geigi** [comment]
@susan3333333 are you using Gnome?

**Comment by ReaderGuy42** [comment]
@geigi I'm on Mint 20.3 and also cannot launch. I've tried installing via PPA which didn't work, and also tried the Software Manager of Mint that let me install the program, but will not launch it. Any ideas?

**Comment by geigi** [comment]
I'm closing this bug as it seems to work fine for other users and no response from the issue creator is present.
