### ISSUE TITLE
WARNING:importer:Track  ...mp3 is no valid MP3 file. Skipping...

### ISSUE THREAD

**Issue by feinstaub** [geigi/cozy#67]
How does cozy determine if an mp3 file is valid? The given mp3 files are old but music players can play them.

**Comment by geigi** [comment]
I think the library I'm using for metadata only supports ID3v2 tags. Can you find out what version of ID3 tags this file is using?

**Comment by geigi** [comment]
I'm closing this now because I don't have enough information to fix the issue. Feel free to reopen if you can provide me some more infos about your mp3 files.

**Comment by geigi** [comment]
Cozy 0.7 is out with a completely new importer! This should work with every mp3 file you can play back with any other media player on your system.
