### ISSUE TITLE
Visual feedback bug on first launch

### ISSUE THREAD

**Issue by YellowEyeFrog** [geigi/cozy#671]
### Bug/Feature description

Visual bug after welcome screen where the user feedback option looks to be detailed error reporting in preferences no matter the option chosen in the welcome screen. 

My assumption is that the option gets saved but the feedback option in preferences is already loaded in and not synced with the one in the welcome screen.

### Steps to reproduce

Launch a fresh install of Cozy and change the user feedback option to disabled in the welcome screen.

Open preferences and then go to feedback and it will be "set" to detailed error reporting.

### System Information
- Operating System: Fedora Linux 35 (Workstation Edition)
- Installation source: Flathub (Flatpak)
- Version of cozy: 1.1.2

**Comment by geigi** [comment]
Thanks for reporting :) I'll have a look into it.
