### ISSUE TITLE
Author and Reader information are exchanged

### ISSUE THREAD

**Issue by srossan** [geigi/cozy#688]
### Bug/Feature description
While using the app, I can see the audiobooks authors in the readers tab, and I can see the readers in the authors one.
### Steps to reproduce
Launch the app, and click on the various tabs
### System Information
- Operating System:  Linux Mint 20.2
- Installation source: Software Manager
- Version of cozy: 1.1.3

**Comment by geigi** [comment]
Hey, have a look at the settings in Cozy's app menu. There is a switch to change this behavior :)

**Comment by srossan** [comment]
Yep, it did the trick.
Thanks for the quick response.

Happy new year!

-Stephane

**Comment by geigi** [comment]
No worries, happy new year :)
