### ISSUE TITLE
Won't launch (at all) on Mint 20.3

### ISSUE THREAD

**Issue by ReaderGuy42** [geigi/cozy#692]
### Bug/Feature description
After installing via Mint's Software Manager Cozy shows up in the software list but won't launch at all. I've also tried the Ubuntu PPA, and Flatpak. Flatpak let's me download the .flatpakref file but then opens up a different Software Manager than the normal one and just tells me it's not available.

Is Cozy just not compatible with Mint? 

### Steps to reproduce
Install via Software Manager/PPA/Flatpak -> nothing happens

### System Information
- Operating System: Linux Mint 20.3
- Installation source: Software Manager/PPA/Flatpak
- Version of cozy: 1.2

Thanks :)

**Comment by geigi** [comment]
Hey, Cozy should work on Linux Mint. Could you post Cozy's log file here? 
```

~/.var/app/com.github.geigi.cozy/data/cozy/cozy.log

```

**Comment by ReaderGuy42** [comment]
There's no file with that name in that folder; no log files at least (see screenshot).

![image](https://user-images.githubusercontent.com/71895400/149622366-867a72f3-ae5f-4d3f-910b-26bfeb784c01.png)

**Comment by geigi** [comment]
Could you then try to start cozy from the terminal and post the output here?

```
flatpak run com.github.geigi.cozy
```

The version of Cozy you see in the software manager is the flatpak version :)

**Comment by ReaderGuy42** [comment]
`error: While opening repository /home/ReaderGuy42/.local/share/flatpak/repo: opening repo: opendir(objects): No such file or directory
`

**Comment by geigi** [comment]
Thanks :) it looks like there is a problem with your system. This error message has nothing to do with cozy itself, it's an error message from flatpak. I've not seen this message before and don't know how to help with that... one thing you could try where I could help with is installing from the ppa. Please launch cozy from the terminal with
```
com.github.geigi.cozy
```
And post the output here :)

**Comment by ReaderGuy42** [comment]
I get this:
` com.github.geigi.cozy: command not found
`
So I try following these instructions here: https://askubuntu.com/questions/1356747/how-to-install-cozy-audiobook-player-in-ubuntu-20-04-without-flatpak/1356751#1356751

But there I don't get very far since for `sudo apt-get install cozy` it tells me 
```sudo apt-get install cozy
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package cozy
```

Thanks for your help!!

**Comment by geigi** [comment]
If apt can't find the package the PPA is not properly added. One of the previous commands must have failed. Could you post the output of those commands as well:
```
sudo add-apt-repository ppa:cozy-team/cozy
sudo apt-get update
```
Otherwise, maybe @apandada1 has an idea?

**Comment by apandada1** [comment]
The PPA does not host packages for Ubuntu 20.04 (consequently on Mint 20), as the dependencies peewee and mutagen are not available in that version of Ubuntu. (The answer in Ask Ubuntu involved downloading updated versions of those packages from Ubuntu 20.10 repositories, but those packages are not anymore available as 20.10 is now obsolete. I will contact the person who wrote the answer in Ask Ubuntu, and we will see if something can be done about that.)

In Mint 20, please use flatpak instead. Instead of using Mint's software manager, enter the following commands to install Cozy.

```
flatpak install flathub com.github.geigi.cozy
flatpak run com.github.geigi.cozy
```
If cozy still does not run, please post the output of `flatpak run com.github.geigi.cozy`.

**Comment by ReaderGuy42** [comment]
For the first line I get this:
```You are about to add the following PPA:
 Cozy is a modern audiobook player for GNU/Linux.
Source: https://github.com/geigi/cozy
Website: https://cozy.sh/

This PPA hosts packages for Ubuntu 20.10 and above.

For Ubuntu 20.04: See https://askubuntu.com/a/1356751/124466 for instructions. Alternatively, use the flatpak.

Somehow Launchpad does not show the signing key in this PPA.
The key is 

pub   rsa4096 2021-06-05 [SC]
      1694 6AB2 56F1 A088 4B5C  E392 5DD7 991B 3AA5 9025
uid           [ unknown] Launchpad PPA for Cozy PPA maintainers

See https://askubuntu.com/q/1356784/124466 for more details
 More info: https://launchpad.net/~cozy-team/+archive/ubuntu/cozy
Press Enter to continue or Ctrl+C to cancel
Executing: /tmp/apt-key-gpghome.8fR2vytIqi/gpg.1.sh --keyserver hkps://keyserver.ubuntu.com:443 --recv-keys 16946AB256F1A0884B5CE3925DD7991B3AA59025
gpg: key 5DD7991B3AA59025: "Launchpad PPA for Cozy PPA maintainers" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
```

And then for the update thing I get a bunch of lines, including the PPA for Cozy (I don't think the other lines are relevant?):
```
Hit:7 http://archive.canonical.com/ubuntu focal InRelease                      
Hit:8 http://ppa.launchpad.net/cozy-team/cozy/ubuntu focal InRelease           
Hit:9 http://ppa.launchpad.net/flatpak/stable/ubuntu focal InRelease           
Hit:10 https://screenrec.com/download/ubuntu stable InRelease  
```

**Comment by ReaderGuy42** [comment]
@apandada1 Ok, thank you! For your first command I get this:
```sudo flatpak install flathub com.github.geigi.cozy
Looking for matches…
Remote ‘flathub’ found in multiple installations:

   1) system
   2) user

Which do you want to use (0 to abort)? [0-2]: 1
Skipping: com.github.geigi.cozy/x86_64/stable is already installed
```
I selected "System" and then it aborts; so I try again and select "User" and get this:

```
Which do you want to use (0 to abort)? [0-2]: 2

com.github.geigi.cozy permissions:
    ipc                 network               fallback-x11    pulseaudio
    wayland             x11                   dri             file access [1]
    dbus access [2]     bus ownership [3]

    [1] host, xdg-run/gvfs, xdg-run/gvfsd
    [2] org.freedesktop.Notifications, org.gtk.vfs.*
    [3] org.mpris.MediaPlayer2.Cozy


        ID                           Branch Op Remote  Download
 1. [✓] com.github.geigi.cozy.Locale stable i  flathub 15,3 kB / 429,4 kB
 2. [✓] com.github.geigi.cozy        stable i  flathub  2,9 MB / 4,2 MB

Installation complete.
```

However, when I then try and run it with `flatpak run com.github.geigi.cozy`
I get this:
```flatpak run com.github.geigi.cozy
error: While opening repository /home/ReaderGuy42/.local/share/flatpak/repo: opening repo: opendir(objects): No such file or directory
```

**Comment by apandada1** [comment]
It says `Skipping: com.github.geigi.cozy/x86_64/stable is already installed`. So maybe remove it and try to reinstall.

```
flatpak remove com.github.geigi.cozy **(also try this once again with sudo)**
flatpak install com.github.geigi.cozy
```

**Comment by ReaderGuy42** [comment]
Ok, so far so good:

```
sudo flatpak remove com.github.geigi.cozy
Similar installed refs found for ‘com.github.geigi.cozy’:

   1) app/com.github.geigi.cozy/x86_64/stable (system)
   2) app/com.github.geigi.cozy/x86_64/stable (user)
   3) All of the above

Which do you want to use (0 to abort)? [0-3]: 3


        ID                                   Branch         Op
 1. [-] com.github.geigi.cozy                stable         r
 2. [-] com.github.geigi.cozy.Locale         stable         r

Uninstall complete.


        ID                                   Branch         Op
 1. [-] com.github.geigi.cozy                stable         r
 2. [-] com.github.geigi.cozy.Locale         stable         r

Uninstall complete.
```
Then I reinstall it:
```
sudo flatpak install com.github.geigi.cozy
Looking for matches…
Remotes found with refs similar to ‘com.github.geigi.cozy’:

   1) ‘flathub’ (system)
   2) ‘flathub’ (user)

Which do you want to use (0 to abort)? [0-2]: 1

com.github.geigi.cozy permissions:
    ipc                 network               fallback-x11    pulseaudio
    wayland             x11                   dri             file access [1]
    dbus access [2]     bus ownership [3]

    [1] host, xdg-run/gvfs, xdg-run/gvfsd
    [2] org.freedesktop.Notifications, org.gtk.vfs.*
    [3] org.mpris.MediaPlayer2.Cozy


        ID                                   Branch Op Remote  Download
 1. [✓] com.github.geigi.cozy.Locale         stable i  flathub 27,2 kB / 429,4 kB
 2. [✓] org.freedesktop.Platform.GL.default  21.08  u  flathub 59,3 MB / 131,2 MB
 3. [✓] org.freedesktop.Platform.VAAPI.Intel 21.08  u  flathub  9,9 MB / 11,7 MB
 4. [✓] org.gtk.Gtk3theme.Mint-Y-Aqua        3.22   u  flathub 16,7 kB / 96,6 kB
 5. [✓] org.gtk.Gtk3theme.Mint-Y-Blue        3.22   u  flathub 16,7 kB / 96,5 kB
 6. [✓] org.gtk.Gtk3theme.Mint-Y-Dark-Aqua   3.22   u  flathub 15,5 kB / 96,5 kB
 7. [✓] org.gtk.Gtk3theme.Mint-Y-Dark-Blue   3.22   u  flathub 15,5 kB / 96,4 kB
 8. [✓] org.gtk.Gtk3theme.Mint-Y-Dark        3.22   u  flathub 15,6 kB / 96,4 kB
 9. [✓] org.gtk.Gtk3theme.Mint-Y             3.22   u  flathub 16,6 kB / 96,5 kB
10. [✓] com.github.geigi.cozy                stable i  flathub  2,9 MB / 4,2 MB

Changes complete.
```
However, when I then try running it, I get the same error:
```
flatpak run com.github.geigi.cozy
error: While opening repository /home/ReaderGuy42/.local/share/flatpak/repo: opening repo: opendir(objects): No such file or directory
```
Any other ideas?

**Comment by apandada1** [comment]
Let me try this in my Mint VM. I am using Cozy from flatpak in KDE Neon (also based on Ubuntu 20.04), where it works fine.

**Comment by ReaderGuy42** [comment]
Ok, thank you for your help!

**Comment by apandada1** [comment]
See https://github.com/flatpak/flatpak/issues/3585#issuecomment-621545087

**Comment by geigi** [comment]
I found an issue in flatpaks repository where somebody has a similar issue, maybe one of the fixes mentioned there may help you: https://github.com/flatpak/flatpak/issues/3585

**Comment by ReaderGuy42** [comment]
Awesome, thank you both, I removed the repo as it was advised in the other thread, then reinstalled that and then Cozy, and now it works!! Thank you!
