### ISSUE TITLE
Way to have Cozy get Author name and Book title from Folders, not metadata?

### ISSUE THREAD

**Issue by ReaderGuy42** [geigi/cozy#694]
### Feature description
I really like Cozy, and it already helped me as it told me that some files were corrupted, which is cool. However, after finally getting it installed (thanks for that, guys!!) I'm now having issues with the metadata. Some of the books that came from Audible work fine, but others that I found on Youtube don't have metadata and I can't get Cozy to work with the tags/metadata I've tried adding with EasyTags or Piccard.

Is there a way to have Cozy recognize the author's name and book title from the folders that the files are in?

### System Information
- Operating System: Linux Mint
- Installation source: Flathub
- Version of cozy: 1.2.0

**Comment by geigi** [comment]
Hey :) 
This feature has already been requested some time ago. But after thinking about it I decided that this won't be implemented. You can read the reasoning here: #612 and #649

Im using Easytag myself and it works quite well for me. The following tags will get recognized by Cozy:
 Album Name Artist (the Reader of the Book) Composer (the Author of the book) Track Name (Chapter Name) An album cover if you like

Composer and artist usage can be swapped in settings though.

**Comment by ReaderGuy42** [comment]
Ah cool, I didn't know the ting about Composer, thanks, I'll try that :)

**Comment by ReaderGuy42** [comment]
Just another quick question: When I edit the Composer, Cozy sees that, but it seems that it recognizes the first and last name of the author as two separate authors instead of being part of the same. So it's seeing "Smith, Joe" as "Smith" and "Joe" instead of one. I also tried not using the comma but it had the same result. How do I have Smith, Joe as a single author? Thanks :)

**Comment by geigi** [comment]
Separating names with "," will indeed be detected as separate authors or readers. If you remove the "," in easytag and save the files, a refresh in cozy should detect this and it will be detected as a single name, e.g. "Joe Smith"

**Comment by geigi** [comment]
Maybe disabling this Automation deserves a setting tough

**Comment by ReaderGuy42** [comment]
Ok, that would be cool, just because that's how I (and maybe others) have it organized anyways. Thanks :) Should I close this issue or leave it open for the Comma thing?

**Comment by geigi** [comment]
Let's open a separate issue for this feature :)
