### ISSUE TITLE
Squares instead of text

### ISSUE THREAD

**Issue by danlock10y** [geigi/cozy#695]
### Bug/Feature description
Installed using flatpak on crostini, all text just coming up as boxes
### System Information
- Operating System: Crostini
- Installation source: Flatpak
- Version of cozy: 1.2.0
![Screenshot 2022-01-19 05 14 26](https://user-images.githubusercontent.com/60039199/150069037-a7736ac3-fa4d-4804-b912-387c4c1ae695.png)

**Comment by geigi** [comment]
Hi, this is a problem with Crostini. There seems to be a broken font configuration. This has nothing to do with Cozy though. I suggest you seek help from Crostini or other people using it in combination with GTK flatpak apps.
