### ISSUE TITLE
Unable to edit metadata of audio book files

### ISSUE THREAD

**Issue by peter099** [geigi/cozy#703]
### Bug/Feature description
I am using EasyTAG to change the authors and titles of some of my audio books. I tried tag fields like title, artist, album, album artist but Cozy do not recognizes the new edits.  

### Steps to reproduce
Open EasyTAG, edit tag field of audio book mp3 file, click Scan Library in Cozy, nothing is changed in audio book title or author name. 

### System Information
- Operating System:  MX Linux
- Installation source: Flatpak
- Version of cozy:  1.2.0

**Comment by geigi** [comment]
Another question: Have you imported the files via Drag&Drop? If you did, they are copied to your default audiobooks folder (have a look at the preferences). Altering the original files won't be detected by Cozy then.

**Comment by peter099** [comment]
I fixed the tags and now they are showing in Cozy, but had problems removing audiobooks, that are deleted, from the library - the library scan won't remove it. I had to remove it from the context menu. I added the audiobooks from Preferences > Storage. 

Suggestion: it will be great if there are options to filter books by genre and series.

This is a great audiobook player, by the way.

**Comment by geigi** [comment]
Ok, good to know you could fix it :) there will be a small help in cozy in the future that tells you, how to tag correctly.

Regarding your suggestion on deleting books: cozy was implemented in the past how you described it. But it had some problems: if files are temporarily unavailable or moved by mistake, you could loose your progress when issuing a rescan. Therefor I decided to implement it how it is today. But I understand that it is a bit inconvenient when you want to remove multiple books. Maybe there will be a better solution in the future.

As the issue regarding the tags is resolved, I'll close this one.
