### ISSUE TITLE
Can you run all cozy commands from a terminal?

### ISSUE THREAD

**Issue by travisengh** [geigi/cozy#705]
I am looking to integrate Cozy with Mycroft AI. I am wondering if there is a way to run Cozy from the terminal, such as a way to find your audiobook, pause, stop, play, bookmark, fast forward or rewind 10 - 30 seconds, and so on.  Any information would be great! Thank you in advance!

**Comment by geigi** [comment]
Hey, using the Cozy from the commandline is currently not possible. But you can control Cozy using the desktop integration (MPRIS). I'm sure there is a way to control MPRIS from the commandline. A quick search found this: https://github.com/altdesktop/playerctl
