### ISSUE TITLE
Detection failure for audiobooks in folders 

### ISSUE THREAD

**Issue by GestaltEngine** [geigi/cozy#711]
### Bug/Feature description
The files related to one audiobook (stored in one folder) are interpreted as two different audiobooks. 

### Steps to reproduce
Have a folder with two subfolders each containing an audiobook broken up into multiple mp3 files. Here's the output of ls -R from said folder in my case:

> .:
> 'Left Hand of Darkness'  'The City and The City'
> 
> './Left Hand of Darkness':
> 00_00_00.mp3  01_04_01.mp3  01_08_01.mp3  01_11_02.mp3  01_15_03.mp3  01_19_01.mp3
> 01_01_01.mp3  01_05_01.mp3  01_08_02.mp3  01_11_03.mp3  01_15_04.mp3  01_19_02.mp3
> 01_01_02.mp3  01_05_02.mp3  01_08_03.mp3  01_11_04.mp3  01_15_05.mp3  01_19_03.mp3
> 01_01_03.mp3  01_05_03.mp3  01_08_04.mp3  01_12_01.mp3  01_15_06.mp3  01_19_04.mp3
> 01_01_04.mp3  01_05_04.mp3  01_08_05.mp3  01_13_01.mp3  01_16_01.mp3  01_19_05.mp3
> 01_01_05.mp3  01_05_05.mp3  01_08_06.mp3  01_13_02.mp3  01_16_02.mp3  01_19_06.mp3
> 01_01_06.mp3  01_05_06.mp3  01_08_07.mp3  01_13_03.mp3  01_16_03.mp3  01_20_01.mp3
> 01_01_07.mp3  01_05_07.mp3  01_09_01.mp3  01_13_04.mp3  01_16_04.mp3  01_20_02.mp3
> 01_01_08.mp3  01_05_08.mp3  01_09_02.mp3  01_13_05.mp3  01_16_05.mp3  01_20_03.mp3
> 01_02_01.mp3  01_06_01.mp3  01_10_01.mp3  01_14_01.mp3  01_17_01.mp3  01_20_04.mp3
> 01_02_02.mp3  01_06_02.mp3  01_10_02.mp3  01_14_02.mp3  01_18_01.mp3  01_20_05.mp3
> 01_03_01.mp3  01_06_03.mp3  01_10_03.mp3  01_14_03.mp3  01_18_02.mp3  1000366734.jpg
> 01_03_02.mp3  01_06_04.mp3  01_10_04.mp3  01_14_04.mp3  01_18_03.mp3
> 01_03_03.mp3  01_06_05.mp3  01_10_05.mp3  01_14_05.mp3  01_18_04.mp3
> 01_03_04.mp3  01_07_01.mp3  01_10_06.mp3  01_15_01.mp3  01_18_05.mp3
> 01_03_05.mp3  01_07_02.mp3  01_11_01.mp3  01_15_02.mp3  01_18_06.mp3
> 
> './The City and The City':
> 01_01.mp3  01_05.mp3  01_09.mp3  02_13.mp3  02_17.mp3  02_21.mp3  03_25.mp3  04_01.mp3
> 01_02.mp3  01_06.mp3  01_10.mp3  02_14.mp3  02_18.mp3  02_22.mp3  03_26.mp3
> 01_03.mp3  01_07.mp3  01_11.mp3  02_15.mp3  02_19.mp3  03_23.mp3  03_27.mp3
> 01_04.mp3  01_08.mp3  02_12.mp3  02_16.mp3  02_20.mp3  03_24.mp3  03_28.mp3

'Left Hand of Darkness' was interpreted as two books and 'The City and The City' was interpreted correctly, albeit when I tried add yet another book, 'Left Hand of Darkness' was interpreted correctly and 'The City and The City' was interpreted as two books. 

Don't know if it's an expected behaviour, but I suspect it isn't.

Suggestion: 

### System Information
- Operating System: Linux Pop!_OS 5.16.15 kernel
- Installation source: flatpak
- Version of cozy: 1.2.0

**Comment by geigi** [comment]
Hi,
are your mp3 files tagged?

- Album Name (Book name)
-  Artist (the Reader of the Book)
- Composer (the Author of the book)
-  Track Name (Chapter Name)
- An album cover if you like

**Comment by GestaltEngine** [comment]
Everything except "Composer" is filled in.

**Comment by geigi** [comment]
Ok, could you verify that the book name is exactly the same (capitalization and whitespace) in all files of the affected book? You can also use a tool like `mediainfo` for this

**Comment by geigi** [comment]
I'm closing this due to the lack of a response
