### ISSUE TITLE
Pacstall

### ISSUE THREAD

**Issue by trymeouteh** [geigi/cozy#717]
Please add this app into the pacstall repository. Pacstall is the AUR for Ubuntu which will allow Ubuntu users to easily install the app and receive updates very shortly after an update is released.

https://pacstall.dev/

**Comment by geigi** [comment]
Hey, the main distribution way of Cozy is via Flatpak. I don't have enough time to support other ways of distributing Cozy. All other package managers are handled by other contributors.
