### ISSUE TITLE
Can't able to play audio books in pop_OS

### ISSUE THREAD

**Issue by AbhishekGowda28** [geigi/cozy#733]
### Bug/Feature description
Cozy isn't able to play audio books in Pop OS
### Steps to reproduce
- Download & Install Cozy from Pop!_Shop
- Open the app
- Add audio book by Drag & Drop

### System Information
- Operating System: 
```bash
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```
- Installation source: Pop_Shop
- Version of cozy: 1.2.1

**Comment by geigi** [comment]
I use a Pop!_OS 22.04 machine myself but it works fine. Does this issue still exist for you?
