### ISSUE TITLE
GNOME 41 runtime no longer supported

### ISSUE THREAD

**Issue by hkockerbeck** [geigi/cozy#741]
### Bug/Feature description
When I update my Flatpak packages, I get a warning that the GNOME 41 runtime is no longer supported, and the app using this runtime is Cozy:

```
Info: runtime org.gnome.Platform branch 41 is end-of-life, with reason:
   The GNOME 41 runtime is no longer supported as of September 17, 2022. Please ask your application developer to migrate to a supported platform.
Info: applications using this runtime:
   com.github.geigi.cozy
```

### Steps to reproduce

Update Flatpak packages with `flatpak update`

### System Information
- Operating System: Ubuntu 22.04 LTS
- Installation source: Flatpak
- Version of cozy: 1.2.1

**Comment by harryfine** [comment]
I have the same issue.  I removed Cozy as the runtime org.gnome.Platform branch 41 is end of life and I don't want any security issues.  Will this be updated?

**Comment by geigi** [comment]
The runtime is now updated :) Sorry for the late response
