### ISSUE TITLE
Request: Require a confirmation when adding a folder to the cozy library before cozy indexes the folder

### ISSUE THREAD

**Issue by meixiexun** [geigi/cozy#744]
### Bug/Feature description
If you add a folder to Prefs > Storage Location, Cozy begins indexing the folder immediately upon selection meaning that if a user misclicks and/or accidentally adds the wrong folder, user won't have a chance to correct that before Cozy adds the files to the library. 

### Steps to reproduce
1. Hamburger Menu
2. Preferences > Storage
4. Add folder
5. Job starts immediately

### System Information
- Operating System: Pop_OS 22.04
- Installation source: Flathub
- Version of cozy: 1.2.1

**Comment by rdbende** [comment]
With 1.3.0 you always get a folder selection dialog. This way it's clear, that something will happen, when you click "Select" on the dialog, and I would expected that it imports the files immediately, without clicking an additional button.
