### ISSUE TITLE
Problem adjusting playback rate (float precision problem)

### ISSUE THREAD

**Issue by da2x** [geigi/cozy#75]
It’s difficult to adjust the playback rate widget using the keyboard, and even harder using the mouse. I believe this screen recording provides the best documentation I can provide: [screen_recording.vp9.webm.zip](https://github.com/geigi/cozy/files/1628572/screen_recording.vp9.webm.zip)

Version 0.4.7 (as distributed on Flathub), Fedora 27

**Comment by da2x** [comment]
This was of course fixed yesterday in commit 90a21a3fdf1adff562500ca52d3303d5fcd23c42. I hope to see the fix released on Flathub soon, Sorry for wasting your time.

**Comment by geigi** [comment]
I've released a small update on Flathub that fixed the issue, enjoy ;)
