### ISSUE TITLE
Cozy Database is corrupted

### ISSUE THREAD

**Issue by Li-Gnux** [geigi/cozy#751]
**### Old database information is still stored somewhere, even though I specified a brand new and almost empty folder as the location for my audio books. Still all audiobooks from the old folder location are displayed. The old folder location still exists because I need it for another application. OpenAudible. I originally wanted to save all my audiobooks that I have stored via open-audible locally on my computer in a certain folder (default was from open-audible) with cozy. To do this, I specified the same folder in cozy that I use in open-audible. the folder is called "books" and is a subfolder in the open-audible folder. When I wanted to change the folder in Cozy later, cozy has indeed shown that I have now set a new audiobook folder as default - but despite turning on and off Cozy, even the uninstallation of Cozy had no success remained in Cozy all my old audiobooks (were displayed) - just those from the Books folder. Playback does not work because cozy reports that the audio book in the said folder can not be found.**

How can I delete the Cozy flatpack database 100% and then let Cozy create the database again. Only about the preferences I do not come further?

**### see above or. 1.) Install Open-Audible (I have 250 Audiobooks there) stored at folder books. Set in cozy the Audiobookfolder also to books. Then scan libary. After the audiobook database is up to date (took a while) I tried to specify another folder in the home directory as the audiobook source. This worked according to the default settings, there was only this - but - it was still all audiobooks from the -books- folder included. Even renaming the books folder did not work. With Flatpack there is no cozyfolder in .local ...**

### System Information
- Operating System: Linux Mint 21
- Installation source: Flatpack
- Version of cozy: 1.2.1
Thanks a lot....

**Comment by geigi** [comment]
Sorry for the late answer...
You can delete Cozy's db here:
`~/.var/app/com.github.geigi.cozy/data/cozy`

**Comment by rdbende** [comment]
To delete individual books, you can right click on them and choose "Remove"
