### ISSUE TITLE
Dark mode switch in preferences does not properly detect system dark mode

### ISSUE THREAD

**Issue by kekonn** [geigi/cozy#755]
### Bug/Feature description

My system is in dark mode by default, but the switch was off. I would expect the switch to be on, to reflect my system style (as a default value, when no override is given).

### Steps to reproduce

1. Get a clean install of cozy (no preferences set)
2. Put system in dark mode
3. Open the settings
4. Dark mode will be switched off. To enable light mode, you have to turn dark mode on and off again.

### System Information
- Operating System: Arch
- Installation source: Gnome software center (flatpak)
- Version of cozy: 1.2.1

**Comment by kekonn** [comment]
I did some research about how to detect this: 
check gsettings/dconf /org/gnome/desktop/interface/color-scheme to see. Should be either default, prefer-dark or prefer-light. If it is prefer-dark, set the default value of the switch to on. I'll see if I can make a pull request sometime this week.

**Comment by in4matix** [comment]
My system is in light mode, but I prefer some Applications in dark mode. When launching Cozy it opens in light mode, but the setting for dark mode is on. If I toggle off and on then dark mode activates, but is not persistent between launches. Thank you for this amazing Application. 

OS: Ubuntu 22.04.02
Source: Snap / Flatpak
Cozy Version 1.2.1
