### ISSUE TITLE
Flatpak crashes at startup

### ISSUE THREAD

**Issue by bkauler** [geigi/cozy#771]
Crashes when start:

```
> cozy
ldconfig: Can't create temporary cache file /run/ld-so-cache-dir/ff29aa50592b572566e77a133d8dfcb29b1f191302ebb1fb66ef6a3faf68ce5e.IFgSRh~: Required key not available
error: ldconfig failed, exit status 256
```

'cozy' is a script:

```
#!/bin/sh
export $(dbus-launch) #if app needs to access dbus.
export XDG_DATA_DIRS=/mnt/wkg/flatpak/exports/share:/home/cozy/.local/share/flatpak/exports/share:/usr/share:/usr/local/share #need to fool flatpak.
flatpak run --filesystem=host --socket=system-bus com.github.geigi.cozy
kill $DBUS_SESSION_BUS_PID
```
...this is the latest script, have played with other holes punched in the sandbox, makes no difference. 

Cozy version: 1.2.1
Host OS: EasyOS 5.2.2

The thing is, so far I have tested 30 flatpaks, and only two of them don't work, Cozy and QGIS.
Both of those two failures have the same error, ldconfig failure.

Do you have any thoughts why just those two are failing, and the other 28 work?
Cozy and QGIS flatpaks must be doing something different.
I have also raised an issue at the QGIS github repo, but as they have 4,129 open issues, I'm not expecting a speedy response from them.
Hoping that you guys might have some thoughts how to fix it.

**Comment by eMBee** [comment]
looks like a variation of this issue: 

https://github.com/flatpak/flatpak/issues/3365

**Comment by bkauler** [comment]
The problem has been fixed. I changed from ext4 folder encryption fscrypt version-1 to version-2. I was using the e4crypt utility from the e2fsprogs package, however that is only v1. Now changed to use the fscryptctl utility, that supports v2, and now flatpaks are all working.

Note v2 support was introduced in 2020 in the 5.4 kernel.
So closing this issue.

**Comment by geigi** [comment]
Thanks for the update!
