### ISSUE TITLE
Snap package ready and listed in snap-store

### ISSUE THREAD

**Issue by soumyaDghosh** [geigi/cozy#776]
Hello, I have created a snap package for your app, it's just at par with the flatpak, and the same of version of python packages are used. Would like to get it transferred to your account. I'll be happy to transfer the ownership in the snap-store.

**[Cozy](https://snapcraft.io/cozy)**

You can test it here. 

```
[![Get it from the Snap Store](https://snapcraft.io/static/images/badges/en/snap-store-black.svg)](https://snapcraft.io/cozy)
````
If you like, you can publicise the snap package also, by adding this.

**Comment by marxjohnson** [comment]
Thanks for doing this!

**Comment by soumyaDghosh** [comment]
It'd be great if you publicise the snap also.

**Comment by RoninTech** [comment]
I just tried this on my Pi4B with the latest 64bit bullseye.  The snap doesn't work for mp4 files for me.  None of them would import.  So then I installed flatpak and grabbed the latest cozy version from there and everything imported fine.  So something seems to be different between the snap and flatpak releases in relation to mp4 importing.  Both listed their revs as 1.2.1.

**Comment by soumyaDghosh** [comment]
> I just tried this on my Pi4B with the latest 64bit bullseye. The snap doesn't work for mp4 files for me. None of them would import. So then I installed flatpak and grabbed the latest cozy version from there and everything imported fine. So something seems to be different between the snap and flatpak releases in relation to mp4 importing. Both listed their revs as 1.2.1.

Thank you for pointing this out. I thought it can't import, so, I never think about it. But, conincidentally, I submitted a PR which got merged yesterday, has the gstreamer-bad plugins which I guess adds the support for mp4 files. Some time will be needed, after which this library will also be in the gnome-sdk. Means, cozy can be able to import it without any problem. Thanks again for your help.

**Comment by rdbende** [comment]
Hi!

It's always cool to see people being interested in our project, and packaging it. However, we are not interested in adding another official package. The preferred distribution source for Cozy is the Flatpak package on Flathub.
