### ISSUE TITLE
An Exception occurs while importing 

### ISSUE THREAD

**Issue by cjfloss** [geigi/cozy#78]
> Exception in thread Thread-3:
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/peewee.py", line 3830, in execute_sql
>     cursor.execute(sql, params or ())
> sqlite3.OperationalError: database is locked
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
>     self.run()
>   File "/usr/lib/python3.5/threading.py", line 862, in run
>     self._target(*self._args, **self._kwargs)
>   File "/usr/lib/python3/dist-packages/cozy/importer.py", line 69, in update_database
>     imported = import_file(file, directory, path, update=True)
>   File "/usr/lib/python3/dist-packages/cozy/importer.py", line 252, in import_file
>     if db.Book.select().where(db.Book.name == book_name).count() < 1:
>   File "/usr/lib/python3/dist-packages/peewee.py", line 3200, in count
>     return self.aggregate(convert=False) or 0
>   File "/usr/lib/python3/dist-packages/peewee.py", line 3193, in aggregate
>     return self._aggregate(aggregation).scalar(convert=convert)
>   File "/usr/lib/python3/dist-packages/peewee.py", line 2948, in scalar
>     row = self._execute().fetchone()
>   File "/usr/lib/python3/dist-packages/peewee.py", line 2939, in _execute
>     return self.database.execute_sql(sql, params, self.require_commit)
>   File "/usr/lib/python3/dist-packages/peewee.py", line 3837, in execute_sql
>     self.commit()
>   File "/usr/lib/python3/dist-packages/peewee.py", line 3656, in __exit__
>     reraise(new_type, new_type(*exc_args), traceback)
>   File "/usr/lib/python3/dist-packages/peewee.py", line 135, in reraise
>     raise value.with_traceback(tb)
>   File "/usr/lib/python3/dist-packages/peewee.py", line 3830, in execute_sql
>     cursor.execute(sql, params or ())
> peewee.OperationalError: database is locked

**Comment by geigi** [comment]
Thanks for reporting. Looks like your database was locked, I need to implement something to let the user know when this happens.

**Comment by geigi** [comment]
I've changed how the database connection is established, this might fix your error. Feel free to reopen the issue if it still occurs :)
