### ISSUE TITLE
Use AdwActionRow for chapter elements

### ISSUE THREAD

**Issue by rdbende** [geigi/cozy#805]
Currently the chapter list has a very GTK 3-ish design:

![Cozy with current GtkBox + CSS styling](https://github.com/geigi/cozy/assets/77941087/a7f6dbff-2996-4812-8043-c08e26c5ed45)

It could use libadwaita's list row widgets instead, for a more contemporary look:

![Cozy with AdwActionRows](https://github.com/geigi/cozy/assets/77941087/781c493b-2ebd-432b-909f-583ddcd18e2f)

This is also what other apps, like Podcasts and Spot do:

![Podcasts](https://github.com/geigi/cozy/assets/77941087/c322e683-9b16-4183-84db-c6092407f2bd)
![Spot](https://github.com/geigi/cozy/assets/77941087/40a01c0a-9df7-4cdb-af21-b5507618423a)

**Comment by geigi** [comment]
Good idea! Looks very nice.

**Comment by rdbende** [comment]
I haven't had time to finish it up, but I have a development branch for this
