### ISSUE TITLE
Remove dark mode preference

### ISSUE THREAD

**Issue by rdbende** [geigi/cozy#829]
1. With libadwaita, Cozy now automatically adapts to the global dark mode
2. Generally, apps shouldn't provide their own dark mode switcher, unless they are heavily text-based, or are in the foreground for long periods of time.

From the GNOME HIG:
> Per-app style preferences are primarily useful for text editing apps, or apps which users use for long periods of time. In these cases, the style preference can be useful as a way of controlling visual contrast and brightness.

**Comment by geigi** [comment]
Forgot that the PR is still open, but sounds reasonable!
