### ISSUE TITLE
zh_CN.po

### ISSUE THREAD

**Issue by trampover** [geigi/cozy#83]
# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: \n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2018-01-05 19:55+0100\n"
"PO-Revision-Date: 2018-01-28 23:03+0800\n"
"Language-Team: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: Poedit 2.0.4\n"
"Last-Translator: 金立龙 <trampover@gmail.com>\n"
"Plural-Forms: nplurals=1; plural=0;\n"
"Language: zh_CN\n"

#: cozy/book_element.py:63 cozy/search_results.py:124
msgid "Play this book"
msgstr "朗读这本书"

#: cozy/book_element.py:186
msgid "Open book overview"
msgstr "打开书籍概览"

#: cozy/book_element.py:313
msgid "Play this part"
msgstr "朗读这个部分"

#: cozy/file_not_found_dialog.py:64
msgid "All files"
msgstr "所有文件"

#: cozy/search_results.py:72
msgid "Jump to author "
msgstr "跳转到作者"

#: cozy/search_results.py:75
msgid "Jump to reader "
msgstr "跳转到朗读者"

#: cozy/importer.py:246
msgid "Unknown Author"
msgstr "未知作者"

#: cozy/importer.py:248
msgid "Unknown Reader"
msgstr "未知朗读者"

#: cozy/ui.py:395 cozy/ui.py:718 data/ui/timer_popover.ui:86
msgid "min"
msgstr "秒"

#: cozy/ui.py:567
msgid "Importing Audiobooks"
msgstr "导入有声读物"

#: cozy/ui.py:629 cozy/ui.py:633 cozy/ui.py:1243 cozy/ui.py:1252
msgid "All"
msgstr "所有"

#: cozy/ui.py:630 cozy/ui.py:634
msgid "Display all books"
msgstr "显示所有书籍"

#: cozy/ui.py:850
msgid "Changing audio book location..."
msgstr "更改有声书籍位置..."

#: data/ui/main_window.ui:67
msgid "Select by author"
msgstr "查看作者"

#: data/ui/main_window.ui:76
msgid "<big>Author</big>"
msgstr "<big>作者</big>"

#: data/ui/main_window.ui:85
msgid "Author filter button"
msgstr "作者过滤按钮"

#: data/ui/main_window.ui:86
msgid "Filter books by author"
msgstr "按作者选择"

#: data/ui/main_window.ui:106
msgid "Select by reader"
msgstr "查看朗读者"

#: data/ui/main_window.ui:114
msgid "<big>Reader</big>"
msgstr "<big>朗读者</big>"

#: data/ui/main_window.ui:123
msgid "Reader filter button"
msgstr "朗读者过滤按钮"

#: data/ui/main_window.ui:124
msgid "Filter books by reader"
msgstr "按朗读者选择"

#: data/ui/main_window.ui:178
msgid "List of authors"
msgstr "作者名单"

#: data/ui/main_window.ui:194 data/ui/search_popover.ui:107
msgid "Author"
msgstr "作者"

#: data/ui/main_window.ui:212
msgid "List of readers"
msgstr "朗读者者名单"

#: data/ui/main_window.ui:228 data/ui/search_popover.ui:201
msgid "Reader"
msgstr "朗读者"

#: data/ui/main_window.ui:275
msgid "List of books"
msgstr "书目清单"

#: data/ui/main_window.ui:309
msgid "Importing your audiobooks..."
msgstr "导入您的有声读物..."

#: data/ui/main_window.ui:360
msgid "Import your Audiobooks"
msgstr "导入您的有声读物"

#: data/ui/main_window.ui:376
msgid ""
"Cozy automatically imports your audiobooks in one directory - your library"
msgstr "朗读者自动将您的有声读物导入一个目录 - 您的图书目录"

#: data/ui/main_window.ui:416
msgid "Drag & Drop"
msgstr "拖放导入"

#: data/ui/main_window.ui:432
msgid ""
"Drag your audiobooks into cozy and the will be automatically imported to "
"your library"
msgstr "将您的有声读物拖到朗读者程序中，那么将被自动导入到您的图书目录"

#: data/ui/main_window.ui:492
msgid "Change Audiobooks Folder"
msgstr "更改您的图书目录"

#: data/ui/main_window.ui:508
msgid "Load audiobooks from a folder, network drive or an external disk"
msgstr "从文件夹，网络驱动器或外部磁盘加载有声读物"

#: data/ui/main_window.ui:537
msgid "Location of your audiobooks"
msgstr "你的有声读物的位置"

#: data/ui/main_window.ui:573
msgid "Auto scan switch"
msgstr "自动扫描开关"

#: data/ui/main_window.ui:574 data/ui/main_window.ui:589
msgid "Automatically import new audiobooks on startup"
msgstr "在启动时自动导入新的有声读物"

#: data/ui/main_window.ui:642
msgid "Rewind 30 seconds"
msgstr "后退30秒"

#: data/ui/main_window.ui:650
msgid "Rewind button"
msgstr "后退"

#: data/ui/main_window.ui:651
msgid "Jump back 30 seconds"
msgstr "回跳30分"

#: data/ui/main_window.ui:668
msgid "Start playback"
msgstr "开始播放"

#: data/ui/main_window.ui:676
msgid "Play/Pause Button"
msgstr "播放/暂停"

#: data/ui/main_window.ui:677
msgid "Start or pause the playback"
msgstr "开始或暂停播放"

#: data/ui/main_window.ui:693
msgid "Volume control"
msgstr "音量控制"

#: data/ui/main_window.ui:771
msgid "Currently playing"
msgstr "正在播放"

#: data/ui/main_window.ui:789
msgid "Booktitle"
msgstr "书名"

#: data/ui/main_window.ui:790
msgid "Title of currently playing book"
msgstr "当前正在播放的书的书名"

#: data/ui/main_window.ui:815
msgid "Part name"
msgstr "章节名字"

#: data/ui/main_window.ui:816
msgid "Title of the currently playing part"
msgstr "当前播放部分的书名"

#: data/ui/main_window.ui:858
msgid "Elapsed time"
msgstr "已用时间"

#: data/ui/main_window.ui:866
msgid "Time elapsed"
msgstr "已用时间"

#: data/ui/main_window.ui:867
msgid "Elapsed time of current part"
msgstr "正在朗读部分已用时间"

#: data/ui/main_window.ui:882
msgid "Scrubb through current part"
msgstr "拖动快进或快退当前朗读部分"

#: data/ui/main_window.ui:888
msgid "Position slider"
msgstr "位置"

#: data/ui/main_window.ui:889
msgid "Position of the current part in seconds"
msgstr "当前部分的位置，以秒为单位"

#: data/ui/main_window.ui:903
msgid "Remaining time"
msgstr "剩余时间:"

#: data/ui/main_window.ui:911
msgid "Time remaining"
msgstr "剩余时间:"

#: data/ui/main_window.ui:912
msgid "Remaining time of current part"
msgstr "正在朗读部分已用时间"

#: data/ui/main_window.ui:987
msgid "Working..."
msgstr "进行中..."

#: data/ui/main_window.ui:992
msgid "Currently working"
msgstr "正在进行"

#: data/ui/main_window.ui:1007
msgid "Playback speed"
msgstr "播放速度"

#: data/ui/main_window.ui:1028
msgid "Sleep timer"
msgstr "睡眠时间"

#: data/ui/main_window.ui:1039
msgid "Timer menu button"
msgstr "定时器菜单按钮"

#: data/ui/main_window.ui:1040
msgid "Open the sleep timer popover"
msgstr "打开睡眠计时器弹出窗口"

#: data/ui/main_window.ui:1056
msgid "Search your library"
msgstr "在您的书库中查找"

#: data/ui/main_window.ui:1067
msgid "Search menu button"
msgstr "搜索菜单按钮"

#: data/ui/main_window.ui:1068
msgid "Open the search popover"
msgstr "打开搜索弹出窗口"

#: data/ui/main_window.ui:1082
msgid "Options"
msgstr "显示选项"

#: data/ui/main_window.ui:1093
msgid "Options menu button"
msgstr "显示选项按钮"

#: data/ui/main_window.ui:1094
msgid "Open the options popover"
msgstr "打开显示选项弹出窗口"

#: data/ui/about.ui:11
msgid "Support me on Patreon: https://www.patreon.com/geigi"
msgstr "在Patreon上支持我:https://www.patreon.com/geigi"

#: data/ui/about.ui:13
msgid "GitHub"
msgstr "GitHub"

#: data/ui/app_menu.ui:7
msgid "_Scan Directory"
msgstr "扫描目录"

#: data/ui/app_menu.ui:13
msgid "_Preferences"
msgstr "偏好设置"

#: data/ui/app_menu.ui:19
msgid "_Help"
msgstr "帮助"

#: data/ui/app_menu.ui:23
msgid "_About"
msgstr "关于"

#: data/ui/app_menu.ui:27
msgid "_Quit"
msgstr "退出"

#: data/ui/file_not_found.ui:19
msgid "Cancel"
msgstr "取消"

#: data/ui/file_not_found.ui:32
msgid "Locate"
msgstr "定位"

#: data/ui/file_not_found.ui:86
msgid "File not found"
msgstr "找不到文件"

#: data/ui/file_not_found.ui:119
msgid "This file could not be found. Do you want to locate it manually?"
msgstr "无法找到此文件。 您想手动找到它吗？"

#: data/ui/import_failed.ui:23
msgid "Ok"
msgstr "好的"

#: data/ui/import_failed.ui:77
msgid "Some files could not be imported"
msgstr "有些文件无法导入"

#: data/ui/import_failed.ui:130
msgid ""
"This can have multiple reasons:\n"
"- The audio format is not supported\n"
"- The file(s) are no valid audio files\n"
"- The file(s) are corrupt"
msgstr ""
"这可能有多种原因：\n"
"- 不支持音频格式\n"
"- 文件没有有效的音频文件\n"
"- 文件已损坏"

#: data/ui/settings.ui:27 data/ui/settings.ui:102
msgid "Order by"
msgstr "按顺序排列"

#: data/ui/settings.ui:37
msgid "Newest"
msgstr "最新"

#: data/ui/settings.ui:54
msgid "Year"
msgstr "年份"

#: data/ui/settings.ui:72
msgid "Name"
msgstr "名字"

#: data/ui/settings.ui:143
msgid "Appearance"
msgstr "外观"

#: data/ui/settings.ui:158
msgid "Suspend system on timer"
msgstr "系统挂起定时器"

#: data/ui/settings.ui:194
msgid "Replay 30 seconds"
msgstr "重播30秒"

#: data/ui/settings.ui:229
msgid "Automatic media scan"
msgstr "自动扫描您的书籍"

#: data/ui/settings.ui:260
msgid "Behaviour"
msgstr "行为"

#: data/ui/settings.ui:276
msgid "Follow symlinks"
msgstr "符号链接"

#: data/ui/settings.ui:314 data/ui/settings.ui:329
msgid "Audio books location"
msgstr "书库的位置"

#: data/ui/settings.ui:351
msgid "Files"
msgstr "文件"

#: data/ui/search_popover.ui:24
msgid "Search"
msgstr "搜索"

#: data/ui/search_popover.ui:36
msgid "Search box"
msgstr "搜索框"

#: data/ui/search_popover.ui:37
msgid "Search your audiobook library"
msgstr "在您的书库中搜索"

#: data/ui/search_popover.ui:67
msgid "Which book are you looking for?"
msgstr "哪本书是您需要看的?"

#: data/ui/search_popover.ui:154
msgid "Book"
msgstr "书"

#: data/ui/search_popover.ui:248
msgid "Part"
msgstr "章节"

#: data/ui/search_popover.ui:295
msgid "Nothing found :("
msgstr "什么也么找到:("

#: data/ui/timer_popover.ui:32
msgid "Toggle the timer on/off"
msgstr "打开/关闭定时器"

#: data/ui/timer_popover.ui:36
msgid "Timer toggle button"
msgstr "定时器按钮"

#: data/ui/timer_popover.ui:37
msgid "Switch the sleep timer on or off"
msgstr "打开或关闭睡眠定时器"

#: data/ui/timer_popover.ui:52 data/ui/timer_popover.ui:80
msgid "Timer duration"
msgstr "计时器时间"

#: data/ui/timer_popover.ui:65
msgid "Timer duration slider"
msgstr "计时器滑块"

#: data/ui/timer_popover.ui:66 data/ui/timer_popover.ui:93
msgid "Set the sleep timer duration in minutes"
msgstr "以分钟为单位设置睡眠定时器的时间"

#: data/ui/timer_popover.ui:92
msgid "Timer duration spin button"
msgstr "计时器持续时间旋钮"

**Comment by geigi** [comment]
Thanks! I'll add this to transifex for later translations. It'll be shipping with the next update ;)

**Comment by geigi** [comment]
I've uploaded this to transifex: https://www.transifex.com/geigi/cozy/language/zh_CN/
