### ISSUE TITLE
Remove Items from Recents

### ISSUE THREAD

**Issue by Haaruun-I** [geigi/cozy#851]
Hi, I really love the cozy app, but I noticed the  "Recents" screen gets pretty. cluttered after a while of using the app.
It would be great if i were able to keep only a few books there at a time instead of *every* book i ever opened.

Maybe there could be a button next to a play button to "reset" it back to an unplayed state?

**Comment by Haaruun-I** [comment]
i have a prototype in https://github.com/Haaruun-I/cozy/tree/prototype_remove_button, this is my first time working with gtk so its a little rough (icons missing, wierd size changing buttons) but its good enough for me

[Screencast from 2024-01-23 16-30-42.webm](https://github.com/geigi/cozy/assets/22063464/7cd8418b-f595-429b-bd22-fb0ee85c16e8)

**Comment by rdbende** [comment]
Instead of a button in the book page, I'd go with a menu item in the right click menu on the recents screen. 

IMO it would also make more sense if books that haven't been listened to in the past 1-2 weeks were automatically removed from the recents screen.
