### ISSUE TITLE
Appdata screenshot guidelines

### ISSUE THREAD

**Issue by bertob** [geigi/cozy#854]
As part of a new curation and quality initiative, Flathub now has [Appdata quality guidelines](https://docs.flathub.org/docs/for-app-authors/appdata-guidelines/quality-guidelines), which Cozy is already following almost perfectly. The only issue currently is that the screenshots are using non-default window decorations (should be close-only), so it'd be appreciated if this could be fixed next time screenshots are retaken.

[This blog post](https://docs.flathub.org/blog/quality-moderation) has a bit more context in case you're interested.

**Comment by rdbende** [comment]
Thanks! I'll definitely keep this in mind, though I don't see when a new release will be ready.

I'm closing #827 as a duplicate, since this one contains more info.

**Comment by bertob** [comment]
Ah woops, sorry for re-filing :sweat_smile:

**Comment by rdbende** [comment]
Resolved by d732b32
