### ISSUE TITLE
Publish fresh release?

### ISSUE THREAD

**Issue by makefu** [geigi/cozy#889]
### Bug/Feature description

in nixpkgs the "invalid version" issue #762 came up in https://github.com/NixOS/nixpkgs/issues/291085 . it would be great if a new release with the fix could be published no patches have to be backported to 1.2.1 in the distributions.

Cheers!

### Steps to reproduce

`nix run github:NixOS/nixpkgs/nixos-23.11#cozy`

### System Information
- Operating System: nixos 23.11
- Installation source: nixpkgs nixos-23.11
- Version of cozy: 1.2.1

**Comment by rdbende** [comment]
There's a new release coming soon. We're currently waiting for translations, and after that @geigi can hopefully release 1.3.0

**Comment by makefu** [comment]
That is great to hear, thanks!

**Comment by rdbende** [comment]
https://github.com/geigi/cozy/releases/tag/1.3.0

**Comment by makefu** [comment]
Thanks!
