### ISSUE TITLE
Some Notes 

### ISSUE THREAD

**Issue by sudo-give-me-coffee** [geigi/cozy#89]
Flatpak: 

* Can't access any file outside "home" directory
* Visual looks bad

Deb package:

* Reverse DNS in package name
* Reverse DNS in binary file name (/usr/bin/com.github.geigi.cozy)
* Reverse DNS in desktop file (/usr/share/applications/)
* Absolute paths in (/usr/bin/com.github.geigi.cozy)

Maybe is the cause of AppImage build failure https://github.com/geigi/cozy/issues/29

**Comment by geigi** [comment]
Thanks for your input!

The guys from flathub recommended to restrict the file access as much as possible. But you can override this by yourself: https://github.com/geigi/cozy/issues/61

Can you specify what looks bad? Are you using the default gtk theme?

Thanks for the AppImage hint, I'll give this a try ;)

**Comment by geigi** [comment]
I've checked about the absolute paths, this shouldn't be an issue because these paths are generated by meson at build time and are always correct for the platform you're building on. Also I didn't found a solution on how to get the correct path to these folders with python directly.
