### ISSUE TITLE
AppStream brand color: Use distinct color for dark

### ISSUE THREAD

**Issue by bertob** [geigi/cozy#894]
The brand color for dark should not be the same as the light one, because it might be used at large sizes where light colors can be disruptive when the rest of the UI is dark. I'd use a darker orange, e.g. `#a44811`.

![image](https://github.com/geigi/cozy/assets/1908896/37b0e68f-172b-49f8-8a3f-7e9ed70bc4f7)

**Comment by rdbende** [comment]
Note to self: 8acef86
