### ISSUE TITLE
Use sentence case in welcome screen

### ISSUE THREAD

**Issue by heldderarbeit** [geigi/cozy#961]
### Bug/Feature description

The text in the welcome screen when opening the app for the first time is mostly presented in Capitalized Case (but not for every word).

![Screenshot from 2024-09-19 18-28-15](https://github.com/user-attachments/assets/1e4bbb42-1a70-4e5e-b0cf-169f239ce874)

`Select a Folder, or Drag Audiobooks Here to Add Them to Your Library  `

Maybe it would be easier to read if it were in Sentence case and without the comma:

`Select a folder or drag audiobooks here to add them to your library  `

The comma seems not to be [necessary in this case](https://english.lingolia.com/de/schreibschule/zeichensetzung/komma), since the main clauses are very short. It would also be consistent with [English Capitalization Rules ](https://www.grammarly.com/blog/capitalization-rules/)and consistent with the welcome screen for other Gnome apps, which usually use Sentence Case:

![Screenshot from 2024-09-19 18-04-02](https://github.com/user-attachments/assets/fb353ad0-686e-438a-bd66-5e6149cb2c5a)

[
![Screenshot from 2024-09-19 18-18-56](https://github.com/user-attachments/assets/bed56cb6-21a4-4f8f-9456-8b5db389e893)
](url)

![Screenshot from 2024-09-19 18-20-31](https://github.com/user-attachments/assets/89c87e90-d610-4af8-ace4-08193ea38387)

![Screenshot from 2024-09-19 18-19-28](https://github.com/user-attachments/assets/a068ee97-1f59-45be-b16f-f8f4a7cc3a94)

### Steps to reproduce
Open the app for the first time

### System Information
- Operating System: Arch
- Installation source:  Flathub
- Version of cozy:  1.3.0

**Comment by rdbende** [comment]
You're right, and I think I already had a local fix for this that I forgot to publish. Will fix soon
