### ISSUE TITLE
Cozy refuses to launch. Displays in taskbar then fails to open at all.

### ISSUE THREAD

**Issue by RetroJedi** [geigi/cozy#962]
### Bug/Feature description
Using `sudo zypper install cozy` I install cozy & cozy-lang. I launch the app and it hangs for a second with the app displaying in my task bar, and the icon bouncing on my cursor as it tries to open, and then it doesn't open. No popup or anything. No matter where I launch from, it doesn't work. I don't have another linux system to test this on, or I would.

### Steps to reproduce
Search for cozy in super key search bar then attempt to launch
Open it's page in discover and attempt to launch
I attempted to open the file from `/home/usr/.var/app/` but there is no directory for cozy.

### System Information
- Operating System: OpenSUSE Tumbleweed
- Installation source: Discover, zypper install in konsole, and from here.
- Version of cozy: cozy-1.2.1-2.5.noarch (according to my terminal)

**Comment by rdbende** [comment]
Hi!

Could you send some logs by launcing it from the terminal (should be `com.gitlab.geigi.cozy`, unless your package manager overwrites that), and copy what it outputs?
Also, there were a couple of issues that can cause this in v1.2.1, so it can be, that your version of Cozy is simply too old. If Zypper doesn't have a newer package, then you could try using our Flatpak, which is at version 1.3.0.

**Comment by RetroJedi** [comment]
I installed it using the Flatpak and installed 1.3 and it works now. Thank you!
