### ISSUE TITLE
Please update flatpak runtime

### ISSUE THREAD

**Issue by Scotty-Trees** [geigi/cozy#967]
Currently on Fedora 41, Gnome 47 and after running `flatpak update` I came across this warning. Please update to the lastest flatpak runtime, thank you. 

```
Looking for updates…

Info: runtime org.gnome.Platform branch 45 is end-of-life, with reason:
   The GNOME 45 runtime is no longer supported as of September 18, 2024. Please ask your application developer to migrate to a supported platform.
Info: applications using this runtime:
   com.github.geigi.cozy
```

**Comment by Miccio-AN** [comment]
Here the same on Debian 12, Gnome 43.9
Thanks!

**Comment by pseudomonas** [comment]
And same on Ubuntu 24.04. I think it must be everywhere that uses flatpak?

**Comment by kureta** [comment]
I am not sure if it is related but on Gnome Software it says "Software no longer supported", which, I assume, is not true.

![image](https://github.com/user-attachments/assets/623f900d-e163-4fbc-9afd-4982388ae789)

**Comment by pseudomonas** [comment]
> I am not sure if it is related but on Gnome Software it says "Software no longer supported", which, I assume, is not true.

I don't think that's related; I think that's another repository and not the Flatpak one.

**Comment by rdbende** [comment]
Was fixed by https://github.com/flathub/com.github.geigi.cozy/pull/15
New release is already on Flathub
