### ISSUE TITLE
can't uninstall

### ISSUE THREAD

**Issue by Meresmata** [geigi/cozy#97]
Hi,

 installed cozy via flatpak with the command from the github site. But now I can't uninstall cozy. It is in the list of flatpak list. But when I insert the uninstall, that it states that their is no package with that name.

**Comment by geigi** [comment]
Try 
```
flatpak list
```
Or 
```
flatpak --user list
```
Is com.github.geigi.cozy listed there? Otherwise it is Not installed correctly anymore

**Comment by Meresmata** [comment]
Hi, I just want to paste the outcome of the commands:

:~$ flatpak list
com.github.geigi.cozy
:~$ flatpak list --user
com.github.geigi.cozy
:~$ flatpak uninstall com.github.geigy --user
Fehler: com.github.geigy master ist nicht installiert
:~$ flatpak uninstall com.github.geigy
Fehler: com.github.geigy master ist nicht installiert

Translated:
      Error: ... is not installed.

**Comment by geigi** [comment]
Try 
```
flatpak uninstall com.github.geigi.cozy
```
The package is Not called com.github.geigy

**Comment by Meresmata** [comment]
That information should be enough for flatpak. Using the full name did not change anything:

x@y:~$ flatpak uninstall com.github.geigi.cozy
Fehler: com.github.geigi.cozy master ist nicht installiert

Even more interessing is:

x@y:~$ flatpak install --user flathub com.github.geigi.cozy
Fehler: com.github.geigi.cozy/x86_64/stable already installed


What helped was:  flatpak uninstall --user com.github.geigi.cozy/x86_64/stable

**Comment by geigi** [comment]
OK I didnt know that... Thanks for Posting the solution
