### ISSUE TITLE
Using external media

### ISSUE THREAD

**Issue by Meresmata** [geigi/cozy#98]
Hi I want to add audiobooks from a SDCard. But to add files from subfolders of /media/ is not possible.

**Comment by geigi** [comment]
You can override this limitation, have an Look at #62

**Comment by Meresmata** [comment]
I can find the entry /media:

![grafik](https://user-images.githubusercontent.com/6282825/37259139-fbcdbd14-2582-11e8-8a42-d27334734846.png)

**Comment by geigi** [comment]
I'll have a look at it tomorrow ;)

**Comment by geigi** [comment]
Ok so you can pass absolute paths to flatpak to allow them in the sandbox like this:
`flatpak --user override --filesystem=/media com.github.geigi.cozy`

**Comment by geigi** [comment]
I'm going to include this in the readme ;)

**Comment by Meresmata** [comment]
So I tried that! Neighter did I find the /media folder. And when I tried Drag and Drop! I let it import for about 40 min. Until then it was nut finished so I closed the application and after a restart I did not find any file imported!

So: flatpak --user override --filesystem=/media com.github.geigi.cozy

Seames not to be the solution!

**Comment by geigi** [comment]
Ok thats weird, it was working fine on my system... Can you try another folder or the whole filesystem with `--filesystem=host`?

**Comment by Meresmata** [comment]
Ok, now was able to add the media... now and tried to import twice. But I seams like cozy crashed just the moment it finished. Nothing was imported. Files are about about 70 GB with file ending ogg. Mainly in opus Codex, some in vorbis .

**Comment by geigi** [comment]
Ok this sounds like there went something wrong during the import. I still need to implement a log file but in the meantime could you delete the database, start cozy from the terminal and post the log here?

rm -rf ~/.local/share/cozy
flatpak run com.github.geigi.cozy > cozy.log

**Comment by geigi** [comment]
The next version will come with a fix that should prevent cozy from crashing while importing files even if something goes wrong. You also will get a list of files in a dialog that could not be imported after the process is finished. Feel free to reopen if you still have problems with your files.
