### ISSUE TITLE
Radio Support

### ISSUE THREAD

**Issue by vendforce** [geigi/cozy#99]
Is there future releases going to support listening to radio,also is there an option to close/hide the player in the background put still play the music

**Comment by geigi** [comment]
No this is not planned as Cozy is mainly focused on audiobooks and not music playback. I suggest Lollypop for listening to radio: https://gitlab.gnome.org/gnumdk/lollypop
You can hide the cozy window under Gnome (maybe other environments too) with the shortcut SUPER+H ;)
